// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/battle.bin`, plans/build-data.md).

//! The battle's and menus' parameters (gcmn): skills, items, equipment, enemies, bosses, the party's AI.

pub use super::types::{
    AIParam, Attribute, BattleAbility, BattleEffect, BossParamData, CharBaseParam, CharParamElement, EnemyList,
    EnemyParamData, EnemyRace, EnemySkillParam, EnemyTable, EnemyThinkParam, Entry, EquipmentParam, FileList,
    GimmickParam, GimmickTable, ItemList, ItemParam, LevelUpTbl, NpcParam, NpcTable, SkillParam, Tolerance,
};
use crate::volume::Volume;

/// What an equipment row's numbers read as where there is no row (id -1, the bytes before a table).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EquipBefore {
    pub elm: CharParamElement,
    pub beff: BattleEffect,
    pub level: i16,
    pub skill_id: [i16; 3],
    pub price: i32,
}

impl crate::store::Load for EquipBefore {
    fn load(r: &mut crate::store::Reader) -> Self {
        EquipBefore {
            elm: crate::store::Load::load(r),
            beff: crate::store::Load::load(r),
            level: crate::store::Load::load(r),
            skill_id: crate::store::Load::load(r),
            price: crate::store::Load::load(r),
        }
    }
}

/// The `battle` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Battle {
    /// `skillTbl`: `ccGetSkillParam(i)`.
    pub skills: &'static [SkillParam],
    /// `BossSkillTbl`: 79 from Mutation on.
    pub boss_skills: &'static [SkillParam],
    /// `enemyTbl`
    pub enemies: &'static [EnemyTable],
    /// `gimmickTbl`: 46 from Mutation on.
    pub gimmicks: &'static [GimmickTable],
    /// `npcTbl`: the towns' people (`param.base.msg` is where their lines are); 184 from Mutation on.
    pub npcs: &'static [NpcTable],
    /// `ccEnemyListInfo`: by server and type, the `enemyTbl` rows an area spawns.
    pub enemy_lists: &'static [[EnemyList; 7]],
    /// `bossTbl`
    pub bosses: &'static [BossParamData],
    /// `itemTblR`: category 10.
    pub item_r: &'static [ItemParam],
    /// `itemTblD`: category 11.
    pub item_d: &'static [ItemParam],
    /// `itemTblU`: category 12.
    pub item_u: &'static [ItemParam],
    /// `itemTblX`: category 13.
    pub item_x: &'static [ItemParam],
    /// `itemTblT`: category 14.
    pub item_t: &'static [ItemParam],
    /// `itemTblE`: category 15.
    pub item_e: &'static [ItemParam],
    /// `equipmentHeadTbl`: category 6.
    pub head: &'static [EquipmentParam],
    /// `equipmentBodyTbl`: category 7.
    pub body: &'static [EquipmentParam],
    /// `equipmentArmTbl`: category 8.
    pub arm: &'static [EquipmentParam],
    /// `equipmentLegTbl`: category 9.
    pub leg: &'static [EquipmentParam],
    /// `equipmentWeapon1Tbl`: job 0's, category 0 (a row more from Mutation on).
    pub weapon1: &'static [EquipmentParam],
    /// `equipmentWeapon2Tbl`
    pub weapon2: &'static [EquipmentParam],
    /// `equipmentWeapon3Tbl`
    pub weapon3: &'static [EquipmentParam],
    /// `equipmentWeapon4Tbl` (a row more from Mutation on)
    pub weapon4: &'static [EquipmentParam],
    /// `equipmentWeapon5Tbl`
    pub weapon5: &'static [EquipmentParam],
    /// `equipmentWeapon6Tbl` (a row more from Mutation on)
    pub weapon6: &'static [EquipmentParam],
    /// The 0x48 bytes before `head`, as a row.
    pub head_before: EquipBefore,
    /// The 0x48 bytes before `body`, as a row.
    pub body_before: EquipBefore,
    /// The 0x48 bytes before `arm`, as a row.
    pub arm_before: EquipBefore,
    /// The 0x48 bytes before `leg`, as a row.
    pub leg_before: EquipBefore,
    /// The 0x48 bytes before `weapon1`, as a row.
    pub weapon1_before: EquipBefore,
    /// The 0x48 bytes before `weapon2`, as a row.
    pub weapon2_before: EquipBefore,
    /// The 0x48 bytes before `weapon3`, as a row.
    pub weapon3_before: EquipBefore,
    /// The 0x48 bytes before `weapon4`, as a row.
    pub weapon4_before: EquipBefore,
    /// The 0x48 bytes before `weapon5`, as a row.
    pub weapon5_before: EquipBefore,
    /// The 0x48 bytes before `weapon6`, as a row.
    pub weapon6_before: EquipBefore,
    /// `LevelUpParamTbl`, by character (21 from Mutation on).
    pub level_up: &'static [LevelUpTbl],
    /// `expCalcTbl`, by level difference + 10.
    pub exp_calc: &'static [i16],
    /// `ccEntryRaceTbl`: `enemyTbl` in groups of `raceNum` rows.
    pub races: &'static [EnemyRace],
    /// `dataDrainErosionTbl`: a Data Drain's side effect by infection / 25.
    pub drain_erosion: &'static [[i32; 16]],
    /// `ccSaveData::AddLvErosion`'s `erosionTbl`.
    pub erosion: &'static [i32],
    /// `spcDefaultItemList` (21 from Mutation on)
    pub spc_default_items: &'static [[ItemList; 10]],
    /// `playerDefaultItemList`
    pub player_default_items: &'static [ItemList],
    /// `playerDefaultImportantItemList`
    pub player_default_important: &'static [ItemList],
    /// `spcAIParam`
    pub ai_params: &'static [AIParam],
    /// `spcDebuffPriorityType`
    pub debuff_priority: &'static [[i16; 9]],
    /// `spcBuffPriorityType`
    pub buff_priority: &'static [[i16; 5]],
    /// `debuffTableIndex`
    pub debuff_table_index: &'static [i16],
    /// `buffTableIndex`
    pub buff_table_index: &'static [i16],
    /// The debuffs' ability skills.
    pub debuff_skill_ability: &'static [i16],
    /// The debuffs' attribute skills.
    pub debuff_skill_attribute: &'static [i16],
    /// The buffs' ability skills.
    pub buff_skill_ability: &'static [i16],
    /// The buffs' attribute skills.
    pub buff_skill_attribute: &'static [i16],
    /// `ccGetItemIcon(cat, id)` by category: each case of its jump table is `li $v0, icon` (or 0).
    pub item_icons: &'static [i32],
    /// `SetItemList`'s page to category: -1 the usable items, -2 the equipment, else the category.
    pub item_pages: &'static [i32],
}

impl crate::store::Load for Battle {
    fn load(r: &mut crate::store::Reader) -> Self {
        Battle {
            skills: crate::store::Load::load(r),
            boss_skills: crate::store::Load::load(r),
            enemies: crate::store::Load::load(r),
            gimmicks: crate::store::Load::load(r),
            npcs: crate::store::Load::load(r),
            enemy_lists: crate::store::Load::load(r),
            bosses: crate::store::Load::load(r),
            item_r: crate::store::Load::load(r),
            item_d: crate::store::Load::load(r),
            item_u: crate::store::Load::load(r),
            item_x: crate::store::Load::load(r),
            item_t: crate::store::Load::load(r),
            item_e: crate::store::Load::load(r),
            head: crate::store::Load::load(r),
            body: crate::store::Load::load(r),
            arm: crate::store::Load::load(r),
            leg: crate::store::Load::load(r),
            weapon1: crate::store::Load::load(r),
            weapon2: crate::store::Load::load(r),
            weapon3: crate::store::Load::load(r),
            weapon4: crate::store::Load::load(r),
            weapon5: crate::store::Load::load(r),
            weapon6: crate::store::Load::load(r),
            head_before: crate::store::Load::load(r),
            body_before: crate::store::Load::load(r),
            arm_before: crate::store::Load::load(r),
            leg_before: crate::store::Load::load(r),
            weapon1_before: crate::store::Load::load(r),
            weapon2_before: crate::store::Load::load(r),
            weapon3_before: crate::store::Load::load(r),
            weapon4_before: crate::store::Load::load(r),
            weapon5_before: crate::store::Load::load(r),
            weapon6_before: crate::store::Load::load(r),
            level_up: crate::store::Load::load(r),
            exp_calc: crate::store::Load::load(r),
            races: crate::store::Load::load(r),
            drain_erosion: crate::store::Load::load(r),
            erosion: crate::store::Load::load(r),
            spc_default_items: crate::store::Load::load(r),
            player_default_items: crate::store::Load::load(r),
            player_default_important: crate::store::Load::load(r),
            ai_params: crate::store::Load::load(r),
            debuff_priority: crate::store::Load::load(r),
            buff_priority: crate::store::Load::load(r),
            debuff_table_index: crate::store::Load::load(r),
            buff_table_index: crate::store::Load::load(r),
            debuff_skill_ability: crate::store::Load::load(r),
            debuff_skill_attribute: crate::store::Load::load(r),
            buff_skill_ability: crate::store::Load::load(r),
            buff_skill_attribute: crate::store::Load::load(r),
            item_icons: crate::store::Load::load(r),
            item_pages: crate::store::Load::load(r),
        }
    }
}

impl Battle {
    pub fn skills(&self) -> &'static [SkillParam] {
        self.skills
    }
    pub fn boss_skills(&self) -> &'static [SkillParam] {
        self.boss_skills
    }
    pub fn enemies(&self) -> &'static [EnemyTable] {
        self.enemies
    }
    pub fn gimmicks(&self) -> &'static [GimmickTable] {
        self.gimmicks
    }
    pub fn npcs(&self) -> &'static [NpcTable] {
        self.npcs
    }
    pub fn enemy_lists(&self) -> &'static [[EnemyList; 7]] {
        self.enemy_lists
    }
    pub fn bosses(&self) -> &'static [BossParamData] {
        self.bosses
    }
    pub fn item_r(&self) -> &'static [ItemParam] {
        self.item_r
    }
    pub fn item_d(&self) -> &'static [ItemParam] {
        self.item_d
    }
    pub fn item_u(&self) -> &'static [ItemParam] {
        self.item_u
    }
    pub fn item_x(&self) -> &'static [ItemParam] {
        self.item_x
    }
    pub fn item_t(&self) -> &'static [ItemParam] {
        self.item_t
    }
    pub fn item_e(&self) -> &'static [ItemParam] {
        self.item_e
    }
    pub fn head(&self) -> &'static [EquipmentParam] {
        self.head
    }
    pub fn body(&self) -> &'static [EquipmentParam] {
        self.body
    }
    pub fn arm(&self) -> &'static [EquipmentParam] {
        self.arm
    }
    pub fn leg(&self) -> &'static [EquipmentParam] {
        self.leg
    }
    pub fn weapon1(&self) -> &'static [EquipmentParam] {
        self.weapon1
    }
    pub fn weapon2(&self) -> &'static [EquipmentParam] {
        self.weapon2
    }
    pub fn weapon3(&self) -> &'static [EquipmentParam] {
        self.weapon3
    }
    pub fn weapon4(&self) -> &'static [EquipmentParam] {
        self.weapon4
    }
    pub fn weapon5(&self) -> &'static [EquipmentParam] {
        self.weapon5
    }
    pub fn weapon6(&self) -> &'static [EquipmentParam] {
        self.weapon6
    }
    pub fn head_before(&self) -> EquipBefore {
        self.head_before
    }
    pub fn body_before(&self) -> EquipBefore {
        self.body_before
    }
    pub fn arm_before(&self) -> EquipBefore {
        self.arm_before
    }
    pub fn leg_before(&self) -> EquipBefore {
        self.leg_before
    }
    pub fn weapon1_before(&self) -> EquipBefore {
        self.weapon1_before
    }
    pub fn weapon2_before(&self) -> EquipBefore {
        self.weapon2_before
    }
    pub fn weapon3_before(&self) -> EquipBefore {
        self.weapon3_before
    }
    pub fn weapon4_before(&self) -> EquipBefore {
        self.weapon4_before
    }
    pub fn weapon5_before(&self) -> EquipBefore {
        self.weapon5_before
    }
    pub fn weapon6_before(&self) -> EquipBefore {
        self.weapon6_before
    }
    pub fn level_up(&self) -> &'static [LevelUpTbl] {
        self.level_up
    }
    pub fn exp_calc(&self) -> &'static [i16] {
        self.exp_calc
    }
    pub fn races(&self) -> &'static [EnemyRace] {
        self.races
    }
    pub fn drain_erosion(&self) -> &'static [[i32; 16]] {
        self.drain_erosion
    }
    pub fn erosion(&self) -> &'static [i32] {
        self.erosion
    }
    pub fn spc_default_items(&self) -> &'static [[ItemList; 10]] {
        self.spc_default_items
    }
    pub fn player_default_items(&self) -> &'static [ItemList] {
        self.player_default_items
    }
    pub fn player_default_important(&self) -> &'static [ItemList] {
        self.player_default_important
    }
    pub fn ai_params(&self) -> &'static [AIParam] {
        self.ai_params
    }
    pub fn debuff_priority(&self) -> &'static [[i16; 9]] {
        self.debuff_priority
    }
    pub fn buff_priority(&self) -> &'static [[i16; 5]] {
        self.buff_priority
    }
    pub fn debuff_table_index(&self) -> &'static [i16] {
        self.debuff_table_index
    }
    pub fn buff_table_index(&self) -> &'static [i16] {
        self.buff_table_index
    }
    pub fn debuff_skill_ability(&self) -> &'static [i16] {
        self.debuff_skill_ability
    }
    pub fn debuff_skill_attribute(&self) -> &'static [i16] {
        self.debuff_skill_attribute
    }
    pub fn buff_skill_ability(&self) -> &'static [i16] {
        self.buff_skill_ability
    }
    pub fn buff_skill_attribute(&self) -> &'static [i16] {
        self.buff_skill_attribute
    }
    pub fn item_icons(&self) -> &'static [i32] {
        self.item_icons
    }
    pub fn item_pages(&self) -> &'static [i32] {
        self.item_pages
    }
}

/// `itemTblR`: category 10.
pub static ITEM_R: std::sync::LazyLock<&'static [ItemParam]> = std::sync::LazyLock::new(|| shared().item_r);

/// `itemTblD`: category 11.
pub static ITEM_D: std::sync::LazyLock<&'static [ItemParam]> = std::sync::LazyLock::new(|| shared().item_d);

/// `itemTblU`: category 12.
pub static ITEM_U: std::sync::LazyLock<&'static [ItemParam]> = std::sync::LazyLock::new(|| shared().item_u);

/// `itemTblX`: category 13.
pub static ITEM_X: std::sync::LazyLock<&'static [ItemParam]> = std::sync::LazyLock::new(|| shared().item_x);

/// The 0x48 bytes before `arm`, as a row.
pub static ARM_BEFORE: std::sync::LazyLock<EquipBefore> = std::sync::LazyLock::new(|| shared().arm_before);

/// The 0x48 bytes before `weapon1`, as a row.
pub static WEAPON1_BEFORE: std::sync::LazyLock<EquipBefore> = std::sync::LazyLock::new(|| shared().weapon1_before);

/// The 0x48 bytes before `weapon6`, as a row.
pub static WEAPON6_BEFORE: std::sync::LazyLock<EquipBefore> = std::sync::LazyLock::new(|| shared().weapon6_before);

/// `expCalcTbl`, by level difference + 10.
pub static EXP_CALC: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().exp_calc);

/// `ccEntryRaceTbl`: `enemyTbl` in groups of `raceNum` rows.
pub static RACES: std::sync::LazyLock<&'static [EnemyRace]> = std::sync::LazyLock::new(|| shared().races);

/// `dataDrainErosionTbl`: a Data Drain's side effect by infection / 25.
pub static DRAIN_EROSION: std::sync::LazyLock<&'static [[i32; 16]]> =
    std::sync::LazyLock::new(|| shared().drain_erosion);

/// `ccSaveData::AddLvErosion`'s `erosionTbl`.
pub static EROSION: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().erosion);

/// `playerDefaultImportantItemList`
pub static PLAYER_DEFAULT_IMPORTANT: std::sync::LazyLock<&'static [ItemList]> =
    std::sync::LazyLock::new(|| shared().player_default_important);

/// `spcDebuffPriorityType`
pub static DEBUFF_PRIORITY: std::sync::LazyLock<&'static [[i16; 9]]> =
    std::sync::LazyLock::new(|| shared().debuff_priority);

/// `spcBuffPriorityType`
pub static BUFF_PRIORITY: std::sync::LazyLock<&'static [[i16; 5]]> =
    std::sync::LazyLock::new(|| shared().buff_priority);

/// The debuffs' ability skills.
pub static DEBUFF_SKILL_ABILITY: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().debuff_skill_ability);

/// The debuffs' attribute skills.
pub static DEBUFF_SKILL_ATTRIBUTE: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().debuff_skill_attribute);

/// The buffs' ability skills.
pub static BUFF_SKILL_ABILITY: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().buff_skill_ability);

/// The buffs' attribute skills.
pub static BUFF_SKILL_ATTRIBUTE: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().buff_skill_attribute);

/// `ccGetItemIcon(cat, id)` by category: each case of its jump table is `li $v0, icon` (or 0).
pub static ITEM_ICONS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().item_icons);

/// `SetItemList`'s page to category: -1 the usable items, -2 the equipment, else the category.
pub static ITEM_PAGES: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().item_pages);

/// The volume's Battle (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Battle {
    static READ: [std::sync::OnceLock<&'static Battle>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "battle"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Battle {
    static READ: std::sync::OnceLock<&'static Battle> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("battle"))
}
