// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/combat.bin`, plans/build-data.md).

//! What Kite's, the members' and the ride's frames read besides the battle's parameters: their clips, the following's constants, Skeith's and Innis's patterns.

pub use super::types::{EnemyBrInfo, EnemyBrParam, EnemyDustInfo, EnemyWpInfo};
use crate::volume::Volume;

/// A boss cinema's skill name: the file and texture it is in, and its row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CinemaSkillName {
    pub file: Option<&'static str>,
    pub tex: Option<&'static str>,
    pub row: i32,
}

impl crate::store::Load for CinemaSkillName {
    fn load(r: &mut crate::store::Reader) -> Self {
        CinemaSkillName {
            file: crate::store::Load::load(r),
            tex: crate::store::Load::load(r),
            row: crate::store::Load::load(r),
        }
    }
}

/// An enemy weapon block (`*WpInfo`, `ccEnemyWpInfo[]`) by name, where the volume keeps it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WpInfos {
    pub name: &'static str,
    pub va: u32,
    pub rows: &'static [EnemyWpInfo],
}

impl crate::store::Load for WpInfos {
    fn load(r: &mut crate::store::Reader) -> Self {
        WpInfos {
            name: crate::store::Load::load(r),
            va: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
        }
    }
}

/// An enemy dust block (`*DustInfo`, `ccEnemyDustInfo[]`) by name, where the volume keeps it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DustInfos {
    pub name: &'static str,
    pub va: u32,
    pub rows: &'static [EnemyDustInfo],
}

impl crate::store::Load for DustInfos {
    fn load(r: &mut crate::store::Reader) -> Self {
        DustInfos {
            name: crate::store::Load::load(r),
            va: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
        }
    }
}

/// The `combat` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Combat {
    /// `playerAnimTbl` (`char[26][21]`): Kite's clip for each act.
    pub player_anims: &'static [&'static str],
    /// `DamActuTbl`: the pad's rumble for a light, medium and heavy hit.
    pub dam_actu: &'static [i16],
    /// `tsp`: Kite's walking speed a frame.
    pub tsp: f32,
    /// `fellowAnimTbl` (one per `fellowNN.cpp`, 0x60 apart): the 22 clips of `charTbl` rows 1-17.
    pub fellow_anims: &'static [[&'static str; 22]],
    /// `fpAngleOffset[4]`.
    pub fp_angle_offset: &'static [u16],
    /// The halfword before `fpAngleOffset`, which `checkPartyMenberNum` -1 indexes.
    pub fp_angle_before: u16,
    /// `fpOkRange`: how near a member keeps.
    pub fp_ok_range: f32,
    /// `CFOFP`.
    pub cfofp: f32,
    /// `puccigusoAnimTbl`: Kite's clips on the Grunty.
    pub ride_anims: &'static [&'static str],
    /// `puccigusoAnimTblPG`: the Grunty's own.
    pub ride_anims_pg: &'static [&'static str],
    /// `puccigusoCharTbl`: the Grunty's model file by kind.
    pub ride_files: &'static [&'static str],
    /// `puccigusoAngleTbl`.
    pub ride_angles: &'static [i16],
    /// Skeith's act tables (normal, super, Epitaph): each to its -1 and the word past it.
    pub skeith_acts: &'static [&'static [i32]],
    /// `Boss01AnmTbl`: Skeith's clip by act, none for some.
    pub skeith_anims: &'static [Option<&'static str>],
    /// The skills Skeith picks from at random.
    pub skeith_rand_skills: &'static [i32],
    /// `Pattern`: Innis's action words, three runs by protect gauge, each ended by a 29.
    pub innis_pattern: &'static [i32],
    /// `EPITAPH_Pattern`: Innis's words once drained.
    pub innis_epitaph: &'static [i32],
    /// `boss02AnmTbl`: Innis's clip by act.
    pub innis_anims: &'static [Option<&'static str>],
    /// `Skill_VARIOUS_INIS`: the skills Innis picks from in its first mode.
    pub innis_various_skills: &'static [i16],
    /// `Skill_DOWNER_INIS`: the skills Innis picks from in its second.
    pub innis_downer_skills: &'static [i16],
    /// `Mon1`-`Mon3`: the clips of the three images Innis sends out, by act.
    pub innis_monster_anims: &'static [[Option<&'static str>; 15]],
    /// `EnemyBurst`'s rings' model (`particle` clump) by image.
    pub innis_ring_models: &'static [i32],
    /// `_g_cinemaSkillName`: `OnCinemaMode(n)`'s name, by `n`.
    pub cinema_skill_names: &'static [CinemaSkillName],
    /// Every `*WpInfo`: the races' weapon trail blocks, by name.
    pub weapon_infos: &'static [WpInfos],
    /// Every `*DustInfo`: the races' dust blocks, by name.
    pub dust_infos: &'static [DustInfos],
    /// `ehkBreathInfo`: `ccEnemyH`'s two fire breaths.
    pub ehk_breath_info: &'static [EnemyBrInfo],
    /// Where the volume keeps it.
    pub ehk_breath_info_va: u32,
    /// `elBrInfo`: `ccEnemyL`'s breaths.
    pub el_br_info: &'static [EnemyBrInfo],
    /// Where the volume keeps it.
    pub el_br_info_va: u32,
    /// `ehkBrParam`: the fire breath's timing and parameters.
    pub ehk_br_param: &'static [EnemyBrParam],
    /// Where the volume keeps it.
    pub ehk_br_param_va: u32,
    /// `elBrParam`: `ccEnemyL`'s.
    pub el_br_param: &'static [EnemyBrParam],
    /// Where the volume keeps it.
    pub el_br_param_va: u32,
    /// `footObjTbl` (`char[4][30]`): a turtle's feet, by foot.
    pub foot_objs: &'static [&'static str],
}

impl crate::store::Load for Combat {
    fn load(r: &mut crate::store::Reader) -> Self {
        Combat {
            player_anims: crate::store::Load::load(r),
            dam_actu: crate::store::Load::load(r),
            tsp: crate::store::Load::load(r),
            fellow_anims: crate::store::Load::load(r),
            fp_angle_offset: crate::store::Load::load(r),
            fp_angle_before: crate::store::Load::load(r),
            fp_ok_range: crate::store::Load::load(r),
            cfofp: crate::store::Load::load(r),
            ride_anims: crate::store::Load::load(r),
            ride_anims_pg: crate::store::Load::load(r),
            ride_files: crate::store::Load::load(r),
            ride_angles: crate::store::Load::load(r),
            skeith_acts: crate::store::Load::load(r),
            skeith_anims: crate::store::Load::load(r),
            skeith_rand_skills: crate::store::Load::load(r),
            innis_pattern: crate::store::Load::load(r),
            innis_epitaph: crate::store::Load::load(r),
            innis_anims: crate::store::Load::load(r),
            innis_various_skills: crate::store::Load::load(r),
            innis_downer_skills: crate::store::Load::load(r),
            innis_monster_anims: crate::store::Load::load(r),
            innis_ring_models: crate::store::Load::load(r),
            cinema_skill_names: crate::store::Load::load(r),
            weapon_infos: crate::store::Load::load(r),
            dust_infos: crate::store::Load::load(r),
            ehk_breath_info: crate::store::Load::load(r),
            ehk_breath_info_va: crate::store::Load::load(r),
            el_br_info: crate::store::Load::load(r),
            el_br_info_va: crate::store::Load::load(r),
            ehk_br_param: crate::store::Load::load(r),
            ehk_br_param_va: crate::store::Load::load(r),
            el_br_param: crate::store::Load::load(r),
            el_br_param_va: crate::store::Load::load(r),
            foot_objs: crate::store::Load::load(r),
        }
    }
}

impl Combat {
    pub fn player_anims(&self) -> &'static [&'static str] {
        self.player_anims
    }
    pub fn dam_actu(&self) -> &'static [i16] {
        self.dam_actu
    }
    pub fn tsp(&self) -> f32 {
        self.tsp
    }
    pub fn fellow_anims(&self) -> &'static [[&'static str; 22]] {
        self.fellow_anims
    }
    pub fn fp_angle_offset(&self) -> &'static [u16] {
        self.fp_angle_offset
    }
    pub fn fp_angle_before(&self) -> u16 {
        self.fp_angle_before
    }
    pub fn fp_ok_range(&self) -> f32 {
        self.fp_ok_range
    }
    pub fn cfofp(&self) -> f32 {
        self.cfofp
    }
    pub fn ride_anims(&self) -> &'static [&'static str] {
        self.ride_anims
    }
    pub fn ride_anims_pg(&self) -> &'static [&'static str] {
        self.ride_anims_pg
    }
    pub fn ride_files(&self) -> &'static [&'static str] {
        self.ride_files
    }
    pub fn ride_angles(&self) -> &'static [i16] {
        self.ride_angles
    }
    pub fn skeith_acts(&self) -> &'static [&'static [i32]] {
        self.skeith_acts
    }
    pub fn skeith_anims(&self) -> &'static [Option<&'static str>] {
        self.skeith_anims
    }
    pub fn skeith_rand_skills(&self) -> &'static [i32] {
        self.skeith_rand_skills
    }
    pub fn innis_pattern(&self) -> &'static [i32] {
        self.innis_pattern
    }
    pub fn innis_epitaph(&self) -> &'static [i32] {
        self.innis_epitaph
    }
    pub fn innis_anims(&self) -> &'static [Option<&'static str>] {
        self.innis_anims
    }
    pub fn innis_various_skills(&self) -> &'static [i16] {
        self.innis_various_skills
    }
    pub fn innis_downer_skills(&self) -> &'static [i16] {
        self.innis_downer_skills
    }
    pub fn innis_monster_anims(&self) -> &'static [[Option<&'static str>; 15]] {
        self.innis_monster_anims
    }
    pub fn innis_ring_models(&self) -> &'static [i32] {
        self.innis_ring_models
    }
    pub fn cinema_skill_names(&self) -> &'static [CinemaSkillName] {
        self.cinema_skill_names
    }
    pub fn weapon_infos(&self) -> &'static [WpInfos] {
        self.weapon_infos
    }
    pub fn dust_infos(&self) -> &'static [DustInfos] {
        self.dust_infos
    }
    pub fn ehk_breath_info(&self) -> &'static [EnemyBrInfo] {
        self.ehk_breath_info
    }
    pub fn ehk_breath_info_va(&self) -> u32 {
        self.ehk_breath_info_va
    }
    pub fn el_br_info(&self) -> &'static [EnemyBrInfo] {
        self.el_br_info
    }
    pub fn el_br_info_va(&self) -> u32 {
        self.el_br_info_va
    }
    pub fn ehk_br_param(&self) -> &'static [EnemyBrParam] {
        self.ehk_br_param
    }
    pub fn ehk_br_param_va(&self) -> u32 {
        self.ehk_br_param_va
    }
    pub fn el_br_param(&self) -> &'static [EnemyBrParam] {
        self.el_br_param
    }
    pub fn el_br_param_va(&self) -> u32 {
        self.el_br_param_va
    }
    pub fn foot_objs(&self) -> &'static [&'static str] {
        self.foot_objs
    }
}

/// `playerAnimTbl` (`char[26][21]`): Kite's clip for each act.
pub static PLAYER_ANIMS: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().player_anims);

/// `DamActuTbl`: the pad's rumble for a light, medium and heavy hit.
pub static DAM_ACTU: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().dam_actu);

/// `tsp`: Kite's walking speed a frame.
pub static TSP: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().tsp);

/// `fellowAnimTbl` (one per `fellowNN.cpp`, 0x60 apart): the 22 clips of `charTbl` rows 1-17.
pub static FELLOW_ANIMS: std::sync::LazyLock<&'static [[&'static str; 22]]> =
    std::sync::LazyLock::new(|| shared().fellow_anims);

/// `fpAngleOffset[4]`.
pub static FP_ANGLE_OFFSET: std::sync::LazyLock<&'static [u16]> = std::sync::LazyLock::new(|| shared().fp_angle_offset);

/// `fpOkRange`: how near a member keeps.
pub static FP_OK_RANGE: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().fp_ok_range);

/// `CFOFP`.
pub static CFOFP: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().cfofp);

/// `puccigusoAnimTbl`: Kite's clips on the Grunty.
pub static RIDE_ANIMS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().ride_anims);

/// `puccigusoAnimTblPG`: the Grunty's own.
pub static RIDE_ANIMS_PG: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().ride_anims_pg);

/// `puccigusoCharTbl`: the Grunty's model file by kind.
pub static RIDE_FILES: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().ride_files);

/// `puccigusoAngleTbl`.
pub static RIDE_ANGLES: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().ride_angles);

/// Skeith's act tables (normal, super, Epitaph): each to its -1 and the word past it.
pub static SKEITH_ACTS: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().skeith_acts);

/// `Boss01AnmTbl`: Skeith's clip by act, none for some.
pub static SKEITH_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().skeith_anims);

/// The skills Skeith picks from at random.
pub static SKEITH_RAND_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().skeith_rand_skills);

/// `Pattern`: Innis's action words, three runs by protect gauge, each ended by a 29.
pub static INNIS_PATTERN: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().innis_pattern);

/// `EPITAPH_Pattern`: Innis's words once drained.
pub static INNIS_EPITAPH: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().innis_epitaph);

/// `boss02AnmTbl`: Innis's clip by act.
pub static INNIS_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().innis_anims);

/// `Skill_VARIOUS_INIS`: the skills Innis picks from in its first mode.
pub static INNIS_VARIOUS_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().innis_various_skills);

/// `Skill_DOWNER_INIS`: the skills Innis picks from in its second.
pub static INNIS_DOWNER_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().innis_downer_skills);

/// `Mon1`-`Mon3`: the clips of the three images Innis sends out, by act.
pub static INNIS_MONSTER_ANIMS: std::sync::LazyLock<&'static [[Option<&'static str>; 15]]> =
    std::sync::LazyLock::new(|| shared().innis_monster_anims);

/// `EnemyBurst`'s rings' model (`particle` clump) by image.
pub static INNIS_RING_MODELS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().innis_ring_models);

/// `ehkBreathInfo`: `ccEnemyH`'s two fire breaths.
pub static EHK_BREATH_INFO: std::sync::LazyLock<&'static [EnemyBrInfo]> =
    std::sync::LazyLock::new(|| shared().ehk_breath_info);

/// `elBrInfo`: `ccEnemyL`'s breaths.
pub static EL_BR_INFO: std::sync::LazyLock<&'static [EnemyBrInfo]> = std::sync::LazyLock::new(|| shared().el_br_info);

/// `ehkBrParam`: the fire breath's timing and parameters.
pub static EHK_BR_PARAM: std::sync::LazyLock<&'static [EnemyBrParam]> =
    std::sync::LazyLock::new(|| shared().ehk_br_param);

/// `elBrParam`: `ccEnemyL`'s.
pub static EL_BR_PARAM: std::sync::LazyLock<&'static [EnemyBrParam]> =
    std::sync::LazyLock::new(|| shared().el_br_param);

/// `footObjTbl` (`char[4][30]`): a turtle's feet, by foot.
pub static FOOT_OBJS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().foot_objs);

/// The volume's Combat (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Combat {
    static READ: [std::sync::OnceLock<&'static Combat>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "combat"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Combat {
    static READ: std::sync::OnceLock<&'static Combat> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("combat"))
}
