// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/combat.bin`, plans/build-data.md).

//! What Kite's, the members' and the ride's frames read besides the battle's parameters: their clips, the following's constants, the bosses' patterns and clips.

pub use super::types::{EnemyBrInfo, EnemyBrParam, EnemyDustInfo, EnemyWpInfo};
use crate::volume::Volume;

/// A boss cinema's skill name: the file and texture it is in, and its row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CinemaSkillName {
    pub file: Option<&'static str>,
    pub tex: Option<&'static str>,
    pub row: i32,
}

impl crate::store::Load for CinemaSkillName {
    fn load(r: &mut crate::store::Reader) -> Self {
        CinemaSkillName {
            file: crate::store::Load::load(r),
            tex: crate::store::Load::load(r),
            row: crate::store::Load::load(r),
        }
    }
}

/// A boss cinema's name for a skill in a field: the file and texture it is in, and its row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CinemaSkillRow {
    pub field: i32,
    pub sid: i32,
    pub file: Option<&'static str>,
    pub tex: Option<&'static str>,
    pub row: i32,
}

impl crate::store::Load for CinemaSkillRow {
    fn load(r: &mut crate::store::Reader) -> Self {
        CinemaSkillRow {
            field: crate::store::Load::load(r),
            sid: crate::store::Load::load(r),
            file: crate::store::Load::load(r),
            tex: crate::store::Load::load(r),
            row: crate::store::Load::load(r),
        }
    }
}

/// An enemy weapon block (`*WpInfo`, `ccEnemyWpInfo[]`) by name, where the volume keeps it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WpInfos {
    pub name: &'static str,
    pub va: u32,
    pub rows: &'static [EnemyWpInfo],
}

impl crate::store::Load for WpInfos {
    fn load(r: &mut crate::store::Reader) -> Self {
        WpInfos {
            name: crate::store::Load::load(r),
            va: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
        }
    }
}

/// An enemy dust block (`*DustInfo`, `ccEnemyDustInfo[]`) by name, where the volume keeps it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DustInfos {
    pub name: &'static str,
    pub va: u32,
    pub rows: &'static [EnemyDustInfo],
}

impl crate::store::Load for DustInfos {
    fn load(r: &mut crate::store::Reader) -> Self {
        DustInfos {
            name: crate::store::Load::load(r),
            va: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
        }
    }
}

/// The `combat` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Combat {
    /// `playerAnimTbl` (`char[26][21]`): Kite's clip for each act.
    pub player_anims: &'static [&'static str],
    /// `DamActuTbl`: the pad's rumble for a light, medium and heavy hit.
    pub dam_actu: &'static [i16],
    /// `tsp`: Kite's walking speed a frame.
    pub tsp: f32,
    /// `fellowAnimTbl` (one per `fellowNN.cpp`, 0x60 apart): the 22 clips of `charTbl` rows 1-17.
    pub fellow_anims: &'static [[&'static str; 22]],
    /// `fpAngleOffset[4]`.
    pub fp_angle_offset: &'static [u16],
    /// The halfword before `fpAngleOffset`, which `checkPartyMenberNum` -1 indexes.
    pub fp_angle_before: u16,
    /// `fpOkRange`: how near a member keeps.
    pub fp_ok_range: f32,
    /// `CFOFP`.
    pub cfofp: f32,
    /// `puccigusoAnimTbl`: Kite's clips on the Grunty.
    pub ride_anims: &'static [&'static str],
    /// `puccigusoAnimTblPG`: the Grunty's own.
    pub ride_anims_pg: &'static [&'static str],
    /// `puccigusoCharTbl`: the Grunty's model file by kind.
    pub ride_files: &'static [&'static str],
    /// `puccigusoAngleTbl`.
    pub ride_angles: &'static [i16],
    /// Skeith's act tables (normal, super, Epitaph): each to its -1 and the word past it.
    pub skeith_acts: &'static [&'static [i32]],
    /// `Boss01AnmTbl`: Skeith's clip by act, none for some.
    pub skeith_anims: &'static [Option<&'static str>],
    /// The skills Skeith picks from at random.
    pub skeith_rand_skills: &'static [i32],
    /// `Pattern`: Innis's action words, three runs by protect gauge, each ended by a 29.
    pub innis_pattern: &'static [i32],
    /// `EPITAPH_Pattern`: Innis's words once drained.
    pub innis_epitaph: &'static [i32],
    /// `boss02AnmTbl`: Innis's clip by act.
    pub innis_anims: &'static [Option<&'static str>],
    /// `Skill_VARIOUS_INIS`: the skills Innis picks from in its first mode.
    pub innis_various_skills: &'static [i16],
    /// `Skill_DOWNER_INIS`: the skills Innis picks from in its second.
    pub innis_downer_skills: &'static [i16],
    /// `Mon1`-`Mon3`: the clips of the three images Innis sends out, by act.
    pub innis_monster_anims: &'static [[Option<&'static str>; 15]],
    /// `EnemyBurst`'s rings' model (`particle` clump) by image.
    pub innis_ring_models: &'static [i32],
    /// `Kyvia01AnmTbl`: Kyvia's clip by act in its first fight.
    pub kyvia01_anims: &'static [Option<&'static str>],
    /// `kyviaCoreAnmTbl`: the core's clip by act.
    pub kyvia_core_anims: &'static [Option<&'static str>],
    /// `kyviaGomoraAnmTbl`: a gomora's clip by act.
    pub kyvia_gomora_anims: &'static [Option<&'static str>],
    /// `Skill_VARIOUS`: the spells a gomora of attribute 1 picks from.
    pub kyvia_various_skills: &'static [i16],
    /// `Skill_DOWNER`: those of attribute 2.
    pub kyvia_downer_skills: &'static [i16],
    /// `AllGomoraList_1[0]`: Kyvia 01's gomora lists, each gomora's attribute (4 none) by slave.
    pub kyvia_gomora_lists: &'static [&'static [i16]],
    /// `boss03EpitaphActTbl`: Magus's patterns once drained, up to and with its -1.
    pub magus_epitaph: &'static [i32],
    /// `Boss03AnmTbl`: Magus's clip by act.
    pub magus_anims: &'static [Option<&'static str>],
    /// `Boss03SlaveAnmTbl`: a leaf's clip by act.
    pub magus_leaf_anims: &'static [Option<&'static str>],
    /// `@1538`: pattern 10's skills, one by `ccRand() % 3`.
    pub magus_skills: &'static [i32],
    /// `@2301`: the skills `OnThinkLeafDrop` casts as its sixth leaf falls.
    pub magus_drop_skills: &'static [i32],
    /// `boss04NormalActTbl`: Fidchell's patterns, up to and with its -1.
    pub fidchell_normal: &'static [i32],
    /// `boss04SuperActTbl`: Fidchell's once its gauge is half full.
    pub fidchell_super: &'static [i32],
    /// `boss04EpitaphActTbl`: Fidchell's once drained.
    pub fidchell_epitaph: &'static [i32],
    /// `boss0xAnmTbl`: Fidchell's clip by act.
    pub fidchell_anims: &'static [Option<&'static str>],
    /// `@1038`: the prediction's text clip (x41) by `m_predId`.
    pub fidchell_pred_texts: &'static [Option<&'static str>],
    /// `@1039`: the prediction's voice (`ccEvVoiceRequest(-40, n)`) by `m_predId`.
    pub fidchell_pred_voices: &'static [i32],
    /// `@1272`: pattern 10's skills (read, never used).
    pub fidchell_rand_skills: &'static [i32],
    /// `@1441`: the skill the prediction lays on each member, by `m_predId`.
    pub fidchell_pred_skills: &'static [i32],
    /// `@2048`: `OnThinkSkill`'s skills, one by `ccRand() % 3`.
    pub fidchell_skills: &'static [i32],
    /// `@2081`: `OnThinkMagic`'s spells, by `ccSys.count & 3`.
    pub fidchell_magic_skills: &'static [i32],
    /// `Boss05AnmTbl`: Gorre's clip by act.
    pub gorre_anims: &'static [Option<&'static str>],
    /// `boss05NormalActTbl`: Gorre's patterns, up to and with its -1.
    pub gorre_normal: &'static [i32],
    /// `boss05SuperActTbl`: Gorre's once its gauge is half full.
    pub gorre_super: &'static [i32],
    /// `boss05EpitaphActTbl`: Gorre's once both brothers are down.
    pub gorre_epitaph: &'static [i32],
    /// `@1261`: `OnThinkSkill`'s three spells, one by `ccRand() % 3`; the same read (and dropped) by `ExecPatternIndex`'s pattern 10.
    pub gorre_skills: &'static [i32],
    /// `@1777`: `OnThinkMagic`'s spells, one by `ccRand() % 3` (the fourth never drawn).
    pub gorre_magic_skills: &'static [i32],
    /// `_g_cinemaSkillName`: `OnCinemaMode(n)`'s name, by `n`.
    pub cinema_skill_names: &'static [CinemaSkillName],
    /// The cinema's names by `game.field` and skill (`OnCinemaMode` with a skill, from Outbreak on); none before.
    pub cinema_skill_rows: &'static [CinemaSkillRow],
    /// Every `*WpInfo`: the races' weapon trail blocks, by name.
    pub weapon_infos: &'static [WpInfos],
    /// Every `*DustInfo`: the races' dust blocks, by name.
    pub dust_infos: &'static [DustInfos],
    /// `ehkBreathInfo`: `ccEnemyH`'s two fire breaths.
    pub ehk_breath_info: &'static [EnemyBrInfo],
    /// Where the volume keeps it.
    pub ehk_breath_info_va: u32,
    /// `elBrInfo`: `ccEnemyL`'s breaths.
    pub el_br_info: &'static [EnemyBrInfo],
    /// Where the volume keeps it.
    pub el_br_info_va: u32,
    /// `ehkBrParam`: the fire breath's timing and parameters.
    pub ehk_br_param: &'static [EnemyBrParam],
    /// Where the volume keeps it.
    pub ehk_br_param_va: u32,
    /// `elBrParam`: `ccEnemyL`'s.
    pub el_br_param: &'static [EnemyBrParam],
    /// Where the volume keeps it.
    pub el_br_param_va: u32,
    /// `footObjTbl` (`char[4][30]`): a turtle's feet, by foot.
    pub foot_objs: &'static [&'static str],
}

impl crate::store::Load for Combat {
    fn load(r: &mut crate::store::Reader) -> Self {
        Combat {
            player_anims: crate::store::Load::load(r),
            dam_actu: crate::store::Load::load(r),
            tsp: crate::store::Load::load(r),
            fellow_anims: crate::store::Load::load(r),
            fp_angle_offset: crate::store::Load::load(r),
            fp_angle_before: crate::store::Load::load(r),
            fp_ok_range: crate::store::Load::load(r),
            cfofp: crate::store::Load::load(r),
            ride_anims: crate::store::Load::load(r),
            ride_anims_pg: crate::store::Load::load(r),
            ride_files: crate::store::Load::load(r),
            ride_angles: crate::store::Load::load(r),
            skeith_acts: crate::store::Load::load(r),
            skeith_anims: crate::store::Load::load(r),
            skeith_rand_skills: crate::store::Load::load(r),
            innis_pattern: crate::store::Load::load(r),
            innis_epitaph: crate::store::Load::load(r),
            innis_anims: crate::store::Load::load(r),
            innis_various_skills: crate::store::Load::load(r),
            innis_downer_skills: crate::store::Load::load(r),
            innis_monster_anims: crate::store::Load::load(r),
            innis_ring_models: crate::store::Load::load(r),
            kyvia01_anims: crate::store::Load::load(r),
            kyvia_core_anims: crate::store::Load::load(r),
            kyvia_gomora_anims: crate::store::Load::load(r),
            kyvia_various_skills: crate::store::Load::load(r),
            kyvia_downer_skills: crate::store::Load::load(r),
            kyvia_gomora_lists: crate::store::Load::load(r),
            magus_epitaph: crate::store::Load::load(r),
            magus_anims: crate::store::Load::load(r),
            magus_leaf_anims: crate::store::Load::load(r),
            magus_skills: crate::store::Load::load(r),
            magus_drop_skills: crate::store::Load::load(r),
            fidchell_normal: crate::store::Load::load(r),
            fidchell_super: crate::store::Load::load(r),
            fidchell_epitaph: crate::store::Load::load(r),
            fidchell_anims: crate::store::Load::load(r),
            fidchell_pred_texts: crate::store::Load::load(r),
            fidchell_pred_voices: crate::store::Load::load(r),
            fidchell_rand_skills: crate::store::Load::load(r),
            fidchell_pred_skills: crate::store::Load::load(r),
            fidchell_skills: crate::store::Load::load(r),
            fidchell_magic_skills: crate::store::Load::load(r),
            gorre_anims: crate::store::Load::load(r),
            gorre_normal: crate::store::Load::load(r),
            gorre_super: crate::store::Load::load(r),
            gorre_epitaph: crate::store::Load::load(r),
            gorre_skills: crate::store::Load::load(r),
            gorre_magic_skills: crate::store::Load::load(r),
            cinema_skill_names: crate::store::Load::load(r),
            cinema_skill_rows: crate::store::Load::load(r),
            weapon_infos: crate::store::Load::load(r),
            dust_infos: crate::store::Load::load(r),
            ehk_breath_info: crate::store::Load::load(r),
            ehk_breath_info_va: crate::store::Load::load(r),
            el_br_info: crate::store::Load::load(r),
            el_br_info_va: crate::store::Load::load(r),
            ehk_br_param: crate::store::Load::load(r),
            ehk_br_param_va: crate::store::Load::load(r),
            el_br_param: crate::store::Load::load(r),
            el_br_param_va: crate::store::Load::load(r),
            foot_objs: crate::store::Load::load(r),
        }
    }
}

impl Combat {
    pub fn player_anims(&self) -> &'static [&'static str] {
        self.player_anims
    }
    pub fn dam_actu(&self) -> &'static [i16] {
        self.dam_actu
    }
    pub fn tsp(&self) -> f32 {
        self.tsp
    }
    pub fn fellow_anims(&self) -> &'static [[&'static str; 22]] {
        self.fellow_anims
    }
    pub fn fp_angle_offset(&self) -> &'static [u16] {
        self.fp_angle_offset
    }
    pub fn fp_angle_before(&self) -> u16 {
        self.fp_angle_before
    }
    pub fn fp_ok_range(&self) -> f32 {
        self.fp_ok_range
    }
    pub fn cfofp(&self) -> f32 {
        self.cfofp
    }
    pub fn ride_anims(&self) -> &'static [&'static str] {
        self.ride_anims
    }
    pub fn ride_anims_pg(&self) -> &'static [&'static str] {
        self.ride_anims_pg
    }
    pub fn ride_files(&self) -> &'static [&'static str] {
        self.ride_files
    }
    pub fn ride_angles(&self) -> &'static [i16] {
        self.ride_angles
    }
    pub fn skeith_acts(&self) -> &'static [&'static [i32]] {
        self.skeith_acts
    }
    pub fn skeith_anims(&self) -> &'static [Option<&'static str>] {
        self.skeith_anims
    }
    pub fn skeith_rand_skills(&self) -> &'static [i32] {
        self.skeith_rand_skills
    }
    pub fn innis_pattern(&self) -> &'static [i32] {
        self.innis_pattern
    }
    pub fn innis_epitaph(&self) -> &'static [i32] {
        self.innis_epitaph
    }
    pub fn innis_anims(&self) -> &'static [Option<&'static str>] {
        self.innis_anims
    }
    pub fn innis_various_skills(&self) -> &'static [i16] {
        self.innis_various_skills
    }
    pub fn innis_downer_skills(&self) -> &'static [i16] {
        self.innis_downer_skills
    }
    pub fn innis_monster_anims(&self) -> &'static [[Option<&'static str>; 15]] {
        self.innis_monster_anims
    }
    pub fn innis_ring_models(&self) -> &'static [i32] {
        self.innis_ring_models
    }
    pub fn kyvia01_anims(&self) -> &'static [Option<&'static str>] {
        self.kyvia01_anims
    }
    pub fn kyvia_core_anims(&self) -> &'static [Option<&'static str>] {
        self.kyvia_core_anims
    }
    pub fn kyvia_gomora_anims(&self) -> &'static [Option<&'static str>] {
        self.kyvia_gomora_anims
    }
    pub fn kyvia_various_skills(&self) -> &'static [i16] {
        self.kyvia_various_skills
    }
    pub fn kyvia_downer_skills(&self) -> &'static [i16] {
        self.kyvia_downer_skills
    }
    pub fn kyvia_gomora_lists(&self) -> &'static [&'static [i16]] {
        self.kyvia_gomora_lists
    }
    pub fn magus_epitaph(&self) -> &'static [i32] {
        self.magus_epitaph
    }
    pub fn magus_anims(&self) -> &'static [Option<&'static str>] {
        self.magus_anims
    }
    pub fn magus_leaf_anims(&self) -> &'static [Option<&'static str>] {
        self.magus_leaf_anims
    }
    pub fn magus_skills(&self) -> &'static [i32] {
        self.magus_skills
    }
    pub fn magus_drop_skills(&self) -> &'static [i32] {
        self.magus_drop_skills
    }
    pub fn fidchell_normal(&self) -> &'static [i32] {
        self.fidchell_normal
    }
    pub fn fidchell_super(&self) -> &'static [i32] {
        self.fidchell_super
    }
    pub fn fidchell_epitaph(&self) -> &'static [i32] {
        self.fidchell_epitaph
    }
    pub fn fidchell_anims(&self) -> &'static [Option<&'static str>] {
        self.fidchell_anims
    }
    pub fn fidchell_pred_texts(&self) -> &'static [Option<&'static str>] {
        self.fidchell_pred_texts
    }
    pub fn fidchell_pred_voices(&self) -> &'static [i32] {
        self.fidchell_pred_voices
    }
    pub fn fidchell_rand_skills(&self) -> &'static [i32] {
        self.fidchell_rand_skills
    }
    pub fn fidchell_pred_skills(&self) -> &'static [i32] {
        self.fidchell_pred_skills
    }
    pub fn fidchell_skills(&self) -> &'static [i32] {
        self.fidchell_skills
    }
    pub fn fidchell_magic_skills(&self) -> &'static [i32] {
        self.fidchell_magic_skills
    }
    pub fn gorre_anims(&self) -> &'static [Option<&'static str>] {
        self.gorre_anims
    }
    pub fn gorre_normal(&self) -> &'static [i32] {
        self.gorre_normal
    }
    pub fn gorre_super(&self) -> &'static [i32] {
        self.gorre_super
    }
    pub fn gorre_epitaph(&self) -> &'static [i32] {
        self.gorre_epitaph
    }
    pub fn gorre_skills(&self) -> &'static [i32] {
        self.gorre_skills
    }
    pub fn gorre_magic_skills(&self) -> &'static [i32] {
        self.gorre_magic_skills
    }
    pub fn cinema_skill_names(&self) -> &'static [CinemaSkillName] {
        self.cinema_skill_names
    }
    pub fn cinema_skill_rows(&self) -> &'static [CinemaSkillRow] {
        self.cinema_skill_rows
    }
    pub fn weapon_infos(&self) -> &'static [WpInfos] {
        self.weapon_infos
    }
    pub fn dust_infos(&self) -> &'static [DustInfos] {
        self.dust_infos
    }
    pub fn ehk_breath_info(&self) -> &'static [EnemyBrInfo] {
        self.ehk_breath_info
    }
    pub fn ehk_breath_info_va(&self) -> u32 {
        self.ehk_breath_info_va
    }
    pub fn el_br_info(&self) -> &'static [EnemyBrInfo] {
        self.el_br_info
    }
    pub fn el_br_info_va(&self) -> u32 {
        self.el_br_info_va
    }
    pub fn ehk_br_param(&self) -> &'static [EnemyBrParam] {
        self.ehk_br_param
    }
    pub fn ehk_br_param_va(&self) -> u32 {
        self.ehk_br_param_va
    }
    pub fn el_br_param(&self) -> &'static [EnemyBrParam] {
        self.el_br_param
    }
    pub fn el_br_param_va(&self) -> u32 {
        self.el_br_param_va
    }
    pub fn foot_objs(&self) -> &'static [&'static str] {
        self.foot_objs
    }
}

/// `playerAnimTbl` (`char[26][21]`): Kite's clip for each act.
pub static PLAYER_ANIMS: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().player_anims);

/// `DamActuTbl`: the pad's rumble for a light, medium and heavy hit.
pub static DAM_ACTU: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().dam_actu);

/// `tsp`: Kite's walking speed a frame.
pub static TSP: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().tsp);

/// `fellowAnimTbl` (one per `fellowNN.cpp`, 0x60 apart): the 22 clips of `charTbl` rows 1-17.
pub static FELLOW_ANIMS: std::sync::LazyLock<&'static [[&'static str; 22]]> =
    std::sync::LazyLock::new(|| shared().fellow_anims);

/// `fpAngleOffset[4]`.
pub static FP_ANGLE_OFFSET: std::sync::LazyLock<&'static [u16]> = std::sync::LazyLock::new(|| shared().fp_angle_offset);

/// `fpOkRange`: how near a member keeps.
pub static FP_OK_RANGE: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().fp_ok_range);

/// `CFOFP`.
pub static CFOFP: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().cfofp);

/// `puccigusoAnimTbl`: Kite's clips on the Grunty.
pub static RIDE_ANIMS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().ride_anims);

/// `puccigusoAnimTblPG`: the Grunty's own.
pub static RIDE_ANIMS_PG: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().ride_anims_pg);

/// `puccigusoCharTbl`: the Grunty's model file by kind.
pub static RIDE_FILES: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().ride_files);

/// `puccigusoAngleTbl`.
pub static RIDE_ANGLES: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().ride_angles);

/// Skeith's act tables (normal, super, Epitaph): each to its -1 and the word past it.
pub static SKEITH_ACTS: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().skeith_acts);

/// `Boss01AnmTbl`: Skeith's clip by act, none for some.
pub static SKEITH_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().skeith_anims);

/// The skills Skeith picks from at random.
pub static SKEITH_RAND_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().skeith_rand_skills);

/// `Pattern`: Innis's action words, three runs by protect gauge, each ended by a 29.
pub static INNIS_PATTERN: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().innis_pattern);

/// `EPITAPH_Pattern`: Innis's words once drained.
pub static INNIS_EPITAPH: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().innis_epitaph);

/// `boss02AnmTbl`: Innis's clip by act.
pub static INNIS_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().innis_anims);

/// `Skill_VARIOUS_INIS`: the skills Innis picks from in its first mode.
pub static INNIS_VARIOUS_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().innis_various_skills);

/// `Skill_DOWNER_INIS`: the skills Innis picks from in its second.
pub static INNIS_DOWNER_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().innis_downer_skills);

/// `Mon1`-`Mon3`: the clips of the three images Innis sends out, by act.
pub static INNIS_MONSTER_ANIMS: std::sync::LazyLock<&'static [[Option<&'static str>; 15]]> =
    std::sync::LazyLock::new(|| shared().innis_monster_anims);

/// `EnemyBurst`'s rings' model (`particle` clump) by image.
pub static INNIS_RING_MODELS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().innis_ring_models);

/// `Kyvia01AnmTbl`: Kyvia's clip by act in its first fight.
pub static KYVIA01_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().kyvia01_anims);

/// `kyviaCoreAnmTbl`: the core's clip by act.
pub static KYVIA_CORE_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().kyvia_core_anims);

/// `kyviaGomoraAnmTbl`: a gomora's clip by act.
pub static KYVIA_GOMORA_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().kyvia_gomora_anims);

/// `Skill_VARIOUS`: the spells a gomora of attribute 1 picks from.
pub static KYVIA_VARIOUS_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().kyvia_various_skills);

/// `Skill_DOWNER`: those of attribute 2.
pub static KYVIA_DOWNER_SKILLS: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().kyvia_downer_skills);

/// `AllGomoraList_1[0]`: Kyvia 01's gomora lists, each gomora's attribute (4 none) by slave.
pub static KYVIA_GOMORA_LISTS: std::sync::LazyLock<&'static [&'static [i16]]> =
    std::sync::LazyLock::new(|| shared().kyvia_gomora_lists);

/// `Boss03AnmTbl`: Magus's clip by act.
pub static MAGUS_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().magus_anims);

/// `Boss03SlaveAnmTbl`: a leaf's clip by act.
pub static MAGUS_LEAF_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().magus_leaf_anims);

/// `@1538`: pattern 10's skills, one by `ccRand() % 3`.
pub static MAGUS_SKILLS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().magus_skills);

/// `@2301`: the skills `OnThinkLeafDrop` casts as its sixth leaf falls.
pub static MAGUS_DROP_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().magus_drop_skills);

/// `boss04EpitaphActTbl`: Fidchell's once drained.
pub static FIDCHELL_EPITAPH: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().fidchell_epitaph);

/// `boss0xAnmTbl`: Fidchell's clip by act.
pub static FIDCHELL_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().fidchell_anims);

/// `@1038`: the prediction's text clip (x41) by `m_predId`.
pub static FIDCHELL_PRED_TEXTS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().fidchell_pred_texts);

/// `@1039`: the prediction's voice (`ccEvVoiceRequest(-40, n)`) by `m_predId`.
pub static FIDCHELL_PRED_VOICES: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().fidchell_pred_voices);

/// `@1272`: pattern 10's skills (read, never used).
pub static FIDCHELL_RAND_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().fidchell_rand_skills);

/// `@1441`: the skill the prediction lays on each member, by `m_predId`.
pub static FIDCHELL_PRED_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().fidchell_pred_skills);

/// `@2048`: `OnThinkSkill`'s skills, one by `ccRand() % 3`.
pub static FIDCHELL_SKILLS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().fidchell_skills);

/// `@2081`: `OnThinkMagic`'s spells, by `ccSys.count & 3`.
pub static FIDCHELL_MAGIC_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().fidchell_magic_skills);

/// `Boss05AnmTbl`: Gorre's clip by act.
pub static GORRE_ANIMS: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().gorre_anims);

/// `boss05NormalActTbl`: Gorre's patterns, up to and with its -1.
pub static GORRE_NORMAL: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().gorre_normal);

/// `boss05SuperActTbl`: Gorre's once its gauge is half full.
pub static GORRE_SUPER: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().gorre_super);

/// `boss05EpitaphActTbl`: Gorre's once both brothers are down.
pub static GORRE_EPITAPH: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().gorre_epitaph);

/// `@1261`: `OnThinkSkill`'s three spells, one by `ccRand() % 3`; the same read (and dropped) by `ExecPatternIndex`'s pattern 10.
pub static GORRE_SKILLS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().gorre_skills);

/// `@1777`: `OnThinkMagic`'s spells, one by `ccRand() % 3` (the fourth never drawn).
pub static GORRE_MAGIC_SKILLS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().gorre_magic_skills);

/// `ehkBreathInfo`: `ccEnemyH`'s two fire breaths.
pub static EHK_BREATH_INFO: std::sync::LazyLock<&'static [EnemyBrInfo]> =
    std::sync::LazyLock::new(|| shared().ehk_breath_info);

/// `elBrInfo`: `ccEnemyL`'s breaths.
pub static EL_BR_INFO: std::sync::LazyLock<&'static [EnemyBrInfo]> = std::sync::LazyLock::new(|| shared().el_br_info);

/// `ehkBrParam`: the fire breath's timing and parameters.
pub static EHK_BR_PARAM: std::sync::LazyLock<&'static [EnemyBrParam]> =
    std::sync::LazyLock::new(|| shared().ehk_br_param);

/// `elBrParam`: `ccEnemyL`'s.
pub static EL_BR_PARAM: std::sync::LazyLock<&'static [EnemyBrParam]> =
    std::sync::LazyLock::new(|| shared().el_br_param);

/// `footObjTbl` (`char[4][30]`): a turtle's feet, by foot.
pub static FOOT_OBJS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().foot_objs);

/// The volume's Combat (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Combat {
    static READ: [std::sync::OnceLock<&'static Combat>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "combat"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Combat {
    static READ: std::sync::OnceLock<&'static Combat> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("combat"))
}
