// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/effect.bin`, plans/build-data.md).

//! What the effects read: the effect files and rows, the particle system's tables, the spells', the hits' and the fly font's, the boss effects' generator rows.

pub use super::types::{
    EffThunderData, EffTimeTbl, Filedata, PCcs, ParticleEffectParam, ParticleForceFieldParam, ParticleGeneratorParam,
    ParticleParam,
};
use crate::volume::Volume;

/// An `effectTbl` row (`ccEffectTbl`): the effect's file, its object and its kind.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EffectRow {
    pub ccs: Option<&'static str>,
    pub name: Option<&'static str>,
    pub kind: i32,
}

impl crate::store::Load for EffectRow {
    fn load(r: &mut crate::store::Reader) -> Self {
        EffectRow {
            ccs: crate::store::Load::load(r),
            name: crate::store::Load::load(r),
            kind: crate::store::Load::load(r),
        }
    }
}

/// `ccParticle::Setup`'s texture-id switch: from `first`, each id's (particleTbl row, CLUT flag); ids outside are their own row with no CLUT.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TexSwitch {
    pub first: i32,
    pub map: &'static [[i32; 2]],
}

impl crate::store::Load for TexSwitch {
    fn load(r: &mut crate::store::Reader) -> Self {
        TexSwitch { first: crate::store::Load::load(r), map: crate::store::Load::load(r) }
    }
}

/// The `effect` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Effect {
    /// `effectCCSTbl`: the effect files, up to the row with no name.
    pub files: &'static [Filedata],
    /// `effectTbl`.
    pub rows: &'static [EffectRow],
    /// `effectTbl2`.
    pub rows2: &'static [EffectRow],
    /// `effectStrTbl`.
    pub str_rows: &'static [EffectRow],
    /// `particleGeneratorTbl`.
    pub generators: &'static [ParticleGeneratorParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub generators_va: u32,
    /// `particleForceFieldTbl`.
    pub force_fields: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub force_fields_va: u32,
    /// `particleTbl` (101 rows), read on to 245 as `Setup` indexes it by texture id (id 237 falls through its switch): rows 101 on are the halfwords that follow.
    pub particles: &'static [ParticleParam],
    /// `particleEffectTbl`: up to four generators about a character.
    pub particle_effects: &'static [ParticleEffectParam],
    /// `particleCcsAnmTbl`: each particle object's file and name.
    pub ccs_anm: &'static [PCcs],
    /// `Polyhedron82Table`: 42 points about the origin (w 1), `Generate`'s rType 3.
    pub polyhedron: &'static [[f32; 4]],
    /// `ccpffpSmoke1`: effect.cpp's force field for its static generators.
    pub smoke_ff1: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub smoke_ff1_va: u32,
    /// `ccpffpSmoke2`.
    pub smoke_ff2: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub smoke_ff2_va: u32,
    /// `ccpffpSmoke3`.
    pub smoke_ff3: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub smoke_ff3_va: u32,
    /// `ccpffpSmoke4`.
    pub smoke_ff4: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub smoke_ff4_va: u32,
    /// `hitPhotonDummyF1`.
    pub hit_photon_ff1: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub hit_photon_ff1_va: u32,
    /// `hitPhotonDummyF2`.
    pub hit_photon_ff2: ParticleForceFieldParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub hit_photon_ff2_va: u32,
    /// `ccParticle::Setup`'s switch on a texture id, decoded from its code.
    pub tex_switch: TexSwitch,
    /// `effElementGeneratorTbl`: the element spells' generator rows.
    pub element_generators: &'static [ParticleGeneratorParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub element_generators_va: u32,
    /// `effElementFFTbl`: their force fields.
    pub element_ffs: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub element_ffs_va: u32,
    /// `panelCamDist`.
    pub panel_cam_dist: f32,
    /// `ffMissStr`.
    pub miss: &'static str,
    /// `ffstrMISS`.
    pub ff_miss: &'static str,
    /// `ffstrEXP`.
    pub ff_exp: &'static str,
    /// `ffstrLEVELDOWN`.
    pub ff_level_down: &'static str,
    /// `Int2StrFF`'s powers of ten.
    pub pow10: &'static [i32],
    /// `TornadoSystem`'s sound codes.
    pub tornado_se: &'static [i32],
    /// Ring 89's rows.
    pub ring89: &'static [[f32; 4]],
    /// Ring 90's rows.
    pub ring90: &'static [[[f32; 4]; 2]],
    /// Ring 91's rows.
    pub ring91: &'static [[[f32; 4]; 4]],
    /// Ring 90's turns.
    pub turn90: &'static [i16],
    /// Ring 91's turns.
    pub turn91: &'static [i16],
    /// `skillTornadeSmokePFF1`, by level.
    pub tornado_smoke1: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub tornado_smoke1_va: u32,
    /// `skillTornadeSmokePFF2`.
    pub tornado_smoke2: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub tornado_smoke2_va: u32,
    /// `skillTornadeSmokePFF3`.
    pub tornado_smoke3: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub tornado_smoke3_va: u32,
    /// The tornado's first start frames, by element (fire).
    pub tornade_start1: &'static [i32],
    /// The same, the second table.
    pub tornade_start1b: &'static [i32],
    /// The second start frames.
    pub tornade_start2: &'static [i32],
    /// The same, the second table.
    pub tornade_start2b: &'static [i32],
    /// The tornado's sound codes.
    pub tornade_sndcode: &'static [i32],
    /// The same, the second table.
    pub tornade_sndcodeb: &'static [i32],
    /// `skillThunderEff`.
    pub thunder_eff: EffThunderData,
    /// `skillThunderEff2`.
    pub thunder_eff2: EffThunderData,
    /// The lists `tornadeThunderTbl` points into (`ccEffTimeTbl` pairs), read on as an entry's cursor walks.
    pub thunder_times: &'static [EffTimeTbl],
    /// `tornadeThunderTbl`: where each entry's list starts, in bytes into `thunder_times`.
    pub thunder_offsets: &'static [i32],
    /// `FallSystemLevelTbl`.
    pub fall_level: &'static [i16],
    /// `fsDelay`.
    pub fall_delay: &'static [i16],
    /// The fall's element table, three a level.
    pub fall_et: &'static [i16],
    /// The fall's elements.
    pub fall_elements: &'static [i32],
    /// The fall's darkness scales.
    pub fall_dark_scale: &'static [f32],
    /// The fall's hits.
    pub fall_hits: &'static [i32],
    /// The fall's bolts.
    pub fall_bolts: &'static [i32],
    /// The fall's bolts' hits.
    pub fall_bolt_hits: &'static [i32],
    /// `ConvergenceSystem`'s radiate frames.
    pub convergence_radiate: &'static [i32],
    /// Its smoke frames.
    pub convergence_smoke: &'static [i32],
    /// Its wait frames.
    pub convergence_wait: &'static [i32],
    /// Its pieces.
    pub convergence_pieces: &'static [i32],
    /// `effIV`.
    pub convergence_iv: f32,
    /// `effSR`.
    pub convergence_sr: f32,
    /// Its elements.
    pub convergence_elements: &'static [i32],
    /// `pillarDegTbl`.
    pub pillar_deg: &'static [i16],
    /// The upheaval's hands' angles.
    pub hand_deg: &'static [i16],
    /// Its trees' angles.
    pub tree_deg: &'static [i16],
    /// Its rocks' angles.
    pub rock_deg: &'static [i16],
    /// The ice's raise frames.
    pub ice_raise: &'static [i32],
    /// The ice's hit frames.
    pub ice_hit: &'static [i32],
    /// The upheaval's rock models.
    pub upheaval_rocks: &'static [&'static str],
    /// Its tree models.
    pub upheaval_trees: &'static [&'static str],
    /// Shock wave 64's rows.
    pub summons_wave: &'static [[f32; 3]],
    /// The summoned fire's counts.
    pub summoned_fire: &'static [i32],
    /// The water's.
    pub summoned_water: &'static [i32],
    /// The thunder's rings.
    pub summoned_thunder_rings: &'static [i32],
    /// The spline's angles.
    pub summoned_spline_deg: &'static [f32],
    /// The soil's.
    pub summoned_soil: &'static [i32],
    /// The tree's rings.
    pub summoned_tree_rings: &'static [i32],
    /// The goblin's rings.
    pub summoned_goblin_rings: &'static [i32],
    /// The circle's CLUTs by element.
    pub summoned_circle_clut: &'static [&'static str],
    /// The dark star's texture.
    pub summoned_dark_star_tex: i32,
    /// The needles' models.
    pub summoned_needles: &'static [&'static str],
    /// The energy's CLUTs by element.
    pub summoned_energy_clut: &'static [&'static str],
    /// The element draw's rocks.
    pub draw_rock: &'static [&'static str],
    /// Its ice.
    pub draw_ice: &'static [&'static str],
    /// Its branches.
    pub draw_blantch: &'static [&'static str],
    /// Its substitutes.
    pub draw_subst: &'static [&'static str],
    /// Its CLUTs.
    pub draw_clut: &'static [&'static str],
    /// Its suffixes (`char[6][8]`).
    pub draw_suffix: &'static [&'static str],
    /// Its kinds.
    pub draw_kinds: &'static [i32],
    /// The skill start's execution ring.
    pub exec_ring: &'static [f32],
    /// Its force ring.
    pub force_ring: &'static [f32],
    /// Its second force ring.
    pub force_ring2: &'static [f32],
    /// Its circle.
    pub circle: &'static [f32],
    /// Its circle's fade frames.
    pub circle_fade: &'static [i32],
    /// Shock wave 80's rows.
    pub wave2: &'static [f32],
    /// Its turns.
    pub wave2_turn: &'static [i16],
    /// Shock wave 81's rows.
    pub wave3: &'static [f32],
    /// Its turns.
    pub wave3_turn: &'static [i16],
    /// The cure's rows A-D.
    pub cure_a: &'static [i32],
    /// Row B.
    pub cure_b: &'static [i32],
    /// Row C.
    pub cure_c: &'static [i32],
    /// Row D.
    pub cure_d: &'static [i32],
    /// `tableAbilityUpS1-4`.
    pub ability_up: &'static [&'static [i32]],
    /// `tableAbilityDownS1-3`.
    pub ability_down: &'static [&'static [i32]],
    /// `g_eruptionGenerator`.
    pub boss_eruption: ParticleGeneratorParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_eruption_va: u32,
    /// `g_eruptionForceField`.
    pub boss_eruption_ff: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_eruption_ff_va: u32,
    /// `MagicSquareGenerator`.
    pub boss_magic_square: &'static [ParticleGeneratorParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_magic_square_va: u32,
    /// `MagicSquareForceField`.
    pub boss_magic_square_ff: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_magic_square_ff_va: u32,
    /// `g_energyOutGenerator`.
    pub boss_energy_out: ParticleGeneratorParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_energy_out_va: u32,
    /// `g_energyOutForceField`.
    pub boss_energy_out_ff: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_energy_out_ff_va: u32,
    /// `g_IceSmokeGenerator`.
    pub boss_ice_smoke: ParticleGeneratorParam,
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_ice_smoke_va: u32,
    /// `g_IceSmokeForceField`.
    pub boss_ice_smoke_ff: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_ice_smoke_ff_va: u32,
    /// `BossDeadGenerator`.
    pub boss_dead: &'static [ParticleGeneratorParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_dead_va: u32,
    /// `BossDeadForceField`.
    pub boss_dead_ff: &'static [ParticleForceFieldParam],
    /// Where the volume keeps it: its rows' identity, as the game's pointers to them.
    pub boss_dead_ff_va: u32,
}

impl crate::store::Load for Effect {
    fn load(r: &mut crate::store::Reader) -> Self {
        Effect {
            files: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
            rows2: crate::store::Load::load(r),
            str_rows: crate::store::Load::load(r),
            generators: crate::store::Load::load(r),
            generators_va: crate::store::Load::load(r),
            force_fields: crate::store::Load::load(r),
            force_fields_va: crate::store::Load::load(r),
            particles: crate::store::Load::load(r),
            particle_effects: crate::store::Load::load(r),
            ccs_anm: crate::store::Load::load(r),
            polyhedron: crate::store::Load::load(r),
            smoke_ff1: crate::store::Load::load(r),
            smoke_ff1_va: crate::store::Load::load(r),
            smoke_ff2: crate::store::Load::load(r),
            smoke_ff2_va: crate::store::Load::load(r),
            smoke_ff3: crate::store::Load::load(r),
            smoke_ff3_va: crate::store::Load::load(r),
            smoke_ff4: crate::store::Load::load(r),
            smoke_ff4_va: crate::store::Load::load(r),
            hit_photon_ff1: crate::store::Load::load(r),
            hit_photon_ff1_va: crate::store::Load::load(r),
            hit_photon_ff2: crate::store::Load::load(r),
            hit_photon_ff2_va: crate::store::Load::load(r),
            tex_switch: crate::store::Load::load(r),
            element_generators: crate::store::Load::load(r),
            element_generators_va: crate::store::Load::load(r),
            element_ffs: crate::store::Load::load(r),
            element_ffs_va: crate::store::Load::load(r),
            panel_cam_dist: crate::store::Load::load(r),
            miss: crate::store::Load::load(r),
            ff_miss: crate::store::Load::load(r),
            ff_exp: crate::store::Load::load(r),
            ff_level_down: crate::store::Load::load(r),
            pow10: crate::store::Load::load(r),
            tornado_se: crate::store::Load::load(r),
            ring89: crate::store::Load::load(r),
            ring90: crate::store::Load::load(r),
            ring91: crate::store::Load::load(r),
            turn90: crate::store::Load::load(r),
            turn91: crate::store::Load::load(r),
            tornado_smoke1: crate::store::Load::load(r),
            tornado_smoke1_va: crate::store::Load::load(r),
            tornado_smoke2: crate::store::Load::load(r),
            tornado_smoke2_va: crate::store::Load::load(r),
            tornado_smoke3: crate::store::Load::load(r),
            tornado_smoke3_va: crate::store::Load::load(r),
            tornade_start1: crate::store::Load::load(r),
            tornade_start1b: crate::store::Load::load(r),
            tornade_start2: crate::store::Load::load(r),
            tornade_start2b: crate::store::Load::load(r),
            tornade_sndcode: crate::store::Load::load(r),
            tornade_sndcodeb: crate::store::Load::load(r),
            thunder_eff: crate::store::Load::load(r),
            thunder_eff2: crate::store::Load::load(r),
            thunder_times: crate::store::Load::load(r),
            thunder_offsets: crate::store::Load::load(r),
            fall_level: crate::store::Load::load(r),
            fall_delay: crate::store::Load::load(r),
            fall_et: crate::store::Load::load(r),
            fall_elements: crate::store::Load::load(r),
            fall_dark_scale: crate::store::Load::load(r),
            fall_hits: crate::store::Load::load(r),
            fall_bolts: crate::store::Load::load(r),
            fall_bolt_hits: crate::store::Load::load(r),
            convergence_radiate: crate::store::Load::load(r),
            convergence_smoke: crate::store::Load::load(r),
            convergence_wait: crate::store::Load::load(r),
            convergence_pieces: crate::store::Load::load(r),
            convergence_iv: crate::store::Load::load(r),
            convergence_sr: crate::store::Load::load(r),
            convergence_elements: crate::store::Load::load(r),
            pillar_deg: crate::store::Load::load(r),
            hand_deg: crate::store::Load::load(r),
            tree_deg: crate::store::Load::load(r),
            rock_deg: crate::store::Load::load(r),
            ice_raise: crate::store::Load::load(r),
            ice_hit: crate::store::Load::load(r),
            upheaval_rocks: crate::store::Load::load(r),
            upheaval_trees: crate::store::Load::load(r),
            summons_wave: crate::store::Load::load(r),
            summoned_fire: crate::store::Load::load(r),
            summoned_water: crate::store::Load::load(r),
            summoned_thunder_rings: crate::store::Load::load(r),
            summoned_spline_deg: crate::store::Load::load(r),
            summoned_soil: crate::store::Load::load(r),
            summoned_tree_rings: crate::store::Load::load(r),
            summoned_goblin_rings: crate::store::Load::load(r),
            summoned_circle_clut: crate::store::Load::load(r),
            summoned_dark_star_tex: crate::store::Load::load(r),
            summoned_needles: crate::store::Load::load(r),
            summoned_energy_clut: crate::store::Load::load(r),
            draw_rock: crate::store::Load::load(r),
            draw_ice: crate::store::Load::load(r),
            draw_blantch: crate::store::Load::load(r),
            draw_subst: crate::store::Load::load(r),
            draw_clut: crate::store::Load::load(r),
            draw_suffix: crate::store::Load::load(r),
            draw_kinds: crate::store::Load::load(r),
            exec_ring: crate::store::Load::load(r),
            force_ring: crate::store::Load::load(r),
            force_ring2: crate::store::Load::load(r),
            circle: crate::store::Load::load(r),
            circle_fade: crate::store::Load::load(r),
            wave2: crate::store::Load::load(r),
            wave2_turn: crate::store::Load::load(r),
            wave3: crate::store::Load::load(r),
            wave3_turn: crate::store::Load::load(r),
            cure_a: crate::store::Load::load(r),
            cure_b: crate::store::Load::load(r),
            cure_c: crate::store::Load::load(r),
            cure_d: crate::store::Load::load(r),
            ability_up: crate::store::Load::load(r),
            ability_down: crate::store::Load::load(r),
            boss_eruption: crate::store::Load::load(r),
            boss_eruption_va: crate::store::Load::load(r),
            boss_eruption_ff: crate::store::Load::load(r),
            boss_eruption_ff_va: crate::store::Load::load(r),
            boss_magic_square: crate::store::Load::load(r),
            boss_magic_square_va: crate::store::Load::load(r),
            boss_magic_square_ff: crate::store::Load::load(r),
            boss_magic_square_ff_va: crate::store::Load::load(r),
            boss_energy_out: crate::store::Load::load(r),
            boss_energy_out_va: crate::store::Load::load(r),
            boss_energy_out_ff: crate::store::Load::load(r),
            boss_energy_out_ff_va: crate::store::Load::load(r),
            boss_ice_smoke: crate::store::Load::load(r),
            boss_ice_smoke_va: crate::store::Load::load(r),
            boss_ice_smoke_ff: crate::store::Load::load(r),
            boss_ice_smoke_ff_va: crate::store::Load::load(r),
            boss_dead: crate::store::Load::load(r),
            boss_dead_va: crate::store::Load::load(r),
            boss_dead_ff: crate::store::Load::load(r),
            boss_dead_ff_va: crate::store::Load::load(r),
        }
    }
}

impl Effect {
    pub fn files(&self) -> &'static [Filedata] {
        self.files
    }
    pub fn rows(&self) -> &'static [EffectRow] {
        self.rows
    }
    pub fn rows2(&self) -> &'static [EffectRow] {
        self.rows2
    }
    pub fn str_rows(&self) -> &'static [EffectRow] {
        self.str_rows
    }
    pub fn generators(&self) -> &'static [ParticleGeneratorParam] {
        self.generators
    }
    pub fn generators_va(&self) -> u32 {
        self.generators_va
    }
    pub fn force_fields(&self) -> &'static [ParticleForceFieldParam] {
        self.force_fields
    }
    pub fn force_fields_va(&self) -> u32 {
        self.force_fields_va
    }
    pub fn particles(&self) -> &'static [ParticleParam] {
        self.particles
    }
    pub fn particle_effects(&self) -> &'static [ParticleEffectParam] {
        self.particle_effects
    }
    pub fn ccs_anm(&self) -> &'static [PCcs] {
        self.ccs_anm
    }
    pub fn polyhedron(&self) -> &'static [[f32; 4]] {
        self.polyhedron
    }
    pub fn smoke_ff1(&self) -> ParticleForceFieldParam {
        self.smoke_ff1
    }
    pub fn smoke_ff1_va(&self) -> u32 {
        self.smoke_ff1_va
    }
    pub fn smoke_ff2(&self) -> ParticleForceFieldParam {
        self.smoke_ff2
    }
    pub fn smoke_ff2_va(&self) -> u32 {
        self.smoke_ff2_va
    }
    pub fn smoke_ff3(&self) -> ParticleForceFieldParam {
        self.smoke_ff3
    }
    pub fn smoke_ff3_va(&self) -> u32 {
        self.smoke_ff3_va
    }
    pub fn smoke_ff4(&self) -> ParticleForceFieldParam {
        self.smoke_ff4
    }
    pub fn smoke_ff4_va(&self) -> u32 {
        self.smoke_ff4_va
    }
    pub fn hit_photon_ff1(&self) -> ParticleForceFieldParam {
        self.hit_photon_ff1
    }
    pub fn hit_photon_ff1_va(&self) -> u32 {
        self.hit_photon_ff1_va
    }
    pub fn hit_photon_ff2(&self) -> ParticleForceFieldParam {
        self.hit_photon_ff2
    }
    pub fn hit_photon_ff2_va(&self) -> u32 {
        self.hit_photon_ff2_va
    }
    pub fn tex_switch(&self) -> TexSwitch {
        self.tex_switch
    }
    pub fn element_generators(&self) -> &'static [ParticleGeneratorParam] {
        self.element_generators
    }
    pub fn element_generators_va(&self) -> u32 {
        self.element_generators_va
    }
    pub fn element_ffs(&self) -> &'static [ParticleForceFieldParam] {
        self.element_ffs
    }
    pub fn element_ffs_va(&self) -> u32 {
        self.element_ffs_va
    }
    pub fn panel_cam_dist(&self) -> f32 {
        self.panel_cam_dist
    }
    pub fn miss(&self) -> &'static str {
        self.miss
    }
    pub fn ff_miss(&self) -> &'static str {
        self.ff_miss
    }
    pub fn ff_exp(&self) -> &'static str {
        self.ff_exp
    }
    pub fn ff_level_down(&self) -> &'static str {
        self.ff_level_down
    }
    pub fn pow10(&self) -> &'static [i32] {
        self.pow10
    }
    pub fn tornado_se(&self) -> &'static [i32] {
        self.tornado_se
    }
    pub fn ring89(&self) -> &'static [[f32; 4]] {
        self.ring89
    }
    pub fn ring90(&self) -> &'static [[[f32; 4]; 2]] {
        self.ring90
    }
    pub fn ring91(&self) -> &'static [[[f32; 4]; 4]] {
        self.ring91
    }
    pub fn turn90(&self) -> &'static [i16] {
        self.turn90
    }
    pub fn turn91(&self) -> &'static [i16] {
        self.turn91
    }
    pub fn tornado_smoke1(&self) -> &'static [ParticleForceFieldParam] {
        self.tornado_smoke1
    }
    pub fn tornado_smoke1_va(&self) -> u32 {
        self.tornado_smoke1_va
    }
    pub fn tornado_smoke2(&self) -> &'static [ParticleForceFieldParam] {
        self.tornado_smoke2
    }
    pub fn tornado_smoke2_va(&self) -> u32 {
        self.tornado_smoke2_va
    }
    pub fn tornado_smoke3(&self) -> &'static [ParticleForceFieldParam] {
        self.tornado_smoke3
    }
    pub fn tornado_smoke3_va(&self) -> u32 {
        self.tornado_smoke3_va
    }
    pub fn tornade_start1(&self) -> &'static [i32] {
        self.tornade_start1
    }
    pub fn tornade_start1b(&self) -> &'static [i32] {
        self.tornade_start1b
    }
    pub fn tornade_start2(&self) -> &'static [i32] {
        self.tornade_start2
    }
    pub fn tornade_start2b(&self) -> &'static [i32] {
        self.tornade_start2b
    }
    pub fn tornade_sndcode(&self) -> &'static [i32] {
        self.tornade_sndcode
    }
    pub fn tornade_sndcodeb(&self) -> &'static [i32] {
        self.tornade_sndcodeb
    }
    pub fn thunder_eff(&self) -> EffThunderData {
        self.thunder_eff
    }
    pub fn thunder_eff2(&self) -> EffThunderData {
        self.thunder_eff2
    }
    pub fn thunder_times(&self) -> &'static [EffTimeTbl] {
        self.thunder_times
    }
    pub fn thunder_offsets(&self) -> &'static [i32] {
        self.thunder_offsets
    }
    pub fn fall_level(&self) -> &'static [i16] {
        self.fall_level
    }
    pub fn fall_delay(&self) -> &'static [i16] {
        self.fall_delay
    }
    pub fn fall_et(&self) -> &'static [i16] {
        self.fall_et
    }
    pub fn fall_elements(&self) -> &'static [i32] {
        self.fall_elements
    }
    pub fn fall_dark_scale(&self) -> &'static [f32] {
        self.fall_dark_scale
    }
    pub fn fall_hits(&self) -> &'static [i32] {
        self.fall_hits
    }
    pub fn fall_bolts(&self) -> &'static [i32] {
        self.fall_bolts
    }
    pub fn fall_bolt_hits(&self) -> &'static [i32] {
        self.fall_bolt_hits
    }
    pub fn convergence_radiate(&self) -> &'static [i32] {
        self.convergence_radiate
    }
    pub fn convergence_smoke(&self) -> &'static [i32] {
        self.convergence_smoke
    }
    pub fn convergence_wait(&self) -> &'static [i32] {
        self.convergence_wait
    }
    pub fn convergence_pieces(&self) -> &'static [i32] {
        self.convergence_pieces
    }
    pub fn convergence_iv(&self) -> f32 {
        self.convergence_iv
    }
    pub fn convergence_sr(&self) -> f32 {
        self.convergence_sr
    }
    pub fn convergence_elements(&self) -> &'static [i32] {
        self.convergence_elements
    }
    pub fn pillar_deg(&self) -> &'static [i16] {
        self.pillar_deg
    }
    pub fn hand_deg(&self) -> &'static [i16] {
        self.hand_deg
    }
    pub fn tree_deg(&self) -> &'static [i16] {
        self.tree_deg
    }
    pub fn rock_deg(&self) -> &'static [i16] {
        self.rock_deg
    }
    pub fn ice_raise(&self) -> &'static [i32] {
        self.ice_raise
    }
    pub fn ice_hit(&self) -> &'static [i32] {
        self.ice_hit
    }
    pub fn upheaval_rocks(&self) -> &'static [&'static str] {
        self.upheaval_rocks
    }
    pub fn upheaval_trees(&self) -> &'static [&'static str] {
        self.upheaval_trees
    }
    pub fn summons_wave(&self) -> &'static [[f32; 3]] {
        self.summons_wave
    }
    pub fn summoned_fire(&self) -> &'static [i32] {
        self.summoned_fire
    }
    pub fn summoned_water(&self) -> &'static [i32] {
        self.summoned_water
    }
    pub fn summoned_thunder_rings(&self) -> &'static [i32] {
        self.summoned_thunder_rings
    }
    pub fn summoned_spline_deg(&self) -> &'static [f32] {
        self.summoned_spline_deg
    }
    pub fn summoned_soil(&self) -> &'static [i32] {
        self.summoned_soil
    }
    pub fn summoned_tree_rings(&self) -> &'static [i32] {
        self.summoned_tree_rings
    }
    pub fn summoned_goblin_rings(&self) -> &'static [i32] {
        self.summoned_goblin_rings
    }
    pub fn summoned_circle_clut(&self) -> &'static [&'static str] {
        self.summoned_circle_clut
    }
    pub fn summoned_dark_star_tex(&self) -> i32 {
        self.summoned_dark_star_tex
    }
    pub fn summoned_needles(&self) -> &'static [&'static str] {
        self.summoned_needles
    }
    pub fn summoned_energy_clut(&self) -> &'static [&'static str] {
        self.summoned_energy_clut
    }
    pub fn draw_rock(&self) -> &'static [&'static str] {
        self.draw_rock
    }
    pub fn draw_ice(&self) -> &'static [&'static str] {
        self.draw_ice
    }
    pub fn draw_blantch(&self) -> &'static [&'static str] {
        self.draw_blantch
    }
    pub fn draw_subst(&self) -> &'static [&'static str] {
        self.draw_subst
    }
    pub fn draw_clut(&self) -> &'static [&'static str] {
        self.draw_clut
    }
    pub fn draw_suffix(&self) -> &'static [&'static str] {
        self.draw_suffix
    }
    pub fn draw_kinds(&self) -> &'static [i32] {
        self.draw_kinds
    }
    pub fn exec_ring(&self) -> &'static [f32] {
        self.exec_ring
    }
    pub fn force_ring(&self) -> &'static [f32] {
        self.force_ring
    }
    pub fn force_ring2(&self) -> &'static [f32] {
        self.force_ring2
    }
    pub fn circle(&self) -> &'static [f32] {
        self.circle
    }
    pub fn circle_fade(&self) -> &'static [i32] {
        self.circle_fade
    }
    pub fn wave2(&self) -> &'static [f32] {
        self.wave2
    }
    pub fn wave2_turn(&self) -> &'static [i16] {
        self.wave2_turn
    }
    pub fn wave3(&self) -> &'static [f32] {
        self.wave3
    }
    pub fn wave3_turn(&self) -> &'static [i16] {
        self.wave3_turn
    }
    pub fn cure_a(&self) -> &'static [i32] {
        self.cure_a
    }
    pub fn cure_b(&self) -> &'static [i32] {
        self.cure_b
    }
    pub fn cure_c(&self) -> &'static [i32] {
        self.cure_c
    }
    pub fn cure_d(&self) -> &'static [i32] {
        self.cure_d
    }
    pub fn ability_up(&self) -> &'static [&'static [i32]] {
        self.ability_up
    }
    pub fn ability_down(&self) -> &'static [&'static [i32]] {
        self.ability_down
    }
    pub fn boss_eruption(&self) -> ParticleGeneratorParam {
        self.boss_eruption
    }
    pub fn boss_eruption_va(&self) -> u32 {
        self.boss_eruption_va
    }
    pub fn boss_eruption_ff(&self) -> &'static [ParticleForceFieldParam] {
        self.boss_eruption_ff
    }
    pub fn boss_eruption_ff_va(&self) -> u32 {
        self.boss_eruption_ff_va
    }
    pub fn boss_magic_square(&self) -> &'static [ParticleGeneratorParam] {
        self.boss_magic_square
    }
    pub fn boss_magic_square_va(&self) -> u32 {
        self.boss_magic_square_va
    }
    pub fn boss_magic_square_ff(&self) -> &'static [ParticleForceFieldParam] {
        self.boss_magic_square_ff
    }
    pub fn boss_magic_square_ff_va(&self) -> u32 {
        self.boss_magic_square_ff_va
    }
    pub fn boss_energy_out(&self) -> ParticleGeneratorParam {
        self.boss_energy_out
    }
    pub fn boss_energy_out_va(&self) -> u32 {
        self.boss_energy_out_va
    }
    pub fn boss_energy_out_ff(&self) -> &'static [ParticleForceFieldParam] {
        self.boss_energy_out_ff
    }
    pub fn boss_energy_out_ff_va(&self) -> u32 {
        self.boss_energy_out_ff_va
    }
    pub fn boss_ice_smoke(&self) -> ParticleGeneratorParam {
        self.boss_ice_smoke
    }
    pub fn boss_ice_smoke_va(&self) -> u32 {
        self.boss_ice_smoke_va
    }
    pub fn boss_ice_smoke_ff(&self) -> &'static [ParticleForceFieldParam] {
        self.boss_ice_smoke_ff
    }
    pub fn boss_ice_smoke_ff_va(&self) -> u32 {
        self.boss_ice_smoke_ff_va
    }
    pub fn boss_dead(&self) -> &'static [ParticleGeneratorParam] {
        self.boss_dead
    }
    pub fn boss_dead_va(&self) -> u32 {
        self.boss_dead_va
    }
    pub fn boss_dead_ff(&self) -> &'static [ParticleForceFieldParam] {
        self.boss_dead_ff
    }
    pub fn boss_dead_ff_va(&self) -> u32 {
        self.boss_dead_ff_va
    }
}

/// `effectCCSTbl`: the effect files, up to the row with no name.
pub static FILES: std::sync::LazyLock<&'static [Filedata]> = std::sync::LazyLock::new(|| shared().files);

/// `effectTbl`.
pub static ROWS: std::sync::LazyLock<&'static [EffectRow]> = std::sync::LazyLock::new(|| shared().rows);

/// `effectTbl2`.
pub static ROWS2: std::sync::LazyLock<&'static [EffectRow]> = std::sync::LazyLock::new(|| shared().rows2);

/// `effectStrTbl`.
pub static STR_ROWS: std::sync::LazyLock<&'static [EffectRow]> = std::sync::LazyLock::new(|| shared().str_rows);

/// `particleGeneratorTbl`.
pub static GENERATORS: std::sync::LazyLock<&'static [ParticleGeneratorParam]> =
    std::sync::LazyLock::new(|| shared().generators);

/// `particleForceFieldTbl`.
pub static FORCE_FIELDS: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().force_fields);

/// `particleTbl` (101 rows), read on to 245 as `Setup` indexes it by texture id (id 237 falls through its switch): rows 101 on are the halfwords that follow.
pub static PARTICLES: std::sync::LazyLock<&'static [ParticleParam]> = std::sync::LazyLock::new(|| shared().particles);

/// `particleEffectTbl`: up to four generators about a character.
pub static PARTICLE_EFFECTS: std::sync::LazyLock<&'static [ParticleEffectParam]> =
    std::sync::LazyLock::new(|| shared().particle_effects);

/// `particleCcsAnmTbl`: each particle object's file and name.
pub static CCS_ANM: std::sync::LazyLock<&'static [PCcs]> = std::sync::LazyLock::new(|| shared().ccs_anm);

/// `Polyhedron82Table`: 42 points about the origin (w 1), `Generate`'s rType 3.
pub static POLYHEDRON: std::sync::LazyLock<&'static [[f32; 4]]> = std::sync::LazyLock::new(|| shared().polyhedron);

/// `ccpffpSmoke1`: effect.cpp's force field for its static generators.
pub static SMOKE_FF1: std::sync::LazyLock<ParticleForceFieldParam> = std::sync::LazyLock::new(|| shared().smoke_ff1);

/// `ccpffpSmoke2`.
pub static SMOKE_FF2: std::sync::LazyLock<ParticleForceFieldParam> = std::sync::LazyLock::new(|| shared().smoke_ff2);

/// `ccpffpSmoke3`.
pub static SMOKE_FF3: std::sync::LazyLock<ParticleForceFieldParam> = std::sync::LazyLock::new(|| shared().smoke_ff3);

/// `ccpffpSmoke4`.
pub static SMOKE_FF4: std::sync::LazyLock<ParticleForceFieldParam> = std::sync::LazyLock::new(|| shared().smoke_ff4);

/// `hitPhotonDummyF1`.
pub static HIT_PHOTON_FF1: std::sync::LazyLock<ParticleForceFieldParam> =
    std::sync::LazyLock::new(|| shared().hit_photon_ff1);

/// `hitPhotonDummyF2`.
pub static HIT_PHOTON_FF2: std::sync::LazyLock<ParticleForceFieldParam> =
    std::sync::LazyLock::new(|| shared().hit_photon_ff2);

/// `ccParticle::Setup`'s switch on a texture id, decoded from its code.
pub static TEX_SWITCH: std::sync::LazyLock<TexSwitch> = std::sync::LazyLock::new(|| shared().tex_switch);

/// `effElementGeneratorTbl`: the element spells' generator rows.
pub static ELEMENT_GENERATORS: std::sync::LazyLock<&'static [ParticleGeneratorParam]> =
    std::sync::LazyLock::new(|| shared().element_generators);

/// `effElementFFTbl`: their force fields.
pub static ELEMENT_FFS: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().element_ffs);

/// `panelCamDist`.
pub static PANEL_CAM_DIST: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().panel_cam_dist);

/// `ffMissStr`.
pub static MISS: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().miss);

/// `ffstrMISS`.
pub static FF_MISS: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().ff_miss);

/// `ffstrEXP`.
pub static FF_EXP: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().ff_exp);

/// `ffstrLEVELDOWN`.
pub static FF_LEVEL_DOWN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().ff_level_down);

/// `Int2StrFF`'s powers of ten.
pub static POW10: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().pow10);

/// `TornadoSystem`'s sound codes.
pub static TORNADO_SE: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornado_se);

/// Ring 89's rows.
pub static RING89: std::sync::LazyLock<&'static [[f32; 4]]> = std::sync::LazyLock::new(|| shared().ring89);

/// Ring 90's rows.
pub static RING90: std::sync::LazyLock<&'static [[[f32; 4]; 2]]> = std::sync::LazyLock::new(|| shared().ring90);

/// Ring 91's rows.
pub static RING91: std::sync::LazyLock<&'static [[[f32; 4]; 4]]> = std::sync::LazyLock::new(|| shared().ring91);

/// Ring 90's turns.
pub static TURN90: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().turn90);

/// Ring 91's turns.
pub static TURN91: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().turn91);

/// `skillTornadeSmokePFF1`, by level.
pub static TORNADO_SMOKE1: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().tornado_smoke1);

/// `skillTornadeSmokePFF2`.
pub static TORNADO_SMOKE2: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().tornado_smoke2);

/// `skillTornadeSmokePFF3`.
pub static TORNADO_SMOKE3: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().tornado_smoke3);

/// The tornado's first start frames, by element (fire).
pub static TORNADE_START1: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornade_start1);

/// The same, the second table.
pub static TORNADE_START1B: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornade_start1b);

/// The second start frames.
pub static TORNADE_START2: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornade_start2);

/// The same, the second table.
pub static TORNADE_START2B: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornade_start2b);

/// The tornado's sound codes.
pub static TORNADE_SNDCODE: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().tornade_sndcode);

/// The same, the second table.
pub static TORNADE_SNDCODEB: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().tornade_sndcodeb);

/// `skillThunderEff`.
pub static THUNDER_EFF: std::sync::LazyLock<EffThunderData> = std::sync::LazyLock::new(|| shared().thunder_eff);

/// `skillThunderEff2`.
pub static THUNDER_EFF2: std::sync::LazyLock<EffThunderData> = std::sync::LazyLock::new(|| shared().thunder_eff2);

/// `tornadeThunderTbl`: where each entry's list starts, in bytes into `thunder_times`.
pub static THUNDER_OFFSETS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().thunder_offsets);

/// `FallSystemLevelTbl`.
pub static FALL_LEVEL: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().fall_level);

/// `fsDelay`.
pub static FALL_DELAY: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().fall_delay);

/// The fall's element table, three a level.
pub static FALL_ET: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().fall_et);

/// The fall's elements.
pub static FALL_ELEMENTS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().fall_elements);

/// The fall's darkness scales.
pub static FALL_DARK_SCALE: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().fall_dark_scale);

/// The fall's hits.
pub static FALL_HITS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().fall_hits);

/// The fall's bolts.
pub static FALL_BOLTS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().fall_bolts);

/// The fall's bolts' hits.
pub static FALL_BOLT_HITS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().fall_bolt_hits);

/// `ConvergenceSystem`'s radiate frames.
pub static CONVERGENCE_RADIATE: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().convergence_radiate);

/// Its smoke frames.
pub static CONVERGENCE_SMOKE: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().convergence_smoke);

/// Its wait frames.
pub static CONVERGENCE_WAIT: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().convergence_wait);

/// Its pieces.
pub static CONVERGENCE_PIECES: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().convergence_pieces);

/// `effIV`.
pub static CONVERGENCE_IV: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().convergence_iv);

/// `effSR`.
pub static CONVERGENCE_SR: std::sync::LazyLock<f32> = std::sync::LazyLock::new(|| shared().convergence_sr);

/// Its elements.
pub static CONVERGENCE_ELEMENTS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().convergence_elements);

/// `pillarDegTbl`.
pub static PILLAR_DEG: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().pillar_deg);

/// The upheaval's hands' angles.
pub static HAND_DEG: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().hand_deg);

/// Its trees' angles.
pub static TREE_DEG: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().tree_deg);

/// Its rocks' angles.
pub static ROCK_DEG: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().rock_deg);

/// The ice's raise frames.
pub static ICE_RAISE: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().ice_raise);

/// The ice's hit frames.
pub static ICE_HIT: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().ice_hit);

/// The upheaval's rock models.
pub static UPHEAVAL_ROCKS: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().upheaval_rocks);

/// Its tree models.
pub static UPHEAVAL_TREES: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().upheaval_trees);

/// Shock wave 64's rows.
pub static SUMMONS_WAVE: std::sync::LazyLock<&'static [[f32; 3]]> = std::sync::LazyLock::new(|| shared().summons_wave);

/// The summoned fire's counts.
pub static SUMMONED_FIRE: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().summoned_fire);

/// The water's.
pub static SUMMONED_WATER: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().summoned_water);

/// The thunder's rings.
pub static SUMMONED_THUNDER_RINGS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().summoned_thunder_rings);

/// The spline's angles.
pub static SUMMONED_SPLINE_DEG: std::sync::LazyLock<&'static [f32]> =
    std::sync::LazyLock::new(|| shared().summoned_spline_deg);

/// The soil's.
pub static SUMMONED_SOIL: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().summoned_soil);

/// The tree's rings.
pub static SUMMONED_TREE_RINGS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().summoned_tree_rings);

/// The goblin's rings.
pub static SUMMONED_GOBLIN_RINGS: std::sync::LazyLock<&'static [i32]> =
    std::sync::LazyLock::new(|| shared().summoned_goblin_rings);

/// The circle's CLUTs by element.
pub static SUMMONED_CIRCLE_CLUT: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().summoned_circle_clut);

/// The dark star's texture.
pub static SUMMONED_DARK_STAR_TEX: std::sync::LazyLock<i32> =
    std::sync::LazyLock::new(|| shared().summoned_dark_star_tex);

/// The needles' models.
pub static SUMMONED_NEEDLES: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().summoned_needles);

/// The energy's CLUTs by element.
pub static SUMMONED_ENERGY_CLUT: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().summoned_energy_clut);

/// The element draw's rocks.
pub static DRAW_ROCK: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().draw_rock);

/// Its ice.
pub static DRAW_ICE: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().draw_ice);

/// Its branches.
pub static DRAW_BLANTCH: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().draw_blantch);

/// Its substitutes.
pub static DRAW_SUBST: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().draw_subst);

/// Its CLUTs.
pub static DRAW_CLUT: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().draw_clut);

/// Its suffixes (`char[6][8]`).
pub static DRAW_SUFFIX: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().draw_suffix);

/// Its kinds.
pub static DRAW_KINDS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().draw_kinds);

/// The skill start's execution ring.
pub static EXEC_RING: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().exec_ring);

/// Its force ring.
pub static FORCE_RING: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().force_ring);

/// Its second force ring.
pub static FORCE_RING2: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().force_ring2);

/// Its circle.
pub static CIRCLE: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().circle);

/// Its circle's fade frames.
pub static CIRCLE_FADE: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().circle_fade);

/// Shock wave 80's rows.
pub static WAVE2: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().wave2);

/// Its turns.
pub static WAVE2_TURN: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().wave2_turn);

/// Shock wave 81's rows.
pub static WAVE3: std::sync::LazyLock<&'static [f32]> = std::sync::LazyLock::new(|| shared().wave3);

/// Its turns.
pub static WAVE3_TURN: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().wave3_turn);

/// The cure's rows A-D.
pub static CURE_A: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().cure_a);

/// Row B.
pub static CURE_B: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().cure_b);

/// Row C.
pub static CURE_C: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().cure_c);

/// Row D.
pub static CURE_D: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().cure_d);

/// `tableAbilityUpS1-4`.
pub static ABILITY_UP: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().ability_up);

/// `tableAbilityDownS1-3`.
pub static ABILITY_DOWN: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().ability_down);

/// `g_eruptionGenerator`.
pub static BOSS_ERUPTION: std::sync::LazyLock<ParticleGeneratorParam> =
    std::sync::LazyLock::new(|| shared().boss_eruption);

/// `g_eruptionForceField`.
pub static BOSS_ERUPTION_FF: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().boss_eruption_ff);

/// `MagicSquareGenerator`.
pub static BOSS_MAGIC_SQUARE: std::sync::LazyLock<&'static [ParticleGeneratorParam]> =
    std::sync::LazyLock::new(|| shared().boss_magic_square);

/// `MagicSquareForceField`.
pub static BOSS_MAGIC_SQUARE_FF: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().boss_magic_square_ff);

/// `g_energyOutGenerator`.
pub static BOSS_ENERGY_OUT: std::sync::LazyLock<ParticleGeneratorParam> =
    std::sync::LazyLock::new(|| shared().boss_energy_out);

/// `g_energyOutForceField`.
pub static BOSS_ENERGY_OUT_FF: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().boss_energy_out_ff);

/// `g_IceSmokeGenerator`.
pub static BOSS_ICE_SMOKE: std::sync::LazyLock<ParticleGeneratorParam> =
    std::sync::LazyLock::new(|| shared().boss_ice_smoke);

/// `g_IceSmokeForceField`.
pub static BOSS_ICE_SMOKE_FF: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().boss_ice_smoke_ff);

/// `BossDeadGenerator`.
pub static BOSS_DEAD: std::sync::LazyLock<&'static [ParticleGeneratorParam]> =
    std::sync::LazyLock::new(|| shared().boss_dead);

/// `BossDeadForceField`.
pub static BOSS_DEAD_FF: std::sync::LazyLock<&'static [ParticleForceFieldParam]> =
    std::sync::LazyLock::new(|| shared().boss_dead_ff);

/// The volume's Effect (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Effect {
    static READ: [std::sync::OnceLock<&'static Effect>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "effect"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Effect {
    static READ: std::sync::OnceLock<&'static Effect> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("effect"))
}
