// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/fieldui.bin`, plans/build-data.md).

//! The field's menus (`ccMenuCtrl`, gcmn with main's texts): lists, help, the windows' words, the item lists.

pub use super::types::{EvMsgData, FoodParam, ItemList};
use crate::volume::Volume;

/// A field menu list's data: how it shows, its width in cells and its items.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldMenuData {
    pub disp: i16,
    pub width: i16,
    pub items: &'static [i16],
}

impl crate::store::Load for FieldMenuData {
    fn load(r: &mut crate::store::Reader) -> Self {
        FieldMenuData {
            disp: crate::store::Load::load(r),
            width: crate::store::Load::load(r),
            items: crate::store::Load::load(r),
        }
    }
}

/// A `menuElementData` row: the list's name, title and data.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldMenuElement {
    pub name: Option<&'static str>,
    pub title: Option<&'static str>,
    pub data: Option<FieldMenuData>,
}

impl crate::store::Load for FieldMenuElement {
    fn load(r: &mut crate::store::Reader) -> Self {
        FieldMenuElement {
            name: crate::store::Load::load(r),
            title: crate::store::Load::load(r),
            data: crate::store::Load::load(r),
        }
    }
}

/// The Flag Race's texts: each its pieces (`ccKanjiStrSeparate`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaceStr {
    pub cost: &'static [&'static str],
    pub retry: &'static [&'static str],
    pub no_money: &'static [&'static str],
    pub select: &'static [&'static str],
    pub start: &'static [&'static str],
    pub paused: &'static [&'static str],
    pub quit: &'static [&'static str],
    pub record: &'static [&'static str],
    pub rankings: &'static [&'static str],
    pub colon: &'static [&'static str],
    pub specs: &'static [&'static str],
    pub stars: &'static [&'static str],
}

impl crate::store::Load for RaceStr {
    fn load(r: &mut crate::store::Reader) -> Self {
        RaceStr {
            cost: crate::store::Load::load(r),
            retry: crate::store::Load::load(r),
            no_money: crate::store::Load::load(r),
            select: crate::store::Load::load(r),
            start: crate::store::Load::load(r),
            paused: crate::store::Load::load(r),
            quit: crate::store::Load::load(r),
            record: crate::store::Load::load(r),
            rankings: crate::store::Load::load(r),
            colon: crate::store::Load::load(r),
            specs: crate::store::Load::load(r),
            stars: crate::store::Load::load(r),
        }
    }
}

/// A face: its scene file and texture.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MenuFace {
    pub file: Option<&'static str>,
    pub texture: Option<&'static str>,
}

impl crate::store::Load for MenuFace {
    fn load(r: &mut crate::store::Reader) -> Self {
        MenuFace { file: crate::store::Load::load(r), texture: crate::store::Load::load(r) }
    }
}

/// The gate's refusal: while `saveData.eventStatus[status]` is set, a warp to one of these story areas (`GetEventAreaNumber`) shows `msg` and closes the gate instead.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct GateRefusal {
    pub status: i32,
    pub areas: &'static [i32],
    pub msg: EvMsgData,
}

impl crate::store::Load for GateRefusal {
    fn load(r: &mut crate::store::Reader) -> Self {
        GateRefusal {
            status: crate::store::Load::load(r),
            areas: crate::store::Load::load(r),
            msg: crate::store::Load::load(r),
        }
    }
}

/// A ranking: the racer, the time in frames, the Grunty's `npcTbl` row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaceRank {
    pub name: &'static str,
    pub time: i16,
    pub row: i16,
}

impl crate::store::Load for RaceRank {
    fn load(r: &mut crate::store::Reader) -> Self {
        RaceRank {
            name: crate::store::Load::load(r),
            time: crate::store::Load::load(r),
            row: crate::store::Load::load(r),
        }
    }
}

/// A Grunty to race: its `npcTbl` row and its stars.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaceGrunty {
    pub row: i16,
    pub speed: i16,
    pub accel: i16,
    pub turn: i16,
}

impl crate::store::Load for RaceGrunty {
    fn load(r: &mut crate::store::Reader) -> Self {
        RaceGrunty {
            row: crate::store::Load::load(r),
            speed: crate::store::Load::load(r),
            accel: crate::store::Load::load(r),
            turn: crate::store::Load::load(r),
        }
    }
}

/// The `fieldui` group's values for a volume, from the build.
#[derive(Debug)]
pub struct FieldUi {
    /// `menuElementData`: the lists `InitMenuList` fills `menuList` from (89; 93 from Mutation on, its loop's bound).
    pub elements: &'static [FieldMenuElement],
    /// `personalMenuHelp`
    pub personal_help: &'static [&'static [&'static str]],
    /// `optionMenuHelp`
    pub option_help: &'static [&'static [&'static str]],
    /// `helpStr`: ": Talk", ": Attack", ...
    pub help: &'static [Option<&'static str>],
    /// The Flag Race's texts (MUT main 0x00353d40).
    pub race_str: RaceStr,
    /// `deadInfo`
    pub dead_info: &'static str,
    /// `newMailStr`
    pub new_mail: &'static str,
    /// `kyviaStatusStr`: eight pieces.
    pub kyvia_status: &'static [&'static str],
    /// `cheatHpStr`: the digits for 5-digit HP.
    pub cheat_hp: &'static str,
    /// `panelFlashTbl`: the panel flash's grey steps.
    pub panel_flash: &'static [u32],
    /// `menuFaceCcsList`: per `charTbl` row; row 18 is Kite before the bracelet.
    pub faces: &'static [MenuFace],
    /// `skillMenuTag`: the pages' tabs.
    pub skill_tags: &'static [&'static str],
    /// `itemMenuTag`
    pub item_tags: &'static [&'static str],
    /// `skillMenuHelp`
    pub skill_help: &'static [&'static [&'static str]],
    /// `itemMenuHelp`
    pub item_help: &'static [&'static [&'static str]],
    /// `targetMenuInfo`
    pub target_info: &'static [&'static str],
    /// `targetMenuWarn`
    pub target_warn: &'static str,
    /// `targetMenuDrainWarn`
    pub target_drain_warn: &'static [&'static str],
    /// `virusCol`: the bracelet gauge's two colour pairs by `erosion / 17`.
    pub virus_col: &'static [[i32; 12]],
    /// `chatMenuTag`
    pub chat_tags: &'static [&'static str],
    /// `chatMenuStr`: the orders.
    pub chat_str: &'static [&'static str],
    /// `chatActionStr`'s pieces.
    pub chat_action: &'static [&'static str],
    /// `chatMenuHelp`
    pub chat_help: &'static [&'static [&'static str]],
    /// `chatMenuWarn`: the orders' refusals.
    pub chat_warn: &'static [Option<&'static [&'static str]>],
    /// `partyMenuWarn`
    pub party_warn: &'static [&'static [&'static str]],
    /// `btInChatAct`: the orders' command numbers.
    pub bt_chat_act: &'static [i32],
    /// `townChatAct`
    pub town_chat_act: &'static [i32],
    /// `gateMenuHelp`
    pub gate_help: &'static [&'static [&'static str]],
    /// `gtNewInfo`
    pub gt_new_info: &'static [&'static [&'static str]],
    /// `gtNewStr1`: the attributes and parts.
    pub gt_new_str1: &'static [Option<&'static str>],
    /// `gtTownMenuHelp`
    pub gt_town_help: &'static [&'static [&'static str]],
    /// `gateWordListMsg`: each story area's note in the Word List.
    pub gate_word_list_msg: &'static [Option<&'static [&'static str]>],
    /// `gtMenuInfo`: "Warp to".
    pub gt_menu_info: &'static str,
    /// `gtNewStr0`'s pieces.
    pub gt_new_str0: &'static [&'static str],
    /// `gtTownMenuStr`: the servers.
    pub gt_town_str: &'static [&'static str],
    /// `serverStr`: the servers' symbols.
    pub server_str: &'static [&'static str],
    /// `gtTownMenuWarn`
    pub gt_town_warn: &'static str,
    /// `gtListMenuWarn`
    pub gt_list_warn: &'static str,
    /// The Area Information row.
    pub gt_area_info: &'static str,
    /// `ccGetGtNewColor`'s colours.
    pub gt_new_colours: &'static [i32],
    /// From Mutation on, the story areas the gate refuses while the bracelet is off, and Kite's line (None on Infection).
    pub gate_refusal: Option<GateRefusal>,
    /// `statusMenuStr`: the Status page's labels.
    pub status_menu: &'static [&'static str],
    /// `statusClassStr`: the classes.
    pub status_class: &'static [&'static str],
    /// `partyInMenuInfo`
    pub party_in_info: &'static [&'static [&'static str]],
    /// `getItemMenuStr`'s lines.
    pub get_item_str: &'static [&'static str],
    /// `getTrapMenuStr`: TrapBoxMenu's lines.
    pub trap_menu: &'static [&'static str],
    /// `trapDischargeStr`
    pub trap_discharge: &'static str,
    /// `showMapInfo`
    pub show_map: &'static str,
    /// `statusUpStr`: "increased by ", "decreased by ", then the stats' names.
    pub status_up: &'static [&'static str],
    /// `installWarnStr`
    pub install_warn: &'static [&'static str],
    /// `epitaphStr0X`'s first piece.
    pub epitaph_unknown: &'static str,
    /// `epitaphStr00`: item 42's pages.
    pub epitaph_00: &'static [&'static [&'static str]],
    /// `epitaphStr00p`
    pub epitaph_00p: &'static [&'static [&'static str]],
    /// `epitaphStr01`: item 43's.
    pub epitaph_01: &'static [&'static [&'static str]],
    /// `epitaphStr01p`
    pub epitaph_01p: &'static [&'static [&'static str]],
    /// `epitaphStr02`: item 44's.
    pub epitaph_02: &'static [&'static [&'static str]],
    /// `epitaphStr02p`
    pub epitaph_02p: &'static [&'static [&'static str]],
    /// `epitaphStr03`: item 45's.
    pub epitaph_03: &'static [&'static [&'static str]],
    /// `epitaphStr03p`
    pub epitaph_03p: &'static [&'static [&'static str]],
    /// `epitaphStr04`: item 46's.
    pub epitaph_04: &'static [&'static [&'static str]],
    /// `epitaphStr04p`
    pub epitaph_04p: &'static [&'static [&'static str]],
    /// `epitaphStr10`: item 48's.
    pub epitaph_10: &'static [&'static [&'static str]],
    /// `epitaphStr10p`
    pub epitaph_10p: &'static [&'static [&'static str]],
    /// `epitaphStr11`: item 68's.
    pub epitaph_11: &'static [&'static [&'static str]],
    /// `epitaphStr11p`
    pub epitaph_11p: &'static [&'static [&'static str]],
    /// `epitaphStrM0`: item 287's, both modes.
    pub epitaph_m0: &'static [&'static [&'static str]],
    /// `epitaphStrM1`: item 288's.
    pub epitaph_m1: &'static [&'static [&'static str]],
    /// `epitaphStrM2`: item 289's.
    pub epitaph_m2: &'static [&'static [&'static str]],
    /// `epitaphStrM3`: item 290's.
    pub epitaph_m3: &'static [&'static [&'static str]],
    /// `ItemBoxList`: 130 item codes by server * 6 + element.
    pub item_box_list: &'static [&'static [i32]],
    /// `DangerItemBoxList`
    pub danger_item_box_list: &'static [&'static [i32]],
    /// `areaItemList`
    pub area_item_list: &'static [&'static [i32]],
    /// `idolItemList`
    pub idol_item_list: &'static [&'static [i32]],
    /// `SukaItemBoxList` by server.
    pub suka_item_box_list: &'static [&'static [i32]],
    /// `idolSubItemList` by server.
    pub idol_sub_item_list: &'static [&'static [i32]],
    /// `recordMenuStr`: "slot 1", "slot 2", "Unused", "Data", "MEMORY CARD".
    pub record_str: &'static [&'static str],
    /// `impItemMenuTag`: Key Items' four tabs.
    pub imp_tags: &'static [&'static str],
    /// `puccigusoCallWarnStr`
    pub grunty_warn: &'static [&'static str],
    /// `shopStr`'s first line: the count window's labels.
    pub shop_str: &'static str,
    /// `inBattleMenuWarn`
    pub in_battle_warn: &'static str,
    /// `gateoutMenuInfo`
    pub gateout_info: &'static str,
    /// `logoutMenuInfo`
    pub logout_info: &'static str,
    /// `statusMenuHelp`: three lines for each cell of the Status grid, 15 rows a column.
    pub status_help: &'static [&'static [&'static str]],
    /// `statusBeffStr`: each added effect's help (lines 0-2) and name (line 3).
    pub status_beff: &'static [&'static [&'static str]],
    /// `equipChangeStr`: each page's four labels, 16 characters each.
    pub equip_change: &'static [&'static str],
    /// `equipMenuWarn`: the refusals.
    pub equip_warn: &'static [&'static [&'static str]],
    /// `addItemCategoryTbl`: the order `AddItem` sorts a list in, (category, rows) pairs.
    pub category_order: &'static [[i16; 2]],
    /// `spcMsgTbl`: where each member's line tables are, the pointers `SetSpcBaseMsg` stores in the save.
    pub spc_msg_tbl: &'static [u32],
    /// `partyMenuHelp`
    pub party_help: &'static [&'static [&'static str]],
    /// `partyOutMenuInfo`
    pub party_out_info: &'static [&'static [&'static str]],
    /// A party message table, a record a member.
    pub spc_msg0: &'static [Option<EvMsgData>],
    /// A party message table, a record a member.
    pub spc_msg1: &'static [Option<EvMsgData>],
    /// A party message table, a record a member.
    pub spc_msg2: &'static [Option<EvMsgData>],
    /// A party message table, a record a member.
    pub spc_msg3: &'static [Option<EvMsgData>],
    /// A party message table, a record a member.
    pub spc_msg4: &'static [Option<EvMsgData>],
    /// A party message table, a record a member.
    pub spc_msg5: &'static [Option<EvMsgData>],
    /// `datadrainDemoMenuInfo`
    pub drain_demo_info: &'static [&'static [&'static str]],
    /// The Controller picture's file.
    pub control_file: &'static str,
    /// The Controller picture's texture.
    pub control_tex: &'static str,
    /// `timeIdolItem`: the items for the places gained.
    pub time_idol_item: &'static [i32],
    /// `getSkillMenuStr`'s first piece.
    pub get_skill: &'static str,
    /// `timeIdolMenuStr`
    pub time_idol_str: &'static [&'static str],
    /// `timeIdolMenuHelp`
    pub time_idol_help: &'static [&'static [&'static str]],
    /// `fountainMenuHelp`
    pub fountain_help: &'static [&'static [&'static str]],
    /// `fountainMenuStr`
    pub fountain_answers: &'static str,
    /// `fountainNameStr`
    pub fountain_names: &'static [&'static str],
    /// The fountains' elements: 80 each, by fountain.
    pub fe_tbl: &'static [&'static [i16]],
    /// `f_limitTbl`: how many count, by server (+ 10 from level 4, + 5 for category 2).
    pub f_limit: &'static [i16],
    /// `tpcTalkStr`: the trading PCs' offer's two pieces.
    pub tpc_talk: &'static [&'static str],
    /// `tradeMenuHelp`
    pub trade_help: &'static [&'static [&'static str]],
    /// `presentMenuHelp`
    pub present_help: &'static [&'static [&'static str]],
    /// `tradeMenuStr`
    pub trade_menu_str: &'static str,
    /// `buyMenuHelp`
    pub buy_help: &'static [&'static [&'static str]],
    /// `sellMenuHelp`: the count's help, the question.
    pub sell_help: &'static [&'static [&'static str]],
    /// `itemDepositMenuHelp`
    pub deposit_help: &'static [&'static [&'static str]],
    /// `itemDrawMenuHelp`
    pub draw_help: &'static [&'static [&'static str]],
    /// `ItemShopItemList`: the stock by server.
    pub item_shop: &'static [&'static [i32]],
    /// `EquipShopItemList`
    pub equip_shop: &'static [&'static [i32]],
    /// `MagicShopItemList`
    pub magic_shop: &'static [&'static [i32]],
    /// `SetPlItemList`'s page table.
    pub pl_item_pages: &'static [i32],
    /// `breederMenuStr`: the breeder's rows (from Mutation on also Flag Race and Rankings).
    pub breeder_str: &'static [&'static str],
    /// The Flag Race's rankings before the player's, three a town (MUT gcmn 0x006d8610).
    pub race_ranks: &'static [[RaceRank; 3]],
    /// The three Grunties a town's Flag Race offers, with their stars (MUT gcmn 0x006d8670).
    pub race_grunties: &'static [[RaceGrunty; 3]],
    /// `breedingMenuStr`: the status rows.
    pub breeding_str: &'static str,
    /// `breedingMenuHelp`: "There is no food.", then the help.
    pub breeding_help: &'static [&'static [&'static str]],
    /// `foodTbl`: what each food (key items 26-41) does to a Grunty's six stats.
    pub food: &'static [FoodParam],
    /// `spcTradeRateTbl`: how much members 1-17 (1-20 from Mutation on) value a kind of item, in tenths.
    pub spc_trade_rate: &'static [[i16; 14]],
    /// `npcTradeRateTbl`
    pub npc_trade_rate: &'static [[i16; 14]],
    /// Members 1-20's wanted gifts, 16 each: one worth 50000 unless the member has it (MUT main 0x0035f850).
    pub gift_wants: &'static [[ItemList; 16]],
    /// The worth bands of the thanks: equipment's (over the member's best of its kind), then the rest's.
    pub gift_bands: &'static [[i32; 4]],
    /// Members 1-20's rates for a gift, as `spcTradeRateTbl`'s (MUT main 0x0035f620; Trade keeps that one).
    pub gift_rates: &'static [[i16; 14]],
    /// `@3218`: `AddFriendship`'s cap by volume.
    pub friendship_cap: &'static [i32],
    /// `spcMsgPresent10`: each member's first thanks record for a gift.
    pub spc_msg_present10: &'static [Option<EvMsgData>],
    /// Where it is.
    pub spc_msg_present10_va: u32,
    /// `spcMsgPresent11`: the same once the member's story has begun.
    pub spc_msg_present11: &'static [Option<EvMsgData>],
    /// Where it is.
    pub spc_msg_present11_va: u32,
    /// `breedTeachMsgTbl`: the About pages' records.
    pub breed_teach: &'static [Option<EvMsgData>],
    /// Where it is.
    pub breed_teach_va: u32,
    /// `breedTeachMsgTbl2`: elsewhere.
    pub breed_teach2: &'static [Option<EvMsgData>],
    /// Where it is.
    pub breed_teach2_va: u32,
    /// `pgEvoMsg`: a Grunty growing up.
    pub pg_evo_msg: &'static [EvMsgData],
    /// Where it is.
    pub pg_evo_msg_va: u32,
    /// `errorData`: the record shown for a missing line.
    pub error_data: EvMsgData,
    /// Where `errorData` is, which a chain of records holds.
    pub error_data_va: u32,
    /// `kiteSelfTalk`: Kite's line as area 43's map sends the party back (`EVENTAREA03::Draw`).
    pub kite_self_talk: EvMsgData,
    /// Where `kiteSelfTalk` is.
    pub kite_self_talk_va: u32,
    /// `ccCheckVoiceGrp(id)`: ids 141-157's voice groups (its jump table's `li $v0, n`), -1 none.
    pub voice_groups: &'static [i32],
    /// `gtHackInfo`
    pub hack_info: &'static [&'static str],
    /// `gtHackStr`
    pub hack_bar: &'static str,
    /// `dataDrainWarn`: 34 pieces.
    pub drain_warn: &'static [&'static str],
    /// `dataDrainEvolutionStr`
    pub drain_evolution: &'static [&'static [&'static str]],
}

impl crate::store::Load for FieldUi {
    fn load(r: &mut crate::store::Reader) -> Self {
        FieldUi {
            elements: crate::store::Load::load(r),
            personal_help: crate::store::Load::load(r),
            option_help: crate::store::Load::load(r),
            help: crate::store::Load::load(r),
            race_str: crate::store::Load::load(r),
            dead_info: crate::store::Load::load(r),
            new_mail: crate::store::Load::load(r),
            kyvia_status: crate::store::Load::load(r),
            cheat_hp: crate::store::Load::load(r),
            panel_flash: crate::store::Load::load(r),
            faces: crate::store::Load::load(r),
            skill_tags: crate::store::Load::load(r),
            item_tags: crate::store::Load::load(r),
            skill_help: crate::store::Load::load(r),
            item_help: crate::store::Load::load(r),
            target_info: crate::store::Load::load(r),
            target_warn: crate::store::Load::load(r),
            target_drain_warn: crate::store::Load::load(r),
            virus_col: crate::store::Load::load(r),
            chat_tags: crate::store::Load::load(r),
            chat_str: crate::store::Load::load(r),
            chat_action: crate::store::Load::load(r),
            chat_help: crate::store::Load::load(r),
            chat_warn: crate::store::Load::load(r),
            party_warn: crate::store::Load::load(r),
            bt_chat_act: crate::store::Load::load(r),
            town_chat_act: crate::store::Load::load(r),
            gate_help: crate::store::Load::load(r),
            gt_new_info: crate::store::Load::load(r),
            gt_new_str1: crate::store::Load::load(r),
            gt_town_help: crate::store::Load::load(r),
            gate_word_list_msg: crate::store::Load::load(r),
            gt_menu_info: crate::store::Load::load(r),
            gt_new_str0: crate::store::Load::load(r),
            gt_town_str: crate::store::Load::load(r),
            server_str: crate::store::Load::load(r),
            gt_town_warn: crate::store::Load::load(r),
            gt_list_warn: crate::store::Load::load(r),
            gt_area_info: crate::store::Load::load(r),
            gt_new_colours: crate::store::Load::load(r),
            gate_refusal: crate::store::Load::load(r),
            status_menu: crate::store::Load::load(r),
            status_class: crate::store::Load::load(r),
            party_in_info: crate::store::Load::load(r),
            get_item_str: crate::store::Load::load(r),
            trap_menu: crate::store::Load::load(r),
            trap_discharge: crate::store::Load::load(r),
            show_map: crate::store::Load::load(r),
            status_up: crate::store::Load::load(r),
            install_warn: crate::store::Load::load(r),
            epitaph_unknown: crate::store::Load::load(r),
            epitaph_00: crate::store::Load::load(r),
            epitaph_00p: crate::store::Load::load(r),
            epitaph_01: crate::store::Load::load(r),
            epitaph_01p: crate::store::Load::load(r),
            epitaph_02: crate::store::Load::load(r),
            epitaph_02p: crate::store::Load::load(r),
            epitaph_03: crate::store::Load::load(r),
            epitaph_03p: crate::store::Load::load(r),
            epitaph_04: crate::store::Load::load(r),
            epitaph_04p: crate::store::Load::load(r),
            epitaph_10: crate::store::Load::load(r),
            epitaph_10p: crate::store::Load::load(r),
            epitaph_11: crate::store::Load::load(r),
            epitaph_11p: crate::store::Load::load(r),
            epitaph_m0: crate::store::Load::load(r),
            epitaph_m1: crate::store::Load::load(r),
            epitaph_m2: crate::store::Load::load(r),
            epitaph_m3: crate::store::Load::load(r),
            item_box_list: crate::store::Load::load(r),
            danger_item_box_list: crate::store::Load::load(r),
            area_item_list: crate::store::Load::load(r),
            idol_item_list: crate::store::Load::load(r),
            suka_item_box_list: crate::store::Load::load(r),
            idol_sub_item_list: crate::store::Load::load(r),
            record_str: crate::store::Load::load(r),
            imp_tags: crate::store::Load::load(r),
            grunty_warn: crate::store::Load::load(r),
            shop_str: crate::store::Load::load(r),
            in_battle_warn: crate::store::Load::load(r),
            gateout_info: crate::store::Load::load(r),
            logout_info: crate::store::Load::load(r),
            status_help: crate::store::Load::load(r),
            status_beff: crate::store::Load::load(r),
            equip_change: crate::store::Load::load(r),
            equip_warn: crate::store::Load::load(r),
            category_order: crate::store::Load::load(r),
            spc_msg_tbl: crate::store::Load::load(r),
            party_help: crate::store::Load::load(r),
            party_out_info: crate::store::Load::load(r),
            spc_msg0: crate::store::Load::load(r),
            spc_msg1: crate::store::Load::load(r),
            spc_msg2: crate::store::Load::load(r),
            spc_msg3: crate::store::Load::load(r),
            spc_msg4: crate::store::Load::load(r),
            spc_msg5: crate::store::Load::load(r),
            drain_demo_info: crate::store::Load::load(r),
            control_file: crate::store::Load::load(r),
            control_tex: crate::store::Load::load(r),
            time_idol_item: crate::store::Load::load(r),
            get_skill: crate::store::Load::load(r),
            time_idol_str: crate::store::Load::load(r),
            time_idol_help: crate::store::Load::load(r),
            fountain_help: crate::store::Load::load(r),
            fountain_answers: crate::store::Load::load(r),
            fountain_names: crate::store::Load::load(r),
            fe_tbl: crate::store::Load::load(r),
            f_limit: crate::store::Load::load(r),
            tpc_talk: crate::store::Load::load(r),
            trade_help: crate::store::Load::load(r),
            present_help: crate::store::Load::load(r),
            trade_menu_str: crate::store::Load::load(r),
            buy_help: crate::store::Load::load(r),
            sell_help: crate::store::Load::load(r),
            deposit_help: crate::store::Load::load(r),
            draw_help: crate::store::Load::load(r),
            item_shop: crate::store::Load::load(r),
            equip_shop: crate::store::Load::load(r),
            magic_shop: crate::store::Load::load(r),
            pl_item_pages: crate::store::Load::load(r),
            breeder_str: crate::store::Load::load(r),
            race_ranks: crate::store::Load::load(r),
            race_grunties: crate::store::Load::load(r),
            breeding_str: crate::store::Load::load(r),
            breeding_help: crate::store::Load::load(r),
            food: crate::store::Load::load(r),
            spc_trade_rate: crate::store::Load::load(r),
            npc_trade_rate: crate::store::Load::load(r),
            gift_wants: crate::store::Load::load(r),
            gift_bands: crate::store::Load::load(r),
            gift_rates: crate::store::Load::load(r),
            friendship_cap: crate::store::Load::load(r),
            spc_msg_present10: crate::store::Load::load(r),
            spc_msg_present10_va: crate::store::Load::load(r),
            spc_msg_present11: crate::store::Load::load(r),
            spc_msg_present11_va: crate::store::Load::load(r),
            breed_teach: crate::store::Load::load(r),
            breed_teach_va: crate::store::Load::load(r),
            breed_teach2: crate::store::Load::load(r),
            breed_teach2_va: crate::store::Load::load(r),
            pg_evo_msg: crate::store::Load::load(r),
            pg_evo_msg_va: crate::store::Load::load(r),
            error_data: crate::store::Load::load(r),
            error_data_va: crate::store::Load::load(r),
            kite_self_talk: crate::store::Load::load(r),
            kite_self_talk_va: crate::store::Load::load(r),
            voice_groups: crate::store::Load::load(r),
            hack_info: crate::store::Load::load(r),
            hack_bar: crate::store::Load::load(r),
            drain_warn: crate::store::Load::load(r),
            drain_evolution: crate::store::Load::load(r),
        }
    }
}

impl FieldUi {
    pub fn elements(&self) -> &'static [FieldMenuElement] {
        self.elements
    }
    pub fn personal_help(&self) -> &'static [&'static [&'static str]] {
        self.personal_help
    }
    pub fn option_help(&self) -> &'static [&'static [&'static str]] {
        self.option_help
    }
    pub fn help(&self) -> &'static [Option<&'static str>] {
        self.help
    }
    pub fn race_str(&self) -> RaceStr {
        self.race_str
    }
    pub fn dead_info(&self) -> &'static str {
        self.dead_info
    }
    pub fn new_mail(&self) -> &'static str {
        self.new_mail
    }
    pub fn kyvia_status(&self) -> &'static [&'static str] {
        self.kyvia_status
    }
    pub fn cheat_hp(&self) -> &'static str {
        self.cheat_hp
    }
    pub fn panel_flash(&self) -> &'static [u32] {
        self.panel_flash
    }
    pub fn faces(&self) -> &'static [MenuFace] {
        self.faces
    }
    pub fn skill_tags(&self) -> &'static [&'static str] {
        self.skill_tags
    }
    pub fn item_tags(&self) -> &'static [&'static str] {
        self.item_tags
    }
    pub fn skill_help(&self) -> &'static [&'static [&'static str]] {
        self.skill_help
    }
    pub fn item_help(&self) -> &'static [&'static [&'static str]] {
        self.item_help
    }
    pub fn target_info(&self) -> &'static [&'static str] {
        self.target_info
    }
    pub fn target_warn(&self) -> &'static str {
        self.target_warn
    }
    pub fn target_drain_warn(&self) -> &'static [&'static str] {
        self.target_drain_warn
    }
    pub fn virus_col(&self) -> &'static [[i32; 12]] {
        self.virus_col
    }
    pub fn chat_tags(&self) -> &'static [&'static str] {
        self.chat_tags
    }
    pub fn chat_str(&self) -> &'static [&'static str] {
        self.chat_str
    }
    pub fn chat_action(&self) -> &'static [&'static str] {
        self.chat_action
    }
    pub fn chat_help(&self) -> &'static [&'static [&'static str]] {
        self.chat_help
    }
    pub fn chat_warn(&self) -> &'static [Option<&'static [&'static str]>] {
        self.chat_warn
    }
    pub fn party_warn(&self) -> &'static [&'static [&'static str]] {
        self.party_warn
    }
    pub fn bt_chat_act(&self) -> &'static [i32] {
        self.bt_chat_act
    }
    pub fn town_chat_act(&self) -> &'static [i32] {
        self.town_chat_act
    }
    pub fn gate_help(&self) -> &'static [&'static [&'static str]] {
        self.gate_help
    }
    pub fn gt_new_info(&self) -> &'static [&'static [&'static str]] {
        self.gt_new_info
    }
    pub fn gt_new_str1(&self) -> &'static [Option<&'static str>] {
        self.gt_new_str1
    }
    pub fn gt_town_help(&self) -> &'static [&'static [&'static str]] {
        self.gt_town_help
    }
    pub fn gate_word_list_msg(&self) -> &'static [Option<&'static [&'static str]>] {
        self.gate_word_list_msg
    }
    pub fn gt_menu_info(&self) -> &'static str {
        self.gt_menu_info
    }
    pub fn gt_new_str0(&self) -> &'static [&'static str] {
        self.gt_new_str0
    }
    pub fn gt_town_str(&self) -> &'static [&'static str] {
        self.gt_town_str
    }
    pub fn server_str(&self) -> &'static [&'static str] {
        self.server_str
    }
    pub fn gt_town_warn(&self) -> &'static str {
        self.gt_town_warn
    }
    pub fn gt_list_warn(&self) -> &'static str {
        self.gt_list_warn
    }
    pub fn gt_area_info(&self) -> &'static str {
        self.gt_area_info
    }
    pub fn gt_new_colours(&self) -> &'static [i32] {
        self.gt_new_colours
    }
    pub fn gate_refusal(&self) -> Option<GateRefusal> {
        self.gate_refusal
    }
    pub fn status_menu(&self) -> &'static [&'static str] {
        self.status_menu
    }
    pub fn status_class(&self) -> &'static [&'static str] {
        self.status_class
    }
    pub fn party_in_info(&self) -> &'static [&'static [&'static str]] {
        self.party_in_info
    }
    pub fn get_item_str(&self) -> &'static [&'static str] {
        self.get_item_str
    }
    pub fn trap_menu(&self) -> &'static [&'static str] {
        self.trap_menu
    }
    pub fn trap_discharge(&self) -> &'static str {
        self.trap_discharge
    }
    pub fn show_map(&self) -> &'static str {
        self.show_map
    }
    pub fn status_up(&self) -> &'static [&'static str] {
        self.status_up
    }
    pub fn install_warn(&self) -> &'static [&'static str] {
        self.install_warn
    }
    pub fn epitaph_unknown(&self) -> &'static str {
        self.epitaph_unknown
    }
    pub fn epitaph_00(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_00
    }
    pub fn epitaph_00p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_00p
    }
    pub fn epitaph_01(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_01
    }
    pub fn epitaph_01p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_01p
    }
    pub fn epitaph_02(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_02
    }
    pub fn epitaph_02p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_02p
    }
    pub fn epitaph_03(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_03
    }
    pub fn epitaph_03p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_03p
    }
    pub fn epitaph_04(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_04
    }
    pub fn epitaph_04p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_04p
    }
    pub fn epitaph_10(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_10
    }
    pub fn epitaph_10p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_10p
    }
    pub fn epitaph_11(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_11
    }
    pub fn epitaph_11p(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_11p
    }
    pub fn epitaph_m0(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_m0
    }
    pub fn epitaph_m1(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_m1
    }
    pub fn epitaph_m2(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_m2
    }
    pub fn epitaph_m3(&self) -> &'static [&'static [&'static str]] {
        self.epitaph_m3
    }
    pub fn item_box_list(&self) -> &'static [&'static [i32]] {
        self.item_box_list
    }
    pub fn danger_item_box_list(&self) -> &'static [&'static [i32]] {
        self.danger_item_box_list
    }
    pub fn area_item_list(&self) -> &'static [&'static [i32]] {
        self.area_item_list
    }
    pub fn idol_item_list(&self) -> &'static [&'static [i32]] {
        self.idol_item_list
    }
    pub fn suka_item_box_list(&self) -> &'static [&'static [i32]] {
        self.suka_item_box_list
    }
    pub fn idol_sub_item_list(&self) -> &'static [&'static [i32]] {
        self.idol_sub_item_list
    }
    pub fn record_str(&self) -> &'static [&'static str] {
        self.record_str
    }
    pub fn imp_tags(&self) -> &'static [&'static str] {
        self.imp_tags
    }
    pub fn grunty_warn(&self) -> &'static [&'static str] {
        self.grunty_warn
    }
    pub fn shop_str(&self) -> &'static str {
        self.shop_str
    }
    pub fn in_battle_warn(&self) -> &'static str {
        self.in_battle_warn
    }
    pub fn gateout_info(&self) -> &'static str {
        self.gateout_info
    }
    pub fn logout_info(&self) -> &'static str {
        self.logout_info
    }
    pub fn status_help(&self) -> &'static [&'static [&'static str]] {
        self.status_help
    }
    pub fn status_beff(&self) -> &'static [&'static [&'static str]] {
        self.status_beff
    }
    pub fn equip_change(&self) -> &'static [&'static str] {
        self.equip_change
    }
    pub fn equip_warn(&self) -> &'static [&'static [&'static str]] {
        self.equip_warn
    }
    pub fn category_order(&self) -> &'static [[i16; 2]] {
        self.category_order
    }
    pub fn spc_msg_tbl(&self) -> &'static [u32] {
        self.spc_msg_tbl
    }
    pub fn party_help(&self) -> &'static [&'static [&'static str]] {
        self.party_help
    }
    pub fn party_out_info(&self) -> &'static [&'static [&'static str]] {
        self.party_out_info
    }
    pub fn spc_msg0(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg0
    }
    pub fn spc_msg1(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg1
    }
    pub fn spc_msg2(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg2
    }
    pub fn spc_msg3(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg3
    }
    pub fn spc_msg4(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg4
    }
    pub fn spc_msg5(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg5
    }
    pub fn drain_demo_info(&self) -> &'static [&'static [&'static str]] {
        self.drain_demo_info
    }
    pub fn control_file(&self) -> &'static str {
        self.control_file
    }
    pub fn control_tex(&self) -> &'static str {
        self.control_tex
    }
    pub fn time_idol_item(&self) -> &'static [i32] {
        self.time_idol_item
    }
    pub fn get_skill(&self) -> &'static str {
        self.get_skill
    }
    pub fn time_idol_str(&self) -> &'static [&'static str] {
        self.time_idol_str
    }
    pub fn time_idol_help(&self) -> &'static [&'static [&'static str]] {
        self.time_idol_help
    }
    pub fn fountain_help(&self) -> &'static [&'static [&'static str]] {
        self.fountain_help
    }
    pub fn fountain_answers(&self) -> &'static str {
        self.fountain_answers
    }
    pub fn fountain_names(&self) -> &'static [&'static str] {
        self.fountain_names
    }
    pub fn fe_tbl(&self) -> &'static [&'static [i16]] {
        self.fe_tbl
    }
    pub fn f_limit(&self) -> &'static [i16] {
        self.f_limit
    }
    pub fn tpc_talk(&self) -> &'static [&'static str] {
        self.tpc_talk
    }
    pub fn trade_help(&self) -> &'static [&'static [&'static str]] {
        self.trade_help
    }
    pub fn present_help(&self) -> &'static [&'static [&'static str]] {
        self.present_help
    }
    pub fn trade_menu_str(&self) -> &'static str {
        self.trade_menu_str
    }
    pub fn buy_help(&self) -> &'static [&'static [&'static str]] {
        self.buy_help
    }
    pub fn sell_help(&self) -> &'static [&'static [&'static str]] {
        self.sell_help
    }
    pub fn deposit_help(&self) -> &'static [&'static [&'static str]] {
        self.deposit_help
    }
    pub fn draw_help(&self) -> &'static [&'static [&'static str]] {
        self.draw_help
    }
    pub fn item_shop(&self) -> &'static [&'static [i32]] {
        self.item_shop
    }
    pub fn equip_shop(&self) -> &'static [&'static [i32]] {
        self.equip_shop
    }
    pub fn magic_shop(&self) -> &'static [&'static [i32]] {
        self.magic_shop
    }
    pub fn pl_item_pages(&self) -> &'static [i32] {
        self.pl_item_pages
    }
    pub fn breeder_str(&self) -> &'static [&'static str] {
        self.breeder_str
    }
    pub fn race_ranks(&self) -> &'static [[RaceRank; 3]] {
        self.race_ranks
    }
    pub fn race_grunties(&self) -> &'static [[RaceGrunty; 3]] {
        self.race_grunties
    }
    pub fn breeding_str(&self) -> &'static str {
        self.breeding_str
    }
    pub fn breeding_help(&self) -> &'static [&'static [&'static str]] {
        self.breeding_help
    }
    pub fn food(&self) -> &'static [FoodParam] {
        self.food
    }
    pub fn spc_trade_rate(&self) -> &'static [[i16; 14]] {
        self.spc_trade_rate
    }
    pub fn npc_trade_rate(&self) -> &'static [[i16; 14]] {
        self.npc_trade_rate
    }
    pub fn gift_wants(&self) -> &'static [[ItemList; 16]] {
        self.gift_wants
    }
    pub fn gift_bands(&self) -> &'static [[i32; 4]] {
        self.gift_bands
    }
    pub fn gift_rates(&self) -> &'static [[i16; 14]] {
        self.gift_rates
    }
    pub fn friendship_cap(&self) -> &'static [i32] {
        self.friendship_cap
    }
    pub fn spc_msg_present10(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg_present10
    }
    pub fn spc_msg_present10_va(&self) -> u32 {
        self.spc_msg_present10_va
    }
    pub fn spc_msg_present11(&self) -> &'static [Option<EvMsgData>] {
        self.spc_msg_present11
    }
    pub fn spc_msg_present11_va(&self) -> u32 {
        self.spc_msg_present11_va
    }
    pub fn breed_teach(&self) -> &'static [Option<EvMsgData>] {
        self.breed_teach
    }
    pub fn breed_teach_va(&self) -> u32 {
        self.breed_teach_va
    }
    pub fn breed_teach2(&self) -> &'static [Option<EvMsgData>] {
        self.breed_teach2
    }
    pub fn breed_teach2_va(&self) -> u32 {
        self.breed_teach2_va
    }
    pub fn pg_evo_msg(&self) -> &'static [EvMsgData] {
        self.pg_evo_msg
    }
    pub fn pg_evo_msg_va(&self) -> u32 {
        self.pg_evo_msg_va
    }
    pub fn error_data(&self) -> EvMsgData {
        self.error_data
    }
    pub fn error_data_va(&self) -> u32 {
        self.error_data_va
    }
    pub fn kite_self_talk(&self) -> EvMsgData {
        self.kite_self_talk
    }
    pub fn kite_self_talk_va(&self) -> u32 {
        self.kite_self_talk_va
    }
    pub fn voice_groups(&self) -> &'static [i32] {
        self.voice_groups
    }
    pub fn hack_info(&self) -> &'static [&'static str] {
        self.hack_info
    }
    pub fn hack_bar(&self) -> &'static str {
        self.hack_bar
    }
    pub fn drain_warn(&self) -> &'static [&'static str] {
        self.drain_warn
    }
    pub fn drain_evolution(&self) -> &'static [&'static [&'static str]] {
        self.drain_evolution
    }
}

/// `personalMenuHelp`
pub static PERSONAL_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().personal_help);

/// `optionMenuHelp`
pub static OPTION_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().option_help);

/// `helpStr`: ": Talk", ": Attack", ...
pub static HELP: std::sync::LazyLock<&'static [Option<&'static str>]> = std::sync::LazyLock::new(|| shared().help);

/// `deadInfo`
pub static DEAD_INFO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().dead_info);

/// `newMailStr`
pub static NEW_MAIL: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().new_mail);

/// `kyviaStatusStr`: eight pieces.
pub static KYVIA_STATUS: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().kyvia_status);

/// `cheatHpStr`: the digits for 5-digit HP.
pub static CHEAT_HP: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().cheat_hp);

/// `panelFlashTbl`: the panel flash's grey steps.
pub static PANEL_FLASH: std::sync::LazyLock<&'static [u32]> = std::sync::LazyLock::new(|| shared().panel_flash);

/// `skillMenuTag`: the pages' tabs.
pub static SKILL_TAGS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().skill_tags);

/// `itemMenuTag`
pub static ITEM_TAGS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().item_tags);

/// `skillMenuHelp`
pub static SKILL_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().skill_help);

/// `itemMenuHelp`
pub static ITEM_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().item_help);

/// `targetMenuInfo`
pub static TARGET_INFO: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().target_info);

/// `targetMenuWarn`
pub static TARGET_WARN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().target_warn);

/// `virusCol`: the bracelet gauge's two colour pairs by `erosion / 17`.
pub static VIRUS_COL: std::sync::LazyLock<&'static [[i32; 12]]> = std::sync::LazyLock::new(|| shared().virus_col);

/// `chatMenuTag`
pub static CHAT_TAGS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().chat_tags);

/// `chatMenuStr`: the orders.
pub static CHAT_STR: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().chat_str);

/// `chatActionStr`'s pieces.
pub static CHAT_ACTION: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().chat_action);

/// `chatMenuHelp`
pub static CHAT_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().chat_help);

/// `chatMenuWarn`: the orders' refusals.
pub static CHAT_WARN: std::sync::LazyLock<&'static [Option<&'static [&'static str]>]> =
    std::sync::LazyLock::new(|| shared().chat_warn);

/// `btInChatAct`: the orders' command numbers.
pub static BT_CHAT_ACT: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().bt_chat_act);

/// `townChatAct`
pub static TOWN_CHAT_ACT: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().town_chat_act);

/// `gateMenuHelp`
pub static GATE_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().gate_help);

/// `gtNewInfo`
pub static GT_NEW_INFO: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().gt_new_info);

/// `gtNewStr1`: the attributes and parts.
pub static GT_NEW_STR1: std::sync::LazyLock<&'static [Option<&'static str>]> =
    std::sync::LazyLock::new(|| shared().gt_new_str1);

/// `gtMenuInfo`: "Warp to".
pub static GT_MENU_INFO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().gt_menu_info);

/// `gtNewStr0`'s pieces.
pub static GT_NEW_STR0: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().gt_new_str0);

/// `gtTownMenuStr`: the servers.
pub static GT_TOWN_STR: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().gt_town_str);

/// `serverStr`: the servers' symbols.
pub static SERVER_STR: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().server_str);

/// `gtTownMenuWarn`
pub static GT_TOWN_WARN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().gt_town_warn);

/// `gtListMenuWarn`
pub static GT_LIST_WARN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().gt_list_warn);

/// The Area Information row.
pub static GT_AREA_INFO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().gt_area_info);

/// `ccGetGtNewColor`'s colours.
pub static GT_NEW_COLOURS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().gt_new_colours);

/// `statusMenuStr`: the Status page's labels.
pub static STATUS_MENU: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().status_menu);

/// `statusClassStr`: the classes.
pub static STATUS_CLASS: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().status_class);

/// `getItemMenuStr`'s lines.
pub static GET_ITEM_STR: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().get_item_str);

/// `getTrapMenuStr`: TrapBoxMenu's lines.
pub static TRAP_MENU: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().trap_menu);

/// `trapDischargeStr`
pub static TRAP_DISCHARGE: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().trap_discharge);

/// `showMapInfo`
pub static SHOW_MAP: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().show_map);

/// `installWarnStr`
pub static INSTALL_WARN: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().install_warn);

/// `epitaphStr0X`'s first piece.
pub static EPITAPH_UNKNOWN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().epitaph_unknown);

/// `epitaphStr00`: item 42's pages.
pub static EPITAPH_00: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().epitaph_00);

/// `epitaphStr10`: item 48's.
pub static EPITAPH_10: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().epitaph_10);

/// `ItemBoxList`: 130 item codes by server * 6 + element.
pub static ITEM_BOX_LIST: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().item_box_list);

/// `DangerItemBoxList`
pub static DANGER_ITEM_BOX_LIST: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().danger_item_box_list);

/// `areaItemList`
pub static AREA_ITEM_LIST: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().area_item_list);

/// `SukaItemBoxList` by server.
pub static SUKA_ITEM_BOX_LIST: std::sync::LazyLock<&'static [&'static [i32]]> =
    std::sync::LazyLock::new(|| shared().suka_item_box_list);

/// `recordMenuStr`: "slot 1", "slot 2", "Unused", "Data", "MEMORY CARD".
pub static RECORD_STR: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().record_str);

/// `impItemMenuTag`: Key Items' four tabs.
pub static IMP_TAGS: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().imp_tags);

/// `puccigusoCallWarnStr`
pub static GRUNTY_WARN: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().grunty_warn);

/// `shopStr`'s first line: the count window's labels.
pub static SHOP_STR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().shop_str);

/// `inBattleMenuWarn`
pub static IN_BATTLE_WARN: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().in_battle_warn);

/// `gateoutMenuInfo`
pub static GATEOUT_INFO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().gateout_info);

/// `logoutMenuInfo`
pub static LOGOUT_INFO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().logout_info);

/// `statusBeffStr`: each added effect's help (lines 0-2) and name (line 3).
pub static STATUS_BEFF: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().status_beff);

/// `equipChangeStr`: each page's four labels, 16 characters each.
pub static EQUIP_CHANGE: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().equip_change);

/// `equipMenuWarn`: the refusals.
pub static EQUIP_WARN: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().equip_warn);

/// `partyMenuHelp`
pub static PARTY_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().party_help);

/// `partyOutMenuInfo`
pub static PARTY_OUT_INFO: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().party_out_info);

/// The Controller picture's file.
pub static CONTROL_FILE: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().control_file);

/// The Controller picture's texture.
pub static CONTROL_TEX: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().control_tex);

/// `timeIdolItem`: the items for the places gained.
pub static TIME_IDOL_ITEM: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().time_idol_item);

/// `getSkillMenuStr`'s first piece.
pub static GET_SKILL: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().get_skill);

/// `timeIdolMenuHelp`
pub static TIME_IDOL_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().time_idol_help);

/// `fountainMenuStr`
pub static FOUNTAIN_ANSWERS: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().fountain_answers);

/// `fountainNameStr`
pub static FOUNTAIN_NAMES: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().fountain_names);

/// `f_limitTbl`: how many count, by server (+ 10 from level 4, + 5 for category 2).
pub static F_LIMIT: std::sync::LazyLock<&'static [i16]> = std::sync::LazyLock::new(|| shared().f_limit);

/// `tpcTalkStr`: the trading PCs' offer's two pieces.
pub static TPC_TALK: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().tpc_talk);

/// `presentMenuHelp`
pub static PRESENT_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().present_help);

/// `tradeMenuStr`
pub static TRADE_MENU_STR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().trade_menu_str);

/// `sellMenuHelp`: the count's help, the question.
pub static SELL_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().sell_help);

/// `itemDepositMenuHelp`
pub static DEPOSIT_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().deposit_help);

/// `itemDrawMenuHelp`
pub static DRAW_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().draw_help);

/// `SetPlItemList`'s page table.
pub static PL_ITEM_PAGES: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().pl_item_pages);

/// `breedingMenuStr`: the status rows.
pub static BREEDING_STR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().breeding_str);

/// `breedingMenuHelp`: "There is no food.", then the help.
pub static BREEDING_HELP: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().breeding_help);

/// `foodTbl`: what each food (key items 26-41) does to a Grunty's six stats.
pub static FOOD: std::sync::LazyLock<&'static [FoodParam]> = std::sync::LazyLock::new(|| shared().food);

/// `@3218`: `AddFriendship`'s cap by volume.
pub static FRIENDSHIP_CAP: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().friendship_cap);

/// `errorData`: the record shown for a missing line.
pub static ERROR_DATA: std::sync::LazyLock<EvMsgData> = std::sync::LazyLock::new(|| shared().error_data);

/// `kiteSelfTalk`: Kite's line as area 43's map sends the party back (`EVENTAREA03::Draw`).
pub static KITE_SELF_TALK: std::sync::LazyLock<EvMsgData> = std::sync::LazyLock::new(|| shared().kite_self_talk);

/// `ccCheckVoiceGrp(id)`: ids 141-157's voice groups (its jump table's `li $v0, n`), -1 none.
pub static VOICE_GROUPS: std::sync::LazyLock<&'static [i32]> = std::sync::LazyLock::new(|| shared().voice_groups);

/// `gtHackInfo`
pub static HACK_INFO: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().hack_info);

/// `gtHackStr`
pub static HACK_BAR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().hack_bar);

/// `dataDrainEvolutionStr`
pub static DRAIN_EVOLUTION: std::sync::LazyLock<&'static [&'static [&'static str]]> =
    std::sync::LazyLock::new(|| shared().drain_evolution);

/// The volume's FieldUi (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static FieldUi {
    static READ: [std::sync::OnceLock<&'static FieldUi>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "fieldui"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static FieldUi {
    static READ: std::sync::OnceLock<&'static FieldUi> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("fieldui"))
}
