// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/fonts.bin`, plans/build-data.md).

//! The two bitmap fonts in main that ccKanji draws ASCII with.

use crate::volume::Volume;

/// The `fonts` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Fonts {
    /// `ef8x16`: 8x16 glyphs, 16 a row, 64 bytes a row line.
    pub ef8x16: &'static [u8],
    /// The two glyph rows past `ef8x16`'s end, which glyphs 112-130 read: the volume's next globals.
    pub ef8x16_past: &'static [u8],
    /// `ef12x20`: 12x20 glyphs, 96 bytes a row line.
    pub ef12x20: &'static [u8],
}

impl crate::store::Load for Fonts {
    fn load(r: &mut crate::store::Reader) -> Self {
        Fonts {
            ef8x16: crate::store::Load::load(r),
            ef8x16_past: crate::store::Load::load(r),
            ef12x20: crate::store::Load::load(r),
        }
    }
}

impl Fonts {
    pub fn ef8x16(&self) -> &'static [u8] {
        self.ef8x16
    }
    pub fn ef8x16_past(&self) -> &'static [u8] {
        self.ef8x16_past
    }
    pub fn ef12x20(&self) -> &'static [u8] {
        self.ef12x20
    }
}

/// `ef8x16`: 8x16 glyphs, 16 a row, 64 bytes a row line.
pub static EF8X16: std::sync::LazyLock<&'static [u8]> = std::sync::LazyLock::new(|| shared().ef8x16);

/// `ef12x20`: 12x20 glyphs, 96 bytes a row line.
pub static EF12X20: std::sync::LazyLock<&'static [u8]> = std::sync::LazyLock::new(|| shared().ef12x20);

/// The volume's Fonts (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Fonts {
    static READ: [std::sync::OnceLock<&'static Fonts>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "fonts"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Fonts {
    static READ: std::sync::OnceLock<&'static Fonts> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("fonts"))
}
