// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/game.bin`, plans/build-data.md).

//! `ccGame`'s own tables (main).

use crate::volume::Volume;

/// The `game` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Game {
    /// `ccGame::ChangeScene`'s server of each town: Infection's `@1489`; the later volumes' ChangeScene sets the server to the town itself.
    pub town_server: &'static [i32],
}

impl crate::store::Load for Game {
    fn load(r: &mut crate::store::Reader) -> Self {
        Game { town_server: crate::store::Load::load(r) }
    }
}

impl Game {
    pub fn town_server(&self) -> &'static [i32] {
        self.town_server
    }
}

/// The volume's Game (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Game {
    static READ: [std::sync::OnceLock<&'static Game>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "game"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Game {
    static READ: std::sync::OnceLock<&'static Game> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("game"))
}
