// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/kanji.bin`, plans/build-data.md).

//! What `ccKanji` and the sprites draw text with (main): the ASCII glyphs' trims, the colours, the blends.

use crate::volume::Volume;

/// The `kanji` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Kanji {
    /// `englishFontOfsS`: each glyph's trim for kt 0 and 1.
    pub english_font_ofs_s: &'static [i16],
    /// The three halfwords past `englishFontOfsS`'s end, which %X-%Z read: the volume's next global.
    pub english_font_ofs_s_past: &'static [i16],
    /// `englishFontOfsL`: the same for kt 2 and 3.
    pub english_font_ofs_l: &'static [i16],
    /// The three halfwords past `englishFontOfsL`'s end (`englishFontOfsS`'s first three).
    pub english_font_ofs_l_past: &'static [i16],
    /// `ccSpriteColorTable`: the 24 RGBA colours the #R #G #B #Y escapes and the sprites index (0x80 = 1.0; each entry 8 bytes, the low four used).
    pub sprite_color_table: &'static [[u8; 4]],
    /// `alphaBlendTbl`: the nine ALPHA register values.
    pub alpha_blend_tbl: &'static [u64],
}

impl crate::store::Load for Kanji {
    fn load(r: &mut crate::store::Reader) -> Self {
        Kanji {
            english_font_ofs_s: crate::store::Load::load(r),
            english_font_ofs_s_past: crate::store::Load::load(r),
            english_font_ofs_l: crate::store::Load::load(r),
            english_font_ofs_l_past: crate::store::Load::load(r),
            sprite_color_table: crate::store::Load::load(r),
            alpha_blend_tbl: crate::store::Load::load(r),
        }
    }
}

impl Kanji {
    pub fn english_font_ofs_s(&self) -> &'static [i16] {
        self.english_font_ofs_s
    }
    pub fn english_font_ofs_s_past(&self) -> &'static [i16] {
        self.english_font_ofs_s_past
    }
    pub fn english_font_ofs_l(&self) -> &'static [i16] {
        self.english_font_ofs_l
    }
    pub fn english_font_ofs_l_past(&self) -> &'static [i16] {
        self.english_font_ofs_l_past
    }
    pub fn sprite_color_table(&self) -> &'static [[u8; 4]] {
        self.sprite_color_table
    }
    pub fn alpha_blend_tbl(&self) -> &'static [u64] {
        self.alpha_blend_tbl
    }
}

/// `englishFontOfsS`: each glyph's trim for kt 0 and 1.
pub static ENGLISH_FONT_OFS_S: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().english_font_ofs_s);

/// `englishFontOfsL`: the same for kt 2 and 3.
pub static ENGLISH_FONT_OFS_L: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().english_font_ofs_l);

/// The three halfwords past `englishFontOfsL`'s end (`englishFontOfsS`'s first three).
pub static ENGLISH_FONT_OFS_L_PAST: std::sync::LazyLock<&'static [i16]> =
    std::sync::LazyLock::new(|| shared().english_font_ofs_l_past);

/// `ccSpriteColorTable`: the 24 RGBA colours the #R #G #B #Y escapes and the sprites index (0x80 = 1.0; each entry 8 bytes, the low four used).
pub static SPRITE_COLOR_TABLE: std::sync::LazyLock<&'static [[u8; 4]]> =
    std::sync::LazyLock::new(|| shared().sprite_color_table);

/// `alphaBlendTbl`: the nine ALPHA register values.
pub static ALPHA_BLEND_TBL: std::sync::LazyLock<&'static [u64]> = std::sync::LazyLock::new(|| shared().alpha_blend_tbl);

/// The volume's Kanji (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Kanji {
    static READ: [std::sync::OnceLock<&'static Kanji>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "kanji"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Kanji {
    static READ: std::sync::OnceLock<&'static Kanji> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("kanji"))
}
