// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/loaddisp.bin`, plans/build-data.md).

//! The loading display's words (`ccLoadDisp`): the towns' cards, the servers' symbols.

use crate::volume::Volume;
use crate::world::{Server, Town};

/// A town's loading card: its two lines (`townNameTbl`'s first two `char *`; the display does not read the third).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TownCard {
    pub name: &'static str,
    pub sub: &'static str,
}

impl crate::store::Load for TownCard {
    fn load(r: &mut crate::store::Reader) -> Self {
        TownCard { name: crate::store::Load::load(r), sub: crate::store::Load::load(r) }
    }
}

/// The `loaddisp` group's values for a volume, from the build.
#[derive(Debug)]
pub struct LoadDisp {
    /// `townNameTbl` (main 0x00311730): the town's loading card.
    pub card: &'static [TownCard],
    /// `serverNameTbl` (0x00311770): the server's symbol (Shift-JIS).
    pub symbol: &'static [&'static str],
    /// "Server" (0x00353f98), after the symbol.
    pub server: &'static str,
}

impl crate::store::Load for LoadDisp {
    fn load(r: &mut crate::store::Reader) -> Self {
        LoadDisp {
            card: crate::store::Load::load(r),
            symbol: crate::store::Load::load(r),
            server: crate::store::Load::load(r),
        }
    }
}

impl LoadDisp {
    pub fn server(&self) -> &'static str {
        self.server
    }
}

/// "Server" (0x00353f98), after the symbol.
pub static SERVER: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().server);

impl Town {
    /// `townNameTbl` (main 0x00311730): the town's loading card.
    pub fn card(self) -> TownCard {
        let k = match self {
            Town::MacAnu => 0,
            Town::DunLoireag => 1,
            Town::CarminaGadelica => 2,
            Town::FortOuph => 3,
            Town::LiaFail => 4,
        };
        shared().card[k]
    }
}

impl Server {
    /// `serverNameTbl` (0x00311770): the server's symbol (Shift-JIS).
    pub fn symbol(self) -> &'static str {
        let k = match self {
            Server::Delta => 0,
            Server::Theta => 1,
            Server::Lambda => 2,
            Server::Sigma => 3,
            Server::Omega => 4,
        };
        shared().symbol[k]
    }
}

/// The volume's LoadDisp (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static LoadDisp {
    static READ: [std::sync::OnceLock<&'static LoadDisp>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "loaddisp"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static LoadDisp {
    static READ: std::sync::OnceLock<&'static LoadDisp> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("loaddisp"))
}
