// Generated by piney-gen - do not edit.

//! The engine's tables out of each volume's executable, generated by
//! `piney-gen` from its manifest (`crates/piney-gen/src/manifest.rs`;
//! `plans/volumes.md`, "The generator"). Each module is one group:
//! `of(volume)` gives that volume's.

// A float near a constant (1.414214) is the game's number, not the
// constant; an offset keeps its form (`0x0 + i * 0x4`) as the layout has it.
#![allow(clippy::approx_constant, clippy::identity_op)]

pub mod battle;
pub mod combat;
pub mod desktop;
pub mod dtmenu;
pub mod effect;
pub mod fieldui;
pub mod fonts;
pub mod game;
pub mod kanji;
pub mod loaddisp;
pub mod mail;
pub mod nameentry;
pub mod newgame;
pub mod party_chat;
pub mod sjis;
pub mod staffroll;
pub mod stream;
pub mod talk;
pub mod title;
pub mod toppage;
pub mod types;
pub mod voice;
pub mod world;
