// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/newgame.bin`, plans/build-data.md).

//! What `ccSaveData::NewGame` copies from the disc: `charTbl` and the default trade lists.

pub use super::types::{
    Attribute, BattleAbility, CharBaseParam, CharParamElement, Equipment, ItemList, SpcParamData, Tolerance, TradeList,
};
use crate::volume::Volume;

/// The `newgame` group's values for a volume, from the build.
#[derive(Debug)]
pub struct NewGame {
    /// `charTbl` (demo.prg; main from Outbreak on): 18 characters, 21 from Mutation on.
    pub chars: &'static [SpcParamData],
    /// `spcDefTradeList`: characters 1-17 (1-20 from Mutation on), each its trades (up to 16; the rest are empty).
    pub spc_trade: &'static [&'static [TradeList]],
    /// `npcDefTradeList`: 48 NPCs (54 from Mutation on), each its trades (up to 16).
    pub npc_trade: &'static [&'static [TradeList]],
    /// `tpcTradeList`: per town PC, three lists of four items.
    pub tpc_trade: &'static [[[ItemList; 4]; 3]],
    /// Where `spcNameList` (`char[17][24]`) is: the address the save's name pointers hold.
    pub spc_name_list: u32,
    /// Where `ccsNameList` (`char[n][32]`) is.
    pub ccs_name_list: u32,
}

impl crate::store::Load for NewGame {
    fn load(r: &mut crate::store::Reader) -> Self {
        NewGame {
            chars: crate::store::Load::load(r),
            spc_trade: crate::store::Load::load(r),
            npc_trade: crate::store::Load::load(r),
            tpc_trade: crate::store::Load::load(r),
            spc_name_list: crate::store::Load::load(r),
            ccs_name_list: crate::store::Load::load(r),
        }
    }
}

impl NewGame {
    pub fn chars(&self) -> &'static [SpcParamData] {
        self.chars
    }
    pub fn spc_trade(&self) -> &'static [&'static [TradeList]] {
        self.spc_trade
    }
    pub fn npc_trade(&self) -> &'static [&'static [TradeList]] {
        self.npc_trade
    }
    pub fn tpc_trade(&self) -> &'static [[[ItemList; 4]; 3]] {
        self.tpc_trade
    }
    pub fn spc_name_list(&self) -> u32 {
        self.spc_name_list
    }
    pub fn ccs_name_list(&self) -> u32 {
        self.ccs_name_list
    }
}

/// The volume's NewGame (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static NewGame {
    static READ: [std::sync::OnceLock<&'static NewGame>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "newgame"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static NewGame {
    static READ: std::sync::OnceLock<&'static NewGame> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("newgame"))
}
