// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/race.bin`, plans/build-data.md).

//! The Flag Race's tables (Mutation on; found through its code).

use crate::volume::Volume;

/// A prize: the item's category and id.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RacePrize {
    pub id: i16,
    pub cat: i8,
}

impl crate::store::Load for RacePrize {
    fn load(r: &mut crate::store::Reader) -> Self {
        RacePrize { id: crate::store::Load::load(r), cat: crate::store::Load::load(r) }
    }
}

/// The `race` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Race {
    /// Kite's start by server (MUT 0x006d80e0).
    pub kite_pos: &'static [[f32; 4]],
    /// His heading there, 16-bit angles (0x006d8130).
    pub kite_rot: &'static [i16],
    /// The ride's top speed, acceleration and easings by kind 1-8 (0x006d8330).
    pub ride_kind: &'static [[f32; 4]],
    /// Kind 0's by server (0x006d83c0).
    pub ride_server: &'static [[f32; 4]],
    /// The intro's camera by kind (0x006d84a0).
    pub intro_pos_kind: &'static [[f32; 4]],
    /// Where it looks (0x006d8410).
    pub intro_view_kind: &'static [[f32; 4]],
    /// Kind 0's by server (0x006d8580).
    pub intro_pos_server: &'static [[f32; 4]],
    /// Where it looks (0x006d8530).
    pub intro_view_server: &'static [[f32; 4]],
    /// The countdown's height by server (0x006d8280).
    pub count_height: &'static [f32],
    /// Kite's place after the race by server (0x006d82c0).
    pub end_pos: &'static [[f32; 4]],
    /// The Grunty at the finish by server (0x006d8140).
    pub ride_end_pos: &'static [[f32; 4]],
    /// Its heading there (0x006d8190).
    pub ride_end_rot: &'static [[f32; 4]],
    /// The finish's camera by server (0x006d81e0).
    pub finish_cam_pos: &'static [[f32; 4]],
    /// Where it looks (0x006d8230).
    pub finish_cam_view: &'static [[f32; 4]],
    /// The result's height by server (0x006d82a0).
    pub cup_height: &'static [f32],
    /// The cup's clip by rank (0x006d8310).
    pub cup_anms: &'static [&'static str],
    /// The place's clip by rank (0x006d8320).
    pub place_anms: &'static [&'static str],
    /// The timer's eight cells (0x006d85d0).
    pub timer_cells: &'static [[i32; 2]],
    /// The flags' marker dummies by town (0x006d80b0).
    pub flag_markers: &'static [Option<[&'static str; 3]>],
    /// Each flag's palette, none for the first (0x006d80c8).
    pub flag_cluts: &'static [Option<&'static str>],
    /// Where the chosen Grunty walks by kind (0x0061ce80).
    pub walk_kind: &'static [[f32; 4]],
    /// Kind 0's by server (0x0061ce30).
    pub walk_server: &'static [[f32; 4]],
    /// The prizes by server 1-4 and result 0-4 (0x00682230).
    pub prizes: &'static [[RacePrize; 5]],
    /// What is given once a rank's three are gone (0x00682280).
    pub prizes_gone: &'static [[RacePrize; 5]],
    /// The wallpapers: the Grand Slam's, then each server's first place (0x006822d0).
    pub wallpapers: &'static [i16],
    /// Flag Race's greeting record (0x00660b90).
    pub greet_va: u32,
    /// Its results' records, nine (0x00660cc0).
    pub results_va: u32,
    /// The breeder's Talk once the race is offered (0x00660b40).
    pub talk_va: u32,
}

impl crate::store::Load for Race {
    fn load(r: &mut crate::store::Reader) -> Self {
        Race {
            kite_pos: crate::store::Load::load(r),
            kite_rot: crate::store::Load::load(r),
            ride_kind: crate::store::Load::load(r),
            ride_server: crate::store::Load::load(r),
            intro_pos_kind: crate::store::Load::load(r),
            intro_view_kind: crate::store::Load::load(r),
            intro_pos_server: crate::store::Load::load(r),
            intro_view_server: crate::store::Load::load(r),
            count_height: crate::store::Load::load(r),
            end_pos: crate::store::Load::load(r),
            ride_end_pos: crate::store::Load::load(r),
            ride_end_rot: crate::store::Load::load(r),
            finish_cam_pos: crate::store::Load::load(r),
            finish_cam_view: crate::store::Load::load(r),
            cup_height: crate::store::Load::load(r),
            cup_anms: crate::store::Load::load(r),
            place_anms: crate::store::Load::load(r),
            timer_cells: crate::store::Load::load(r),
            flag_markers: crate::store::Load::load(r),
            flag_cluts: crate::store::Load::load(r),
            walk_kind: crate::store::Load::load(r),
            walk_server: crate::store::Load::load(r),
            prizes: crate::store::Load::load(r),
            prizes_gone: crate::store::Load::load(r),
            wallpapers: crate::store::Load::load(r),
            greet_va: crate::store::Load::load(r),
            results_va: crate::store::Load::load(r),
            talk_va: crate::store::Load::load(r),
        }
    }
}

impl Race {
    pub fn kite_pos(&self) -> &'static [[f32; 4]] {
        self.kite_pos
    }
    pub fn kite_rot(&self) -> &'static [i16] {
        self.kite_rot
    }
    pub fn ride_kind(&self) -> &'static [[f32; 4]] {
        self.ride_kind
    }
    pub fn ride_server(&self) -> &'static [[f32; 4]] {
        self.ride_server
    }
    pub fn intro_pos_kind(&self) -> &'static [[f32; 4]] {
        self.intro_pos_kind
    }
    pub fn intro_view_kind(&self) -> &'static [[f32; 4]] {
        self.intro_view_kind
    }
    pub fn intro_pos_server(&self) -> &'static [[f32; 4]] {
        self.intro_pos_server
    }
    pub fn intro_view_server(&self) -> &'static [[f32; 4]] {
        self.intro_view_server
    }
    pub fn count_height(&self) -> &'static [f32] {
        self.count_height
    }
    pub fn end_pos(&self) -> &'static [[f32; 4]] {
        self.end_pos
    }
    pub fn ride_end_pos(&self) -> &'static [[f32; 4]] {
        self.ride_end_pos
    }
    pub fn ride_end_rot(&self) -> &'static [[f32; 4]] {
        self.ride_end_rot
    }
    pub fn finish_cam_pos(&self) -> &'static [[f32; 4]] {
        self.finish_cam_pos
    }
    pub fn finish_cam_view(&self) -> &'static [[f32; 4]] {
        self.finish_cam_view
    }
    pub fn cup_height(&self) -> &'static [f32] {
        self.cup_height
    }
    pub fn cup_anms(&self) -> &'static [&'static str] {
        self.cup_anms
    }
    pub fn place_anms(&self) -> &'static [&'static str] {
        self.place_anms
    }
    pub fn timer_cells(&self) -> &'static [[i32; 2]] {
        self.timer_cells
    }
    pub fn flag_markers(&self) -> &'static [Option<[&'static str; 3]>] {
        self.flag_markers
    }
    pub fn flag_cluts(&self) -> &'static [Option<&'static str>] {
        self.flag_cluts
    }
    pub fn walk_kind(&self) -> &'static [[f32; 4]] {
        self.walk_kind
    }
    pub fn walk_server(&self) -> &'static [[f32; 4]] {
        self.walk_server
    }
    pub fn prizes(&self) -> &'static [[RacePrize; 5]] {
        self.prizes
    }
    pub fn prizes_gone(&self) -> &'static [[RacePrize; 5]] {
        self.prizes_gone
    }
    pub fn wallpapers(&self) -> &'static [i16] {
        self.wallpapers
    }
    pub fn greet_va(&self) -> u32 {
        self.greet_va
    }
    pub fn results_va(&self) -> u32 {
        self.results_va
    }
    pub fn talk_va(&self) -> u32 {
        self.talk_va
    }
}

/// The volume's Race (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Race {
    static READ: [std::sync::OnceLock<&'static Race>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "race"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Race {
    static READ: std::sync::OnceLock<&'static Race> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("race"))
}
