// Generated by piney-gen from the four discs' executables - do not edit.

//! The Event NPC's Item List (menu 91; Mutation on; found through its code).

use crate::volume::Volume;

/// A group's page count (`lh` of a word).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ItemListPages {
    pub n: i16,
}

impl crate::store::Load for ItemListPages {
    fn load(r: &mut crate::store::Reader) -> Self {
        ItemListPages { n: crate::store::Load::load(r) }
    }
}

const PAGES: &[ItemListPages] =
    &[ItemListPages { n: 6 }, ItemListPages { n: 4 }, ItemListPages { n: 3 }, ItemListPages { n: 2 }];

const CATS_2: [i32; 6] = [-2, 11, 14, -1, -1, -1];

const CATS_3: [i32; 6] = [-3, -4, -1, -1, -1, -1];

const CATS: &[[i32; 6]] = &[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, -1, -1], CATS_2, CATS_3];

/// What differs between the volumes in the manifest's `registry` group;
/// what they hold alike is the module's own items.
#[derive(Debug)]
pub struct Registry {
    /// The Event NPC's record once every item is in (MUT 0x00669d90).
    pub done_va: u32,
    /// Each group's page count (0x006822e0).
    pub pages: &'static [ItemListPages],
    /// Each group's pages' categories, -1 past them (0x006822f0).
    pub cats: &'static [[i32; 6]],
}

static INF: Registry = Registry { done_va: 0x00000000, pages: &[], cats: &[] };

static MUT: Registry = Registry { done_va: 0x00669d90, pages: PAGES, cats: CATS };

static OUT: Registry = Registry { done_va: 0x00668780, pages: PAGES, cats: CATS };

static QUA: Registry = Registry { done_va: 0x0055fb00, pages: PAGES, cats: CATS };

impl Registry {
    pub fn done_va(&self) -> u32 {
        self.done_va
    }
    pub fn pages(&self) -> &'static [ItemListPages] {
        self.pages
    }
    pub fn cats(&self) -> &'static [[i32; 6]] {
        self.cats
    }
}

/// The volume's Registry.
pub fn of(v: Volume) -> &'static Registry {
    match v {
        Volume::Inf => &INF,
        Volume::Mut => &MUT,
        Volume::Out => &OUT,
        Volume::Qua => &QUA,
    }
}
