// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/staffroll.bin`, plans/build-data.md).

//! The staff roll's pages (desktop.prg `g_srDataGrp`), its scene file and its timings.

pub use super::types::{SRData, SRDataGrp};
use crate::volume::Volume;

/// The `staffroll` group's values for a volume, from the build.
#[derive(Debug)]
pub struct StaffRoll {
    /// `g_srDataGrp`: the pages, each its credits (none for a picture alone) and picture; none on Quarantine, whose desktop has no staff roll.
    pub pages: &'static [SRDataGrp],
    /// `SR_CCS_NAME`: the volume's staff roll scene file (the table `ccThStaffRoll` indexes by `volumeNum - 1`); none on Quarantine.
    pub ccs: &'static str,
    /// `SR_RND_FADEIN_TIME`
    pub rnd_fadein: i32,
    /// `SR_RND_FADEOUT_TIME`
    pub rnd_fadeout: i32,
    /// `SR_BG_FIX_TIME`
    pub bg_fix: i32,
    /// `SR_BG_FADEIN_TIME`
    pub bg_fadein: i32,
    /// `SR_BG_FADEOUT_TIME`
    pub bg_fadeout: i32,
    /// `SR_ONLYBG_FADEIN_TIME`
    pub onlybg_fadein: i32,
    /// `SR_ONLYBG_FADEOUT_TIME`
    pub onlybg_fadeout: i32,
    /// `SR_ONLYBG_FIX_TIME`
    pub onlybg_fix: i32,
}

impl crate::store::Load for StaffRoll {
    fn load(r: &mut crate::store::Reader) -> Self {
        StaffRoll {
            pages: crate::store::Load::load(r),
            ccs: crate::store::Load::load(r),
            rnd_fadein: crate::store::Load::load(r),
            rnd_fadeout: crate::store::Load::load(r),
            bg_fix: crate::store::Load::load(r),
            bg_fadein: crate::store::Load::load(r),
            bg_fadeout: crate::store::Load::load(r),
            onlybg_fadein: crate::store::Load::load(r),
            onlybg_fadeout: crate::store::Load::load(r),
            onlybg_fix: crate::store::Load::load(r),
        }
    }
}

impl StaffRoll {
    pub fn pages(&self) -> &'static [SRDataGrp] {
        self.pages
    }
    pub fn ccs(&self) -> &'static str {
        self.ccs
    }
    pub fn rnd_fadein(&self) -> i32 {
        self.rnd_fadein
    }
    pub fn rnd_fadeout(&self) -> i32 {
        self.rnd_fadeout
    }
    pub fn bg_fix(&self) -> i32 {
        self.bg_fix
    }
    pub fn bg_fadein(&self) -> i32 {
        self.bg_fadein
    }
    pub fn bg_fadeout(&self) -> i32 {
        self.bg_fadeout
    }
    pub fn onlybg_fadein(&self) -> i32 {
        self.onlybg_fadein
    }
    pub fn onlybg_fadeout(&self) -> i32 {
        self.onlybg_fadeout
    }
    pub fn onlybg_fix(&self) -> i32 {
        self.onlybg_fix
    }
}

/// The volume's StaffRoll (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static StaffRoll {
    static READ: [std::sync::OnceLock<&'static StaffRoll>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "staffroll"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static StaffRoll {
    static READ: std::sync::OnceLock<&'static StaffRoll> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("staffroll"))
}
