// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/stream.bin`, plans/build-data.md).

//! What the in-engine streams read (main): each stream's files, its music changes, the gate hack's files, the subtitles, the stream effects' and the ending's tables.

pub use super::types::{
    CcsndStrBgm, EffPartParam0580, EvMsgData, GateHackOut, ObjPartParam0580, PartCreateParam, SndStrTbl, Streamdata,
};
use crate::volume::Volume;

/// An ending event entry (`ccEventObjTbl`): its cue, name and what it starts.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct EventObj {
    pub cue: u32,
    pub name: Option<&'static str>,
    pub eff: Option<EffPartParam0580>,
    pub rock: Option<ObjPartParam0580>,
}

impl crate::store::Load for EventObj {
    fn load(r: &mut crate::store::Reader) -> Self {
        EventObj {
            cue: crate::store::Load::load(r),
            name: crate::store::Load::load(r),
            eff: crate::store::Load::load(r),
            rock: crate::store::Load::load(r),
        }
    }
}

/// The `stream` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Stream {
    /// `streamTbl`: each stream's header record, then its files; none on Outbreak and Quarantine, whose `ccStreamInit` takes `streamTblE` whatever the voice.
    pub lists: &'static [Option<&'static [Streamdata]>],
    /// `streamTblE`: the same with English voices (`saveData.voice`).
    pub lists_e: &'static [Option<&'static [Streamdata]>],
    /// `strSndTbl`: per stream its BGM table (`strbgm`), up to and with its end record (`bgm1` below 0, `param` 5).
    pub bgm: &'static [SndStrTbl],
    /// `str7000TblPre`: the Chaos Gate movie's setup file.
    pub gate_pre: &'static [Streamdata],
    /// `str7000TblTown`: per town its setup file and departure scene.
    pub gate_town: &'static [[Streamdata; 2]],
    /// `str7000TblTownC`: the same in the crisis.
    pub gate_town_crisis: &'static [[Streamdata; 2]],
    /// `str7000TblAfter`: per arrival its setup file and scene.
    pub gate_after: &'static [[Streamdata; 2]],
    /// `str7000TblPreE`.
    pub gate_pre_e: &'static [Streamdata],
    /// `str7000TblTownE`.
    pub gate_town_e: &'static [[Streamdata; 2]],
    /// `str7000TblTownCE`.
    pub gate_town_crisis_e: &'static [[Streamdata; 2]],
    /// `str7000TblAfterE`.
    pub gate_after_e: &'static [[Streamdata; 2]],
    /// `str7000Out`: a field's arrival row, up to a negative field.
    pub gate_out: &'static [GateHackOut],
    /// `evStrMsgTbl`: each stream's subtitles, read on past its own records as the game's pointer walks (none for a stream without).
    pub subtitles: &'static [Option<&'static [EvMsgData]>],
    /// `evStrMsgTblp`: Parody Mode's.
    pub subtitles_parody: &'static [Option<&'static [EvMsgData]>],
    /// `hitRot0120a` (x, y, z degrees; three), read on to eight as the cues 610-614 do (the next data, the jump table's denormal floats, which the EE takes as 0).
    pub hit_rot_0120a: &'static [[f32; 3]],
    /// `hitRot0240` (seven), its eighth mark reading on into the next data.
    pub hit_rot_0240: &'static [[f32; 3]],
    /// `hitRot0250`: `Func_str0250`'s rotation.
    pub hit_rot_0250: [f32; 3],
    /// `hitRot0301`: `Func_str0301`'s rotation.
    pub hit_rot_0301: [f32; 3],
    /// `eventObjTbl_0580` read on through `eventObjTbl_0581`: the ending's cues.
    pub event_objs: &'static [EventObj],
    /// `rockScaleTbl`: a rock's scale by its model.
    pub rock_scale: [f32; 3],
    /// `eventObjTbl_0710` (MUT main 0x00366e30): the opening's (`Func_str0710`) cues, up to its end row; none on Infection.
    pub opening_events: &'static [EventObj],
    /// The opening's texts (`Func_str0710`'s cues 700 and 710), each normal then Parody Mode's; none on Infection.
    pub opening_text: [Option<&'static str>; 4],
    /// `Func_str0880`'s hit marks' rotations (MUT main 0x00366ed0: x, y, z degrees); none on Infection.
    pub hit_rot_0880: &'static [[f32; 3]],
}

impl crate::store::Load for Stream {
    fn load(r: &mut crate::store::Reader) -> Self {
        Stream {
            lists: crate::store::Load::load(r),
            lists_e: crate::store::Load::load(r),
            bgm: crate::store::Load::load(r),
            gate_pre: crate::store::Load::load(r),
            gate_town: crate::store::Load::load(r),
            gate_town_crisis: crate::store::Load::load(r),
            gate_after: crate::store::Load::load(r),
            gate_pre_e: crate::store::Load::load(r),
            gate_town_e: crate::store::Load::load(r),
            gate_town_crisis_e: crate::store::Load::load(r),
            gate_after_e: crate::store::Load::load(r),
            gate_out: crate::store::Load::load(r),
            subtitles: crate::store::Load::load(r),
            subtitles_parody: crate::store::Load::load(r),
            hit_rot_0120a: crate::store::Load::load(r),
            hit_rot_0240: crate::store::Load::load(r),
            hit_rot_0250: crate::store::Load::load(r),
            hit_rot_0301: crate::store::Load::load(r),
            event_objs: crate::store::Load::load(r),
            rock_scale: crate::store::Load::load(r),
            opening_events: crate::store::Load::load(r),
            opening_text: crate::store::Load::load(r),
            hit_rot_0880: crate::store::Load::load(r),
        }
    }
}

impl Stream {
    pub fn lists(&self) -> &'static [Option<&'static [Streamdata]>] {
        self.lists
    }
    pub fn lists_e(&self) -> &'static [Option<&'static [Streamdata]>] {
        self.lists_e
    }
    pub fn bgm(&self) -> &'static [SndStrTbl] {
        self.bgm
    }
    pub fn gate_pre(&self) -> &'static [Streamdata] {
        self.gate_pre
    }
    pub fn gate_town(&self) -> &'static [[Streamdata; 2]] {
        self.gate_town
    }
    pub fn gate_town_crisis(&self) -> &'static [[Streamdata; 2]] {
        self.gate_town_crisis
    }
    pub fn gate_after(&self) -> &'static [[Streamdata; 2]] {
        self.gate_after
    }
    pub fn gate_pre_e(&self) -> &'static [Streamdata] {
        self.gate_pre_e
    }
    pub fn gate_town_e(&self) -> &'static [[Streamdata; 2]] {
        self.gate_town_e
    }
    pub fn gate_town_crisis_e(&self) -> &'static [[Streamdata; 2]] {
        self.gate_town_crisis_e
    }
    pub fn gate_after_e(&self) -> &'static [[Streamdata; 2]] {
        self.gate_after_e
    }
    pub fn gate_out(&self) -> &'static [GateHackOut] {
        self.gate_out
    }
    pub fn subtitles(&self) -> &'static [Option<&'static [EvMsgData]>] {
        self.subtitles
    }
    pub fn subtitles_parody(&self) -> &'static [Option<&'static [EvMsgData]>] {
        self.subtitles_parody
    }
    pub fn hit_rot_0120a(&self) -> &'static [[f32; 3]] {
        self.hit_rot_0120a
    }
    pub fn hit_rot_0240(&self) -> &'static [[f32; 3]] {
        self.hit_rot_0240
    }
    pub fn hit_rot_0250(&self) -> [f32; 3] {
        self.hit_rot_0250
    }
    pub fn hit_rot_0301(&self) -> [f32; 3] {
        self.hit_rot_0301
    }
    pub fn event_objs(&self) -> &'static [EventObj] {
        self.event_objs
    }
    pub fn rock_scale(&self) -> [f32; 3] {
        self.rock_scale
    }
    pub fn opening_events(&self) -> &'static [EventObj] {
        self.opening_events
    }
    pub fn opening_text(&self) -> [Option<&'static str>; 4] {
        self.opening_text
    }
    pub fn hit_rot_0880(&self) -> &'static [[f32; 3]] {
        self.hit_rot_0880
    }
}

/// `str7000Out`: a field's arrival row, up to a negative field.
pub static GATE_OUT: std::sync::LazyLock<&'static [GateHackOut]> = std::sync::LazyLock::new(|| shared().gate_out);

/// `hitRot0240` (seven), its eighth mark reading on into the next data.
pub static HIT_ROT_0240: std::sync::LazyLock<&'static [[f32; 3]]> = std::sync::LazyLock::new(|| shared().hit_rot_0240);

/// `hitRot0250`: `Func_str0250`'s rotation.
pub static HIT_ROT_0250: std::sync::LazyLock<[f32; 3]> = std::sync::LazyLock::new(|| shared().hit_rot_0250);

/// `hitRot0301`: `Func_str0301`'s rotation.
pub static HIT_ROT_0301: std::sync::LazyLock<[f32; 3]> = std::sync::LazyLock::new(|| shared().hit_rot_0301);

/// `eventObjTbl_0580` read on through `eventObjTbl_0581`: the ending's cues.
pub static EVENT_OBJS: std::sync::LazyLock<&'static [EventObj]> = std::sync::LazyLock::new(|| shared().event_objs);

/// `rockScaleTbl`: a rock's scale by its model.
pub static ROCK_SCALE: std::sync::LazyLock<[f32; 3]> = std::sync::LazyLock::new(|| shared().rock_scale);

/// The volume's Stream (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Stream {
    static READ: [std::sync::OnceLock<&'static Stream>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "stream"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Stream {
    static READ: std::sync::OnceLock<&'static Stream> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("stream"))
}
