// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/talk.bin`, plans/build-data.md).

//! The records the talk pages reach through the addresses the game keeps (`npcTbl`, the save, `spcMsgTbl`).

pub use super::types::EvMsgData;
use crate::volume::Volume;

/// Where a record's name and text are: the addresses it holds.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RecordVa {
    pub name: u32,
    pub str: u32,
}

impl crate::store::Load for RecordVa {
    fn load(r: &mut crate::store::Reader) -> Self {
        RecordVa { name: crate::store::Load::load(r), str: crate::store::Load::load(r) }
    }
}

/// A record array (`ccEvMsgData[]`), where the volume keeps it, and the addresses its records hold (a table read as text shows them).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MsgRecords {
    pub va: u32,
    pub records: &'static [EvMsgData],
    pub addresses: &'static [RecordVa],
}

impl crate::store::Load for MsgRecords {
    fn load(r: &mut crate::store::Reader) -> Self {
        MsgRecords {
            va: crate::store::Load::load(r),
            records: crate::store::Load::load(r),
            addresses: crate::store::Load::load(r),
        }
    }
}

/// A pointer table (`ccEvMsgData *[]` or `**[]`), its words the addresses it holds.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MsgPointers {
    pub va: u32,
    pub words: &'static [u32],
}

impl crate::store::Load for MsgPointers {
    fn load(r: &mut crate::store::Reader) -> Self {
        MsgPointers { va: crate::store::Load::load(r), words: crate::store::Load::load(r) }
    }
}

/// The `talk` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Talk {
    /// The record arrays, by address.
    pub records: &'static [MsgRecords],
    /// The pointer tables, by address.
    pub pointers: &'static [MsgPointers],
}

impl crate::store::Load for Talk {
    fn load(r: &mut crate::store::Reader) -> Self {
        Talk { records: crate::store::Load::load(r), pointers: crate::store::Load::load(r) }
    }
}

impl Talk {
    pub fn records(&self) -> &'static [MsgRecords] {
        self.records
    }
    pub fn pointers(&self) -> &'static [MsgPointers] {
        self.pointers
    }
}

/// The volume's Talk (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Talk {
    static READ: [std::sync::OnceLock<&'static Talk>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "talk"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Talk {
    static READ: std::sync::OnceLock<&'static Talk> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("talk"))
}
