// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/title.bin`, plans/build-data.md).

//! The title's texts: the save's time-idol ranks, the memory-card dialog's words and messages.

use crate::volume::Volume;

/// The `title` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Title {
    /// `timeIdolRankDefStr`: a name then a time for each of the five ranks.
    pub time_idol_rank: &'static [&'static str],
    /// `STR_YES`
    pub yes: &'static str,
    /// `STR_NO`
    pub no: &'static str,
    /// `STR_LV`
    pub lv: &'static str,
    /// `STR_ALLTIME`
    pub alltime: &'static str,
    /// `STR_NODETA`
    pub nodeta: &'static str,
    /// `STR_MEMORYCARD`
    pub memorycard: &'static str,
    /// `STR_SLOT1`
    pub slot1: &'static str,
    /// `STR_SLOT2`
    pub slot2: &'static str,
    /// `STR_DATA`
    pub data: &'static str,
    /// `STR_CLEAR`
    pub clear: &'static str,
    /// `STR_PARODY`
    pub parody: &'static str,
    /// demo.prg's highlight escape
    pub highlight: &'static str,
    /// demo.prg's volume label
    pub vol: &'static str,
    /// `saveSysMsg` by `result & 0xfff`: each message's first five pieces, None for none.
    pub save_sys_msg: &'static [Option<&'static [&'static str]>],
    /// `mcDirName`: each volume's save directory on the memory card, by `volumeNum - 1`, with its leading `/` (Infection names the later ones by placeholders).
    pub mc_dir_names: &'static [&'static str],
}

impl crate::store::Load for Title {
    fn load(r: &mut crate::store::Reader) -> Self {
        Title {
            time_idol_rank: crate::store::Load::load(r),
            yes: crate::store::Load::load(r),
            no: crate::store::Load::load(r),
            lv: crate::store::Load::load(r),
            alltime: crate::store::Load::load(r),
            nodeta: crate::store::Load::load(r),
            memorycard: crate::store::Load::load(r),
            slot1: crate::store::Load::load(r),
            slot2: crate::store::Load::load(r),
            data: crate::store::Load::load(r),
            clear: crate::store::Load::load(r),
            parody: crate::store::Load::load(r),
            highlight: crate::store::Load::load(r),
            vol: crate::store::Load::load(r),
            save_sys_msg: crate::store::Load::load(r),
            mc_dir_names: crate::store::Load::load(r),
        }
    }
}

impl Title {
    pub fn time_idol_rank(&self) -> &'static [&'static str] {
        self.time_idol_rank
    }
    pub fn yes(&self) -> &'static str {
        self.yes
    }
    pub fn no(&self) -> &'static str {
        self.no
    }
    pub fn lv(&self) -> &'static str {
        self.lv
    }
    pub fn alltime(&self) -> &'static str {
        self.alltime
    }
    pub fn nodeta(&self) -> &'static str {
        self.nodeta
    }
    pub fn memorycard(&self) -> &'static str {
        self.memorycard
    }
    pub fn slot1(&self) -> &'static str {
        self.slot1
    }
    pub fn slot2(&self) -> &'static str {
        self.slot2
    }
    pub fn data(&self) -> &'static str {
        self.data
    }
    pub fn clear(&self) -> &'static str {
        self.clear
    }
    pub fn parody(&self) -> &'static str {
        self.parody
    }
    pub fn highlight(&self) -> &'static str {
        self.highlight
    }
    pub fn vol(&self) -> &'static str {
        self.vol
    }
    pub fn save_sys_msg(&self) -> &'static [Option<&'static [&'static str]>] {
        self.save_sys_msg
    }
    pub fn mc_dir_names(&self) -> &'static [&'static str] {
        self.mc_dir_names
    }
}

/// `timeIdolRankDefStr`: a name then a time for each of the five ranks.
pub static TIME_IDOL_RANK: std::sync::LazyLock<&'static [&'static str]> =
    std::sync::LazyLock::new(|| shared().time_idol_rank);

/// `STR_YES`
pub static YES: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().yes);

/// `STR_NO`
pub static NO: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().no);

/// `STR_LV`
pub static LV: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().lv);

/// `STR_ALLTIME`
pub static ALLTIME: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().alltime);

/// `STR_NODETA`
pub static NODETA: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().nodeta);

/// `STR_MEMORYCARD`
pub static MEMORYCARD: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().memorycard);

/// `STR_SLOT1`
pub static SLOT1: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().slot1);

/// `STR_SLOT2`
pub static SLOT2: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().slot2);

/// `STR_DATA`
pub static DATA: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().data);

/// `STR_CLEAR`
pub static CLEAR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().clear);

/// `STR_PARODY`
pub static PARODY: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().parody);

/// demo.prg's highlight escape
pub static HIGHLIGHT: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().highlight);

/// demo.prg's volume label
pub static VOL: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().vol);

/// The volume's Title (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Title {
    static READ: [std::sync::OnceLock<&'static Title>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "title"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Title {
    static READ: std::sync::OnceLock<&'static Title> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("title"))
}
