// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/toppage.bin`, plans/build-data.md).

//! The top page's board (toppage.prg): its threads and posts, normal and parody, and its words.

pub use super::types::{BBSMsgList, BBSThreadList};
use crate::volume::Volume;

/// The `toppage` group's values for a volume, from the build.
#[derive(Debug)]
pub struct TopPage {
    /// `bbsThreadTbl`: the 63 threads, each its posts (`message` is the post's lines).
    pub threads: &'static [BBSThreadList],
    /// `bbsThreadTblP`: Parody Mode's.
    pub threads_parody: &'static [BBSThreadList],
    /// `@1088`: the idle animation by volume; `_ChangeMode` reads entry `volumeNum - 1`.
    pub neutral: &'static [&'static str],
    /// The writing page's label.
    pub new_msg: &'static str,
    /// The empty thread's line.
    pub no_msg: &'static str,
    /// A post's author label.
    pub author: &'static str,
    /// A post's time label.
    pub time: &'static str,
    /// The player's label.
    pub player: &'static str,
}

impl crate::store::Load for TopPage {
    fn load(r: &mut crate::store::Reader) -> Self {
        TopPage {
            threads: crate::store::Load::load(r),
            threads_parody: crate::store::Load::load(r),
            neutral: crate::store::Load::load(r),
            new_msg: crate::store::Load::load(r),
            no_msg: crate::store::Load::load(r),
            author: crate::store::Load::load(r),
            time: crate::store::Load::load(r),
            player: crate::store::Load::load(r),
        }
    }
}

impl TopPage {
    pub fn threads(&self) -> &'static [BBSThreadList] {
        self.threads
    }
    pub fn threads_parody(&self) -> &'static [BBSThreadList] {
        self.threads_parody
    }
    pub fn neutral(&self) -> &'static [&'static str] {
        self.neutral
    }
    pub fn new_msg(&self) -> &'static str {
        self.new_msg
    }
    pub fn no_msg(&self) -> &'static str {
        self.no_msg
    }
    pub fn author(&self) -> &'static str {
        self.author
    }
    pub fn time(&self) -> &'static str {
        self.time
    }
    pub fn player(&self) -> &'static str {
        self.player
    }
}

/// `@1088`: the idle animation by volume; `_ChangeMode` reads entry `volumeNum - 1`.
pub static NEUTRAL: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().neutral);

/// The writing page's label.
pub static NEW_MSG: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().new_msg);

/// The empty thread's line.
pub static NO_MSG: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().no_msg);

/// A post's author label.
pub static AUTHOR: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().author);

/// A post's time label.
pub static TIME: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().time);

/// The player's label.
pub static PLAYER: std::sync::LazyLock<&'static str> = std::sync::LazyLock::new(|| shared().player);

/// The volume's TopPage (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static TopPage {
    static READ: [std::sync::OnceLock<&'static TopPage>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "toppage"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static TopPage {
    static READ: std::sync::OnceLock<&'static TopPage> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("toppage"))
}
