// Generated by piney-gen - do not edit. The values are in the build
// (`PINEY/TABLES/voice.bin`, plans/build-data.md).

//! The event voices (sndlib.cpp, main): the voice files and `ccEvVoiceRequest`'s tables.

pub use super::types::VoiceData;
use crate::volume::Volume;

/// A table `ccEvVoiceRequest` picks: its `voiceFile`, then per event (from its first) the rows by message; `en` where the code takes another table when `saveData.voice` is set.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VoiceBranch {
    pub file: i32,
    pub jp: &'static [Option<&'static [VoiceData]>],
    pub en: Option<&'static [Option<&'static [VoiceData]>]>,
}

impl crate::store::Load for VoiceBranch {
    fn load(r: &mut crate::store::Reader) -> Self {
        VoiceBranch {
            file: crate::store::Load::load(r),
            jp: crate::store::Load::load(r),
            en: crate::store::Load::load(r),
        }
    }
}

/// A hundred of events in `ccEvVoiceRequest`: the main events' table, the side events', Parody Mode's for the main events.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VoiceSection {
    pub main: Option<VoiceBranch>,
    pub side: Option<VoiceBranch>,
    pub parody: Option<VoiceBranch>,
}

impl crate::store::Load for VoiceSection {
    fn load(r: &mut crate::store::Reader) -> Self {
        VoiceSection {
            main: crate::store::Load::load(r),
            side: crate::store::Load::load(r),
            parody: crate::store::Load::load(r),
        }
    }
}

/// A field voice table: the file it sets (`voiceFile`), its rows by message, and the English rows (`saveData.voice`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VoiceTable {
    pub file: i32,
    pub jp: &'static [VoiceData],
    pub en: &'static [VoiceData],
}

impl crate::store::Load for VoiceTable {
    fn load(r: &mut crate::store::Reader) -> Self {
        VoiceTable {
            file: crate::store::Load::load(r),
            jp: crate::store::Load::load(r),
            en: crate::store::Load::load(r),
        }
    }
}

/// English messages `first..end` another file plays while `talkNum[talk]` is set: row `msg + add` of `rows` from file `file` (Mutation's `MIAE.BIN`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VoiceAlt {
    pub first: i32,
    pub end: i32,
    pub talk: i32,
    pub add: i32,
    pub file: i32,
    pub rows: &'static [VoiceData],
}

impl crate::store::Load for VoiceAlt {
    fn load(r: &mut crate::store::Reader) -> Self {
        VoiceAlt {
            first: crate::store::Load::load(r),
            end: crate::store::Load::load(r),
            talk: crate::store::Load::load(r),
            add: crate::store::Load::load(r),
            file: crate::store::Load::load(r),
            rows: crate::store::Load::load(r),
        }
    }
}

/// One of `ccVoiceRequest`'s cases: its group (the event number below -1), its table, and an alternative for some English rows.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldVoice {
    pub group: i32,
    pub table: VoiceTable,
    pub alt: Option<VoiceAlt>,
}

impl crate::store::Load for FieldVoice {
    fn load(r: &mut crate::store::Reader) -> Self {
        FieldVoice {
            group: crate::store::Load::load(r),
            table: crate::store::Load::load(r),
            alt: crate::store::Load::load(r),
        }
    }
}

/// One language's skill words for a character: the file, and its rows by `skillVoicePlay`'s row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SkillWords {
    pub file: &'static str,
    pub rows: &'static [VoiceData],
}

impl crate::store::Load for SkillWords {
    fn load(r: &mut crate::store::Reader) -> Self {
        SkillWords { file: crate::store::Load::load(r), rows: crate::store::Load::load(r) }
    }
}

/// A character's skill words, Japanese (`spcVoiceData`, `voiceData`) and English (`spcVoiceDataE`, `voiceDataE`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SkillVoice {
    pub jp: SkillWords,
    pub en: SkillWords,
}

impl crate::store::Load for SkillVoice {
    fn load(r: &mut crate::store::Reader) -> Self {
        SkillVoice { jp: crate::store::Load::load(r), en: crate::store::Load::load(r) }
    }
}

/// The `voice` group's values for a volume, from the build.
#[derive(Debug)]
pub struct Voice {
    /// `evVoiceFile`: the voice files by `voiceFile`, as paths on the disc (`VOICE/EVVOL1.BIN`; the IOP opens `cdrom0:\VOICE\EVVOL1.BIN`).
    pub files: &'static [&'static str],
    /// `evVoiceFileE`: the same in `VOICE_E`; from Mutation on one more, `MIAE.BIN` (20).
    pub files_e: &'static [&'static str],
    /// `ccEvVoiceRequest`'s tables by `event / 100`, as the volume's code picks them.
    pub events: &'static [VoiceSection],
    /// `ccVoiceRequest`'s groups, the field's voices (the Grunties, the fountain, party members joining and leaving, their talk and presents, the dogs, Fidchell), as the volume's code builds them.
    pub field: &'static [FieldVoice],
    /// `ccVoicePgFood`'s table: a Grunty food calling out.
    pub food: VoiceTable,
    /// `skillVoicePlay`'s tables by `charTbl` row, for the characters with a file.
    pub skill: &'static [SkillVoice],
}

impl crate::store::Load for Voice {
    fn load(r: &mut crate::store::Reader) -> Self {
        Voice {
            files: crate::store::Load::load(r),
            files_e: crate::store::Load::load(r),
            events: crate::store::Load::load(r),
            field: crate::store::Load::load(r),
            food: crate::store::Load::load(r),
            skill: crate::store::Load::load(r),
        }
    }
}

impl Voice {
    pub fn files(&self) -> &'static [&'static str] {
        self.files
    }
    pub fn files_e(&self) -> &'static [&'static str] {
        self.files_e
    }
    pub fn events(&self) -> &'static [VoiceSection] {
        self.events
    }
    pub fn field(&self) -> &'static [FieldVoice] {
        self.field
    }
    pub fn food(&self) -> VoiceTable {
        self.food
    }
    pub fn skill(&self) -> &'static [SkillVoice] {
        self.skill
    }
}

/// `evVoiceFile`: the voice files by `voiceFile`, as paths on the disc (`VOICE/EVVOL1.BIN`; the IOP opens `cdrom0:\VOICE\EVVOL1.BIN`).
pub static FILES: std::sync::LazyLock<&'static [&'static str]> = std::sync::LazyLock::new(|| shared().files);

/// `ccVoicePgFood`'s table: a Grunty food calling out.
pub static FOOD: std::sync::LazyLock<VoiceTable> = std::sync::LazyLock::new(|| shared().food);

/// The volume's Voice (read once a run; kept here per volume).
pub fn of(v: Volume) -> &'static Voice {
    static READ: [std::sync::OnceLock<&'static Voice>; 4] = [const { std::sync::OnceLock::new() }; 4];
    READ[v as usize].get_or_init(|| crate::store::group(v, "voice"))
}

/// The values every volume has alike, from whichever volume's can be had.
#[allow(dead_code)]
fn shared() -> &'static Voice {
    static READ: std::sync::OnceLock<&'static Voice> = std::sync::OnceLock::new();
    READ.get_or_init(|| crate::store::shared("voice"))
}
