#!/usr/bin/env python3
"""The Chaos Gate keyword system - see docs/engine/area-words.md.

    tools/areas.py words  ELF                      every keyword and its attributes
    tools/areas.py events ELF [--server N]         the fixed story areas
    tools/areas.py gen    ELF A B C [--server N] [--volume N] [--flag71]
                          [--floor N]              the area three words make,
                                                   and the enemies it registers

Words are given as text ("Bursting") or as an ID. `gen` reproduces
WORLD_MAN::SimGenerateCode (0x0019e5c0) step for step: a seed from the three
word IDs, random defaults from the game's RNG, then each attribute taken from
the highest-priority word that sets it, then the story-area overrides.
Everything is read from the executable given, so it works on all four
volumes (the stripped ones through the names piney-gen syms carries);
`--volume` defaults to that executable's own `volumeNum`.

Enemies follow ccRegisterDifficultyEnemy (0x001b7020) and ccRegisterEnemyList
(gcmn 0x0042ed70): a list type from the field type and weather (or 6 for a
story area), a rank `25 * (areaLevel - 1) + 10 + enemyOfs` (a story area's own
`enemy` value instead, when set; plus floor + 1 in a dungeon), and the three
entries of ccEnemyListInfo[server][type] starting at that rank.
"""

import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from image import Program  # noqa: E402

FIELDS = ("ID", "pri", "fieldType", "dungeonSize", "weather", "ground", "object",
          "areaLevel", "enemyOfs", "itemOfs", "circleOfs")
UNSET = 255   # "this word says nothing about this field"; dungeonSize uses 0
SERVERS = {0: "Delta", 1: "Theta", 2: "Lambda", 3: "Sigma", 4: "Omega"}

# WORLD_MAN::GetFieldAttrb (0x001a3830): enemy list type by [fieldType][weather].
# Generated by running the function in tools/eemu.py for every input;
# tools/test_areas.py re-derives it.
FIELD_ATTRIB = [
    [2] * 10, [2] * 10, [2] * 10, [2] * 10,
    [3, 3, 3, 3, 3, 3, 4, 4, 4, 4],
    [1] * 10, [1] * 10, [0] * 10,
    [5, 5, 5, 5, 5, 5, 4, 4, 4, 4],
    [3, 3, 3, 3, 1, 1, 4, 4, 4, 4],
    [3, 3, 3, 3, 5, 5, 4, 4, 4, 4],
]
ENEMY_RANGE = 3          # ccInitRegisterEnemy, gcmn 0x0042e8b4
STORY_LIST_TYPE = 6


class Word:
    __slots__ = ("text", "slot", "group") + FIELDS

    def copy(self):
        w = Word()
        for k in self.__slots__:
            setattr(w, k, getattr(self, k))
        return w


class Data:
    def __init__(self, elf_path):
        p = self.p = Program(elf_path)
        self.words = []
        for group in "1234":
            for slot in "abc":
                sym = p.symbol_named(f"word_{slot}{group}")
                for i in range(sym.size // 0x30):
                    raw = p.read(sym.value + 0x30 * i, 0x30)
                    vals = struct.unpack("<I11i", raw)
                    w = Word()
                    w.text = self.cstr(vals[0])
                    w.slot = "abc".index(slot)
                    w.group = int(group)
                    for k, v in zip(FIELDS, vals[1:]):
                        setattr(w, k, v)
                    self.words.append(w)
        sym = p.symbol_named("dungeonData")
        self.dungeon = [struct.unpack("<ii", p.read(sym.value + 8 * i, 8))
                        for i in range(sym.size // 8)]
        num = p.u32(p.symbol_named("eventAreaInfoNum").value)
        base = p.symbol_named("eventAreaInfo").value
        self.events = [self.event_at(base + 0x54 * i) for i in range(num)]
        self.volume = p.u32(p.symbol_named("volumeNum").value)
        self.substitutes = self.find_substitutes()

    def event_at(self, va):
        v = struct.unpack("<i3I9i8i", self.p.read(va, 0x54))
        return {"code": v[0], "wordA": self.cstr(v[1]), "wordB": self.cstr(v[2]),
                "wordC": self.cstr(v[3]), "server": v[4], "circle": v[5],
                "enemy": v[6], "item": v[7], "model": v[8], "flag": v[9],
                "type": v[10], "bgnum": v[11], "dungeonNum": v[12],
                "protect": list(v[13:21]), "has_words": bool(v[1])}

    def find_substitutes(self):
        """{event code: EVENTAREA_INFO} for the records ccGetEventAreaInfo
        returns in place of the table's. From Mutation on, the two special
        cases Infection writes inline in SimGenerateCode (events 71 and 47)
        are substitute records returned by that function (and by
        WORLD_MAN::GetEventAreaInfo): `li $v1, CODE`, a condition, then the
        substitute's address built in $v0. Infection's has none."""
        f = self.p.symbol_named("ccGetEventAreaInfo__Fi")
        words = struct.unpack(f"<{f.size // 4}I", self.p.read(f.value, f.size // 4 * 4))
        out = {}
        code = None
        hi = {}
        for w in words:
            op, rs, rt, imm = w >> 26, (w >> 21) & 31, (w >> 16) & 31, w & 0xFFFF
            if op == 0x09 and rs == 0 and rt == 3:
                code = imm
            elif op == 0x0F:
                hi[rt] = imm << 16
            elif op == 0x09 and rt == 2 and rs in hi and code is not None:
                va = (hi[rs] + (imm - 0x10000 if imm & 0x8000 else imm)) & 0xFFFFFFFF
                out[code] = self.event_at(va)
                code = None
        return out

    def event_info(self, code, volume, flag71=False):
        """The EVENTAREA_INFO the game uses for story area `code`: the
        substitute for event 71 when the save flag (saveData+0x5bc0 bit 62) is
        set and for event 47 from volume 3, where the executable has them;
        otherwise the table's."""
        sub = self.substitutes.get(code)
        if sub and ((code == 71 and flag71) or (code == 47 and volume >= 3)):
            return sub
        return next((e for e in self.events if e["code"] == code), None)

    def cstr(self, va):
        return self.p.cstr(va).decode("shift_jis", "replace") if va else ""

    def enemy_lists(self):
        """ccEnemyListInfo[server][type] -> list of enemyTbl indexes, and the
        enemy names; from the gcmn overlay."""
        if getattr(self, "_lists", None) is None:
            g = Program(self.p.elf.path, "gcmn")
            info = g.symbol_named("ccEnemyListInfo").value
            self._lists = []
            for server in range(5):
                row = []
                for t in range(7):
                    lst, num = struct.unpack("<Ii", g.read(info + 56 * server + 8 * t, 8))
                    row.append(list(struct.unpack(f"<{num}i", g.read(lst, 4 * num))))
                self._lists.append(row)
            tbl = g.symbol_named("enemyTbl")
            self._names = []
            for i in range(tbl.size // 448):
                name = struct.unpack("<I", g.read(tbl.value + 448 * i, 4))[0]
                self._names.append(g.cstr(name).decode("shift_jis", "replace") if name else "")
        return self._lists, self._names

    def find(self, slot, key):
        """GetWordParamPtr(slot, id): search groups 1..4 of one slot."""
        for w in self.words:
            if w.slot != slot:
                continue
            if (isinstance(key, int) and w.ID == key) or w.text.strip() == str(key).strip():
                return w
        raise SystemExit(f"no word {key!r} in slot {'abc'[slot]}")


class Rng:
    """seed = (seed * 109 + 1021) mod 0xfffffffe, as SimGenerateCode inlines
    it: a 32-bit mult, a 32-bit addiu, then divu for the remainder."""

    def __init__(self, seed):
        self.seed = seed & 0xFFFFFFFF
        self.count = 0

    def next(self):
        self.count += 1
        self.seed = (((self.seed * 109) & 0xFFFFFFFF) + 1021) & 0xFFFFFFFF
        self.seed %= 0xFFFFFFFE
        return self.seed % 0xFFFFFFFE


def clamp_weather(field_type, weather):
    """The jump tables at 0x003555f0 and 0x003555c0."""
    if field_type <= 4:
        return weather if weather < 4 else 0
    if field_type <= 6:
        if weather == 8:
            return 4
        if weather == 9:
            return 5
        return weather if weather < 4 else 0
    if field_type <= 10:
        return weather if weather < 8 else 0
    return weather


def merge(dst, src):
    """CopyWordParam (0x0019e500): src overrides dst field by field."""
    for k in ("fieldType", "weather", "ground", "object", "areaLevel",
              "enemyOfs", "itemOfs", "circleOfs"):
        if getattr(src, k) != UNSET:
            setattr(dst, k, getattr(src, k))
    if src.dungeonSize != 0:
        dst.dungeonSize = src.dungeonSize


def enemies(data, area, server, floor=None):
    """What ccRegisterDifficultyEnemy + ccRegisterEnemyList register."""
    event = (data.event_info(area["event"], area["volume"], area["flag71"])
             if area["event"] else None)
    rank = 25 * (area["areaLevel"] - 1) + 10 + area["enemyOfs"]
    if event is not None:
        kind = STORY_LIST_TYPE
        if event["enemy"] != UNSET:
            rank = event["enemy"]
    else:
        kind = FIELD_ATTRIB[area["fieldType"]][area["weather"]]
    rank = max(rank, 0)
    if floor is not None:
        rank += max(floor + 1, 0)
    lists, names = data.enemy_lists()
    lst = lists[server][kind]
    ids = []
    at = rank
    for _ in range(ENEMY_RANGE):
        ids.append(lst[at])
        if at + 1 != len(lst):
            at += 1
    return {"listType": kind, "rank": rank,
            "enemies": [(i, names[i] if 0 <= i < len(names) else "?") for i in ids]}


def generate(data, a, b, c, server=0, volume=None, flag71=False):
    if volume is None:
        volume = data.volume
    wa, wb, wc = data.find(0, a), data.find(1, b), data.find(2, c)
    code = wa.ID * 1000000 + wb.ID * 1000 + wc.ID
    rng = Rng(code)
    out = {"code": code, "words": (wa.text, wb.text, wc.text), "volume": volume,
           "flag71": flag71}
    out["fieldSeed"] = rng.next()
    out["dungeonSeed"] = [rng.next() for _ in range(3)]

    # Insertion sort by pri, ascending, so the highest-priority word is last.
    order = [wa, wb, wc]
    for i in range(1, 3):
        j = i - 1
        while j >= 0 and order[j + 1].pri < order[j].pri:
            order[j], order[j + 1] = order[j + 1], order[j]
            j -= 1

    base = Word()
    base.fieldType = rng.next() % 11
    base.weather = clamp_weather(base.fieldType, rng.next() % 10)
    base.dungeonSize = rng.next() % 10 + 1
    base.ground = rng.next() % 3
    base.object = rng.next() % 3
    base.areaLevel = rng.next() % 5 + 1
    base.enemyOfs = rng.next() % 20 - 9
    base.itemOfs = rng.next() % 20 - 9
    base.circleOfs = rng.next() % 3

    merged = order[0].copy()
    merge(merged, order[1])
    merge(merged, order[2])
    merge(base, merged)

    event = None
    for e in data.events:
        if (e["has_words"] and e["server"] == server and e["wordA"] == wa.text
                and e["wordB"] == wb.text and e["wordC"] == wc.text):
            event = e
            break
    if event:
        info = data.event_info(event["code"], volume, flag71)
        for src, dst in (("circle", "circleOfs"), ("enemy", "enemyOfs"),
                         ("item", "itemOfs"), ("type", "fieldType"), ("bgnum", "weather")):
            if info[src] != UNSET:
                setattr(base, dst, info[src])
        if not data.substitutes:
            # Infection: the same two cases, inline. Its event 47 values
            # (78, 122) differ from the later substitute's (42, 122), but
            # only apply from volume 3, which Infection never is.
            if event["code"] == 71 and flag71:
                base.enemyOfs = base.itemOfs = 119
            if event["code"] == 47 and volume >= 3:
                base.enemyOfs, base.itemOfs = 78, 122
    base.weather = clamp_weather(base.fieldType, base.weather)
    if base.dungeonSize >= 11:
        base.dungeonSize = 1
    out["event"] = event["code"] if event else 0
    out["timeSym"] = int(wa.ID == 131)
    for k in ("fieldType", "weather", "dungeonSize", "ground", "object", "areaLevel",
              "enemyOfs", "itemOfs", "circleOfs"):
        out[k] = getattr(base, k)
    out["levelMax"], out["roomMax"] = data.dungeon[base.dungeonSize]
    out["randcnt"] = rng.count
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("words").add_argument("elf")
    p = sub.add_parser("events")
    p.add_argument("elf")
    p.add_argument("--server", type=int)
    p = sub.add_parser("gen")
    p.add_argument("elf")
    p.add_argument("a")
    p.add_argument("b")
    p.add_argument("c")
    p.add_argument("--server", type=int, default=0)
    p.add_argument("--volume", type=int, help="default: the executable's volumeNum")
    p.add_argument("--flag71", action="store_true", help="the save flag event 71 checks")
    p.add_argument("--floor", type=int, help="dungeon floor (0 = first); omit for the field")
    args = parser.parse_args()

    data = Data(args.elf)
    if args.cmd == "words":
        print(f"{'slot':4} {'grp':3} {'ID':>4} {'pri':>4}  {'word':16} " +
              " ".join(f"{k[:6]:>6}" for k in FIELDS[2:]))
        for w in sorted(data.words, key=lambda w: (w.slot, w.group, -w.pri, w.ID)):
            print(f"{'abc'[w.slot]:4} {w.group:3} {w.ID:4} {w.pri:4}  {w.text:16} " +
                  " ".join(f"{getattr(w, k):6}" for k in FIELDS[2:]))
        print(f"# {len(data.words)} words")
    elif args.cmd == "events":
        for e in data.events:
            if args.server is not None and e["server"] != args.server:
                continue
            if not e["has_words"]:
                continue
            print(f"{e['code']:4}  {SERVERS.get(e['server'], e['server']):6}  "
                  f"{e['wordA']} {e['wordB']} {e['wordC']:16}  type {e['type']:3} "
                  f"weather {e['bgnum']:3} circle {e['circle']:3} enemy {e['enemy']:3} "
                  f"item {e['item']:3} dungeons {e['dungeonNum']} flag {e['flag']}")
    else:
        def key(s):
            return int(s) if s.isdigit() else s
        r = generate(data, key(args.a), key(args.b), key(args.c),
                     args.server, args.volume, args.flag71)
        for k, v in r.items():
            print(f"{k:12} {v}")
        for k, v in enemies(data, r, args.server, args.floor).items():
            print(f"{k:12} {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
