"""Shared pieces of the generators that write each volume's engine data as
Rust for crates/piney-data (plans/volumes.md): the four discs' executables,
the generated files' names, Rust literals, and writing or checking a file.

The port never reads an executable at run time; these generators read them
on a machine with the four discs extracted under work/, and what they write
is committed.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Volume tag -> (work/ directory, boot executable, Rust module name).
VOLUMES = {
    "INF": ("infection", "SLUS_202.67", "inf"),
    "MUT": ("mutation", "SLUS_205.62", "mut_"),
    "OUT": ("outbreak", "SLUS_205.63", "out"),
    "QUA": ("quarantine", "SLUS_205.64", "qua"),
}


def elf_path(volume):
    """The extracted boot executable of a volume ("INF", "MUT", ...)."""
    d, exe, _mod = VOLUMES[volume]
    return ROOT / "work" / d / "disc" / exe


def module(volume):
    """The generated file's module name for a volume."""
    return VOLUMES[volume][2]


def header(tool, volume):
    """The first line of a generated file."""
    return f"// Generated by tools/{tool} from {volume} {VOLUMES[volume][1]} - do not edit.\n"


def rs_str(raw):
    """A Rust string literal for bytes taken one char per byte (Latin-1), as
    the port compares the game's texts: byte for byte."""
    out = []
    for b in raw:
        c = chr(b)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            out.append(f"\\u{{{b:x}}}")
    return '"' + "".join(out) + '"'


def rs_bytes(raw):
    """A Rust byte string literal."""
    out = []
    for b in raw:
        if b == 0x5C:
            out.append("\\\\")
        elif b == 0x22:
            out.append('\\"')
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return 'b"' + "".join(out) + '"'


def write_or_check(text, out, check):
    """Write `text` to `out`, or with `check` fail (1) when `out` differs."""
    out = pathlib.Path(out)
    if check:
        if not out.exists() or out.read_text() != text:
            print(f"{out} is out of date; run without --check")
            return 1
        print(f"{out} is current")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    return 0
